### ISSUE TITLE
Elementor - Add accessible code to widgets

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#100]
Currently the widgets within Elementor are not coded to be fully accessible. We need to extend the plugin to be able to add in code to make various widget elements accessible for the sites. 

This came about in discussing the Accordion widget (https://docs.elementor.com/article/111-accordion) and the need to add aria-expanded to each accordion section.

**Comment by tap87** [comment]
https://developers.elementor.com/add-html-attribute/

**Comment by kevinkidwell** [comment]
@mhk33 Does that look like what we are trying to accomplish with being able to add those elements for accessibility?

@manolobevia Is that something that we are able to do with the code to add those in?

**Comment by mhk33** [comment]
It might be useful in some cases, but I'm not sure if this would work in the accordion example. This is what we'd need for accordions:

When closed:
<div ... aria-expanded="false">

When open:
<div ... aria-expanded="true">

I have that working on Vet, but added a snippet of JS to the theme:
https://vet.library.cornell.edu/library-collections/
https://vet.library.cornell.edu/wp-content/themes/unitlibrary/js/scripts.js?ver=1.0.0

**Comment by tap87** [comment]
Thanks @mhk33 That is good to know. @manolobevia Are we using the basic version or the pro version of Elementor?

**Comment by kevinkidwell** [comment]
@tap87 We are using the Pro version of Elementor for all of the sites.

**Comment by tap87** [comment]
Thanks @kevinkidwell It looks like the pro version lets you add custom attributes including aria. I am not sure if it has anything for accordions though. https://github.com/pojome/elementor/pull/4030

**Comment by manolobevia** [comment]
I think it is going to be a combination of adding attributes in Elementor + some JS coding to accomplish what we want.

**Comment by ramiy** [comment]
@kobizz @matipojo @bainternet @joshmarom @arielk

Read this comment: https://github.com/cul-it/uls/issues/100#issuecomment-453146934 above.

**Comment by kevinkidwell** [comment]
@tap87 @manolobevia @mhk33  I was able to add this in, starting with Hotel, so that it works for accordion elements. I added in the Code Snippets plugin so that it was easy to add and test without editing the theme JS.

This code is what I added and it works in Dev and Live (this code is how the Snippet plugin needed it organized):

function elementor_accordion_aria_expanded() { ?>
<script>
	jQuery(document).ready(function() {
		jQuery('.elementor-accordion .elementor-tab-title').attr( 'aria-expanded','false' );
		jQuery('.elementor-accordion .elementor-tab-title').click(function() {
		    if (jQuery(this).attr('aria-expanded') === 'false') {
				jQuery('.elementor-accordion .elementor-tab-title').attr('aria-expanded', 'false');
		    	jQuery(this).attr('aria-expanded', 'true');
		    }
		    else {
		       jQuery(this).attr('aria-expanded', 'false');
		    }
		});
	});
</script>
<?php }
add_action( 'wp_footer', 'elementor_accordion_aria_expanded', 99 );

**Comment by mhk33** [comment]
Great @kevinkidwell!

**Comment by tap87** [comment]
Nice work @kevinkidwell 👍
