### ISSUE TITLE
URL redirects for Mann launch

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#1001]
We're going to handle these using the Redirection plugin so they're accessible to and can be managed by our content contributors.

> Goes hand in hand with #992

**Comment by cappadona** [comment]
@sew268 @eeh53 @kevinkidwell I've gone ahead and added redirects for all of the top 50 landing pages that I shared via Slack, with the following exceptions/notes:

- [x] `/use/technology/computing/laptops`
  - created cul-it/uls#1010
- [x] `/news-events/news/{articlePermalink}`
  - set up a catch all via regex to main news page
- [ ] `/help/research-support/tutorials/gis`
  - `404` on current site
- [ ] `/help/research-support/tutorials/endnote`
  - `404` on current site
- [ ] `/search`
  - redirect created
  - suggestion: improve UX for search landing page by rendering input field for search term
- [ ] `/use/borrow-request-renew/contactless-pickup-and-curbside-delivery`
  - couldn't find equivalent page in new site
  - https://mannlib.cornell.edu/use/borrow-request-renew/contactless-pickup-and-curbside-delivery

**Comment by sew268** [comment]
@cappadona thanks!   
Can we redirect to any url?  If so, GIS can point to https://guides.library.cornell.edu/c.php?g=945956&p=6819744
And Endnote could go here: https://www.library.cornell.edu/research/citation 
I just created a page on the live site for contactless pickup and deliver: </curbside-pickup-contactless-delivery> that we can redirect to

**Comment by sew268** [comment]
oops!  lost the slug for contactless pickup and delivery on WP, it's: /curbside-pickup-contactless-delivery

**Comment by cappadona** [comment]
Thanks @sew268. We can redirect to any URL and a big thanks for creating the curbside & contactless page. All set 🙌🏼
