### ISSUE TITLE
Staff profiles: Some facets should support filtering by any/all values

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#1002]
In our meeting with Jessa yesterday, a couple of things came up around the Staff Profiles.

1. ~How will they be able to default to the more collapsed view? Is this a setting that would be able to be set in the backend so it can be changed if they want?~
   > This feature will be implemented in https://github.com/cul-it/wp-cul-theme-culu/issues/99
2. ~The icon for the more collapsed view doesn't match what is actually being shown. Would have expected to see a grid view instead of rows. Can this icon be changed to better match what the view is?~
   > Will be addressed in https://github.com/cul-it/wp-cul-theme-culu/issues/117
3. Is there a way to filter to any staff member with an Area of Expertise or Liaison area? It would be good to be able to see a filtered view where it shows anyone where that field isn't blank (could look at https://usda.library.cornell.edu/ on the search page for an example of how we do something similar).

@sew268 @eeh53 Let me know if I'm missing anything!

**Comment by cappadona** [comment]
Thanks @kevinkidwell. Specifying the view via shortcode attribute will be addressed in https://github.com/cul-it/wp-cul-theme-culu/issues/99. I've updated the description to account for this.

**Comment by cappadona** [comment]
As for the remaining two items:

2. I completely agree and discussed this with Manolo yesterday (just created https://github.com/cul-it/wp-cul-theme-culu/issues/117)
3. Not sure I follow this entirely. It sounds like you want to be able to use the facets to filter down to any staff with a value for some of the fields. I wasn't able to find an example of this on the USDA site. Maybe you can send an explicit link or share a screenshot?

**Comment by kevinkidwell** [comment]
@cappadona For #3, sure I can show some screenshots! On our search page, you can see we have our top level filters and then those can expand to show the ones below it. We're also able to filter by those top levels, which will show any publication with anything in that overarching category.

<img width="772" alt="Screen Shot 2021-03-24 at 1 59 17 PM" src="https://user-images.githubusercontent.com/29164102/112361279-98738000-8ca9-11eb-8d72-14d8590853f1.png">
<img width="902" alt="Screen Shot 2021-03-24 at 1 59 24 PM" src="https://user-images.githubusercontent.com/29164102/112361290-9a3d4380-8ca9-11eb-85b9-16cfa457dae5.png">

**Comment by kevinkidwell** [comment]
And just to note, the 3rd item in that list isn't necessary for launch but something that could be done later!

**Comment by cappadona** [comment]
Thanks @kevinkidwell. This helps me understand what's being asked but of course now I have more questions 😉 

Since this isn't intended for next week's launch I propose we update this issue to be specific for the third item in the description (facet tweaking) and save it for later after the dust settles. Deal?

**Comment by sarah-cul** [comment]
@JesiBuell79 @mhk33 

I think this is already done? Check out engineering, there are facets for the liaison area. 

https://engineering.library.cornell.edu/staff-profiles/
![image](https://github.com/cul-it/uls/assets/144364984/fbcf3aa4-fc65-4f66-b3ca-c595a213b3df)

**Comment by JesiBuell79** [comment]
Agreed -all set!
