### ISSUE TITLE
Mann homepage librarian feature

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#1003]
This came up in talking with @eeh53 but there were a few display changes that would be nice to see with this.

1. Can the photos be the same size as the other feature boxes for consistency?
2. Would we be able to unlink the staff member's title?
3. Is there a way to add Areas of Expertise and Teams like on the current site?

We are also planning to change this feature box for Mann to Meet Our Experts and use the Librarian toggle to select who we want to display in that box. Can/will discuss further at Monday's meeting.

**Comment by manolobevia** [comment]
> This came up in talking with @eeh53 but there were a few display changes that would be nice to see with this.
> 
> 1. Can the photos be the same size as the other feature boxes for consistency?
> 2. Would we be able to unlink the staff member's title?
> 3. Is there a way to add Areas of Expertise and Teams like on the current site?
> 
> We are also planning to change this feature box for Mann to Meet Our Experts and use the Librarian toggle to select who we want to display in that box. Can/will discuss further at Monday's meeting.

Yes. We can do that.

**Comment by manolobevia** [comment]
[#94](https://github.com/cul-it/wp-cul-theme-culu/issues/94) will take care of:

1. > Can the photos be the same size as the other feature boxes for consistency?
2. > Would we be able to unlink the staff member's title?
3. > Is there a way to add Areas of Expertise and Teams like on the current site?
