### ISSUE TITLE
contact us link in hero box broken

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#1007]
Email icon is not able to be set to an email address in the hero box.  one of the latest upstreams removed the email information from all units on the email icon in the hero box.  we tested on the Olin/Uris dev site to see if we could change it and it didn't work.  We looked at Catherwood, Fine Arts, and Management and they are all defaulting to the home page when clicked.

**Comment by manolobevia** [comment]
@cappadona @sew268 It has been fixed. It will be part of our next upstream.

**Comment by cappadona** [comment]
Hi @sew268. This won't be fixed until the new upstream (which is currently being built) is applied to each unit site. We can leave this open until that has happened and you've had a chance to test 😄
