### ISSUE TITLE
Elementor - Restrict access to widgets by role

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#101]
We will need to be able to restrict access to the various widgets within Elementor based on user roles within each site.

**Comment by tap87** [comment]
@kevinkidwell Have you looked at Role Manager, does that fit the requirements? https://elementor.com/blog/role-manager/

**Comment by kevinkidwell** [comment]
@tap87 That looks like it would do what I want out of that. We could restrict so that they could only edit the content currently on pages and not add any other. I think we should implement that as soon as we can on everything.

Would that work @manolobevia?

**Comment by manolobevia** [comment]
That will work!!!
