### ISSUE TITLE
Application Password plugin activation error.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1022]
Plugin could not be activated because it triggered a fatal error.
`Fatal error: Cannot declare class Application_Passwords, because the name is already in use in /code/web/wp-content/plugins/application-passwords/class.application-passwords.php on line 9`

**Comment by manolobevia** [comment]
Distributor plugin https://github.com/10up/distributor bundles application password with distributor. That means we can't have the standalone version of the same plugin installed as long as the Distributor plugin is active. Please see this [comment](https://github.com/WordPress/application-passwords/issues/115#issuecomment-703055233).

@cappadona on my local instance:
- I have deleted Application Password
- Deactivated Distributor v1.6.0
- Activated Distributor v1.6.2 (we had this version already installed)
- Deleted Distributor v1.6.0
- Updated Distributor v1.6.2 to Distributor v1.6.4

Tested the staff and everything works. 

Note: None of the distributor versions have been tested from vendor on WP v5.7.1.

**Comment by cappadona** [comment]
@manolobevia Nice find. Sounds like we should [drop `application-passwords`](https://github.com/cul-it/ci-jenkins-pantheon-wordpress/blob/98d830c73b5eb15908a4aa654bb0b2bf9d9073f0/composer.json#L119) in the next upstream.

**Comment by manolobevia** [comment]
Yes. I will remove it from the upstream.
