### ISSUE TITLE
Test and Implement Elementor Widget Manager

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#1024]
@manolobevia would you be able to test the Elementor Widget Manager plugin? I put together a [pre-release v1.0.0](https://github.com/cul-it/elementor-widget-manager/releases/tag/v1.0.0) so that it can be downloaded and added as a plugin.

I've tested this locally and it's properly hiding the Elementor widgets when I'm signed in to an account with a role other than Admin. If this works for you, we should include it in the next upstream so that I can begin opening up some page creation to users and put together additional training as needed for that.

**Comment by manolobevia** [comment]
@kevinkidwell I have tested the plugin on my local instance for Mann and [Dev Vet](https://dev-uls-vet-library-cornell-edu.pantheonsite.io/). Then deactivated the accordion and alert widgets. After that, I edited a page, and those two widgets were still visible. Please let me know what I am doing wrong.

**Comment by kevinkidwell** [comment]
@manolobevia Did you log into an account with either the Content Admin or Content Editor role? By default, it will always show all the widgets for Administrators, in case there are more complex pages that might need created for stakeholders but it should remove those that you deactivate for those other roles.

**Comment by manolobevia** [comment]
@kevinkidwell I logged in with admin role, with editor role works.
