### ISSUE TITLE
Migrate Qualtrics forms to LibWizard

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#1028]
Due to some issues with reply emails that are fed into LibAnswers from Qualtrics forms, workarounds are being used by staff members at the moment. With the approval of using Springshare products with the accessibility roadmap, we are able to utilize LibWizard which will properly feed forms into LibAnswers. These are the steps that need to be taken to do this migration:

1. Set up timeline for form migration
2. Move forms to LibWizard (double check all settings with reply-to emails and conditional sending options)
3. Contact Springshare launch/LibAnswers team to test forms (in some cases individual units may be needed)
4. Notify unit stakeholders prior to switch from Qualtrics on their unit sites
5. Change all forms on unit sites to the LibWizard links

**Comment by mhk33** [comment]
Do you think this is something we should also do for non-unit sites that use Qualtrics for forms?

**Comment by kevinkidwell** [comment]
@mhk33 If those other sites have forms that integrate with LibAnswers then I would say yes. The biggest reason for this switch is that we can't indicate a dynamic Reply To field in Qualtrics so things were being missed and not sent to patrons. There's currently a workaround of editing the LibAnswers tickets but LibWizard forms allow for this dynamic reply email.

**Comment by mhk33** [comment]
Okay, got it. It might be good to have one solution for all forms, but I don't know if LibWizard makes sense, if the form does not have integration with LibAnswers.

**Comment by JesiBuell79** [comment]
@mhk33 - still an issue?  Not sure where these qualtrics forms are?

**Comment by mhk33** [comment]
As far as I know all forms were moved to LibWizard. It's possible a couple are on Qualtrics for the main site, I but I think that's fine for now.
