### ISSUE TITLE
Setup new staff interface page in all units.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1035]
All the units are now using the new staff interface except for: Management, Psl , and Ilr. Those units don’t display any profile in the new staff interface. I think this is due to the domain redirect and how we have defined this sites in our unit configuration yaml file (cul-config.yml).
Ex: https://management.library.cornell.edu/ is redirected to https://johnson.library.cornell.edu/ and in our yaml file we have added Management instead of Johnson.  @cappadona do you think that could be the reason?

**Comment by cappadona** [comment]
@manolobevia Thanks for quickly adding the Vue app to the PSL site so we could verify our suspicion. I have some ideas on how we can handle this, which all essentially hinge on introducing an _alias_ for units with domain redirects. I can set aside time next week to work on this with you if you want.

**Comment by JesiBuell79** [comment]
will revisit staff profiles once decisions have been made
