### ISSUE TITLE
Fix link Full Hours style for OLINURIS staff page in child theme.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1036]
![Screen Shot 2021-05-17 at 10.20.58 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/cce8877b-0039-45a8-abfb-600a9482fb99)

**Comment by cappadona** [comment]
@manolobevia This _should_ be a simple fix by scoping the styles, as we did for the software list in https://github.com/cul-it/wp-cul-theme-culu/pull/9.

**Comment by manolobevia** [comment]
The hours display for OLINURIS has been defined in the child theme. I might have something that overrides some css. This is not happening with the rest of the units.
