### ISSUE TITLE
Git rebase to integrate the latest upstream into unit sites

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1055]
- [x] africana
- [x] annex
- [x] asia
- [x] engineering
- [x] finearts
- [x] hotel
- [x] ilr
- [x] law
- [x] makerspace
- [x] management
- [x] mann
- [x] mathematics
- [x] music
- [x] olinuris
- [x] psl
- [x] rare
- [x] uls-library-cornell-edu
- [x] vet

**Comment by jgreidy** [comment]
ILR is ready
https://dashboard.pantheon.io/sites/1d4cf8dc-dcef-4f4e-adef-7f7a2e2d3e0c#upa-jgr25

**Comment by jgreidy** [comment]
finearts and hotel are also ready

**Comment by jgreidy** [comment]
The related JIRA issue: https://culibrary.atlassian.net/browse/CULWEBDEVTEAM-1114

**Comment by jgreidy** [comment]
management is ready
https://dashboard.pantheon.io/sites/b79409ad-3d8a-44e8-9585-dd430c6e3ab8#upd-jgr25

**Comment by jgreidy** [comment]
mathematics is ready
https://dashboard.pantheon.io/sites/430a238b-b9f9-4244-81f7-d47d8ef92a32#upe-jgr25/code

**Comment by jgreidy** [comment]
music is ready
https://dashboard.pantheon.io/sites/b713fe01-d6ad-4344-8804-6dd2c13d2572#upf-jgr25

**Comment by jgreidy** [comment]
psl is ready
https://dashboard.pantheon.io/sites/ba552c66-aa18-4202-b712-b8612d0d6d11#upg-jgr25
