### ISSUE TITLE
Test multidev env in all units with the latest upstream and apply it to dev.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1056]
Review [#1055](https://github.com/cul-it/uls/issues/1055). Backup live sites. Test multidev env, then merge it into dev, and migrate to test, live for:

- [x] africana
- [x] annex
- [x] asia
- [x] engineering
- [x] finearts
- [x]  hotel
- [x] ilr
- [x] law
- [x] makerspace
- [x] management
- [x]  mann
- [x] mathematics
- [x] music
- [x] olinuris
- [x] psl
- [x] rare
- [x] uls-library-cornell-edu
- [x] vet

**Comment by jgreidy** [comment]
uls-library-cornell-edu is ready to test
https://dashboard.pantheon.io/sites/2845285d-0b3c-47c1-9df3-29a15a558309#up9-jgr25

**Comment by manolobevia** [comment]
uls-library-cornell-edu tested and merged. Thanks.
