### ISSUE TITLE
Add units alert.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1074]
Message: `The library spaces are closed to students and visitors. Others please check building hours.`
Link `building hours` to https://www.library.cornell.edu/libraries

@kevinkidwell are stakeholder able to do this on their own?

........
Future feature to consider. Add global alert message to all units at one.

**Comment by kevinkidwell** [comment]
Stakeholders can add their own alerts for unit sites but for the sake of speed, I'll probably go in and add them, along with letting the stakeholders know.
