### ISSUE TITLE
Accessibility: Links are not clearly identifiable

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#1082]
This has been coming up on multiple unit sites in SiteImprove. It seems like the footer links are getting flagged. Can we underline these to make them identifiable and stand out? Should this be done at the theme level?

![image](https://user-images.githubusercontent.com/29164102/152417057-f547841d-7e35-4fe7-b3ee-3061b278ede4.png)

**Comment by manolobevia** [comment]
@kevinkidwell Yes. It will be fixed at the theme level. Also, part of the next upstream, which is going to be in the next couple of days. Let me know if you have more accessibility issues to be fixed.

**Comment by manolobevia** [comment]
@kevinkidwell can we make the bold, so we are consistent with the rest of the links?
