### ISSUE TITLE
MANN unit: Remove CALS logo in footer.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1091]
The graphic representing CALS is not an approved wordmark. CALS COMM requested to remove it immediately.

**Comment by eeh53** [comment]
Here is the new approved wordmark supplied by CALS.

![CALS Vertical Wordmark-color (3)](https://user-images.githubusercontent.com/17053005/166009462-86e3c25e-f80b-4d48-8215-51b179fd6f2d.png)
