### ISSUE TITLE
ULS UNITS HOTEL - Make link colors consistent across all the pages.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#111]
![Artboard.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/6294518b-9c9b-4708-9b10-f4445713f58d)

**Comment by manolobevia** [comment]
@kevinkidwell Please update the links to become relative path.

**Comment by kevinkidwell** [comment]
Adjusted all link colors and paths.
