### ISSUE TITLE
Background issue in hero image for interior pages in Music library

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1116]
From Tracey L. Snyder 
Lenora noticed that when you go to any page on our website other than the homepage, the purple banner covers most of the Mozart statue — all but the top of his hair. Simeon happened to be over here for a visit and agreed that you would be the person to bring questions and issues to about our website that are out of my control. Thanks for looking into this.

**Comment by JesiBuell79** [comment]
Closing
