### ISSUE TITLE
Update PHP to v7.4

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1133]
> Your site is running an insecure version of PHP (7.3.33), which should be updated.
> What is PHP and how does it affect my site?
> PHP is the programming language used to build and maintain WordPress. Newer versions of PHP are created with increased performance in mind, so you may see a positive effect on your site’s performance. The minimum recommended version of PHP is 7.4.
>

**Comment by manolobevia** [comment]
@jgreidy for updating the upstream to PHP 7.4, I just need to update the PHP version on the composer.json file. Right?

**Comment by JesiBuell79** [comment]
@jgreidy do you know if this happened?

**Comment by JesiBuell79** [comment]
Need 7.3 for upstream per Jim.  Will reopen in the future
