### ISSUE TITLE
ULS UNITS PSL - Accessibility assessment

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#114]

**Comment by kevinkidwell** [comment]
We are currently waiting for CIT to perform their manual assessment and will revisit with those results.

**Comment by mhk33** [comment]
A quick look at SiteImprove and I think PSL has more content-related errors that should be fixed (outside of any theme changes). I'm not sure if this should fall to the client or us/UX?

**Comment by mhk33** [comment]
This page has empty h2's with links, throughout:
https://physicalsciences.library.cornell.edu/category/physics-journals/

Not sure how this is built, but can they be removed? @manolobevia @kevinkidwell

**Comment by mhk33** [comment]
Manual check by CIT:

Physical Science Library -  https://docs.google.com/spreadsheets/d/1ggLYECt1iGmWCK5YokRIuiwKCr7uFOosLALkZxcNmC4/edit?usp=sharing
