### ISSUE TITLE
Update ULS central repo.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#1153]
CULU theme changes:

- Add new staff custom fields to support the new staff interface from CUL main site
- Add new staff taxonomies to support the new staff interface from CUL main site

**Comment by JesiBuell79** [comment]
@mhk33 - do you know what he means by this?

**Comment by mhk33** [comment]
Sounds like these are updates to the staff profiles repo from the unit sites to support having profiles on the main site, but we are on hold with that. I'm not sure if this is still needed.

**Comment by JesiBuell79** [comment]
I'm going to close this one for now - we can reopen if needed
