### ISSUE TITLE
Clean up user accounts

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1176]

**Comment by mhk33** [comment]
Some staff have left and should be removed from units. Will need to ensure that we don't lose their content if removing accounts.

**Comment by JesiBuell79** [comment]
https://github.com/cul-it/uls/issues/1109

**Comment by sarah-cul** [comment]
When distributor plugin was deactivated last month, any discrepancies between unit sites and the central repo were resolved and confirmed with the content owners.

**Comment by mhk33** [comment]
@sarah-cul I'm trying to remember if this was about cleaning up WP user accounts for people no longer at CUL? Like Manolo, Kevin, Darcy, et al. I don't know what happens to their content if you delete old users.

**Comment by sarah-cul** [comment]
Oh! Thats interesting, I will keep this open and look into that.

**Comment by mhk33** [comment]
Thanks! I have a similar issue in the main site repo, too, haven't had a chance to look at what the ramifications are for removing users.

**Comment by sarah-cul** [comment]
if we delete a user, all content that user created will remain on the site but the author of the content becomes "anonymous". 

Alternatively, instead of deleting the user, we can change their role.. maybe to one with no permissions. 
I like knowing when and by who something was created, so I like this idea. 

do you know if the passwords have been changed? It might still be possible for people who left to access the sites?

**Comment by sarah-cul** [comment]
Strategy:

-  AAM -> New Role "Blocked" does NOT inherit anything
- update the user profile by changing their role to "Blocked", uncheck show toolbar
<img width="400" alt="image" src="https://github.com/cul-it/uls/assets/144364984/914468de-6d01-4a32-8fba-bfb8c1a5318e">

<img width="300" alt="image" src="https://github.com/cul-it/uls/assets/144364984/60ce909d-d985-4753-a2b5-124ea7eef21c">

**Comment by sarah-cul** [comment]
- [ ] Africana
- [ ] Annex
- [ ] Asia
- [ ] Catherwood
- [ ] Engineering
- [ ] Finearts
- [ ] Hotel
- [ ] Law
- [ ] Management
- [ ] Mann
- [ ] Math
- [ ] Music
- [ ] OlinUris
- [ ] PSL
- [ ] Rare
- [ ] Tech
- [ ] Vet

**Comment by sarah-cul** [comment]
Added documentation "Blocking a User" and listed it here: https://confluence.cornell.edu/display/CULITSD/Content+Contributors+-+Documentation
