### ISSUE TITLE
Update Web Accessibility email to form across footers

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1184]
Should no longer be pointing to web-accessibility@cornell.edu -- rather, it should send people to https://tdx.cornell.edu/TDClient/39/Portal/Requests/ServiceDet?ID=373

**Comment by mhk33** [comment]
The units (and likely most of our other sites) point to this page, and I see that it was updated, so we should be good to go.
https://www.library.cornell.edu/web-accessibility
