### ISSUE TITLE
Staff Profiles display problems

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#1191]
Elementor plugin (regular or PRO?) is involved with the staff profile page on the ULS sites, like
https://test-uls-management-library-cornell-edu.pantheonsite.io/staff-profiles/

Admins can edit the profile display with either WordPress or Elementor. With WordPress, you can see either a list of images and text, or the shortcode [staff]. I have not been able to edit with Elementor - not sure why.

The list of images and text seem to be left over from some previous incarnation of the staff profile. In some cases, I was able to replace the images and text with [staff] and the staff page worked again after saving.

In the management site, when I replace the images/text with [staff] on the test site, I get 9 staff members (https://test-uls-management-library-cornell-edu.pantheonsite.io/staff-profiles/). When I try that on the live production site (https://johnson.library.cornell.edu/staff-profiles/) I get 193 staff members.

**Comment by jgreidy** [comment]
The ACF plugin has a field group called 'Staff Profile'. These field groups seem to correspond to the menu items
<img width="1464" alt="Screenshot 2023-05-11 at 3 28 31 PM" src="https://github.com/cul-it/uls/assets/5996967/049ad90d-3fa9-45d6-a049-f5e119f14fac">

**Comment by jgreidy** [comment]
I left the management production site with 0 Staff Profile showing rather than have the confusing 193 showing.

**Comment by jgreidy** [comment]
This is a problem for sites where the Pantheon name (uls-<<this part>>-library-cornell-edu) does not match the actual domain name of the production site.
ILR -> catherwood
Management -> Johnson
psl -> physicalsciences

Ilr is currently not fixed in the upstream, the other two are fixed.

**Comment by jgreidy** [comment]
https://catherwood.library.cornell.edu/staff-profiles/

ILR Catherwood is now fixed.

**Comment by sarah-cul** [comment]
@jgreidy @mhk33 
Reading through the comments on this issue concerning the incorrect number of staff profiles, I think it is resolved. I'm not totally sure but your comments seem to suggest you had deployed a fix. Can you confirm?  As of 9/14:

16 staff for     https://catherwood.library.cornell.edu/staff-profiles/ 
2 staff for       https://physicalsciences.library.cornell.edu/
7 staff for       https://johnson.library.cornell.edu/staff-profiles/
12 staff for     https://asia.library.cornell.edu/staff-profiles/
Some of them have profile pics and some do not. 

Is there a bigger issue that is still left to be done here that I am not fully understanding? Thanks.

**Comment by mhk33** [comment]
I think this was fixed. Right, @jgreidy?
