### ISSUE TITLE
Check for newcatalog domain on unit sites

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1193]
And change to catalog domain as needed

**Comment by mhk33** [comment]
@sarah-cul It looks like the Mann website search box is searching the newcatalog.library.cornell.edu domain instead of catalog.library.cornell.edu. Can this be easily changed? Would it need to be updated in the central theme and then pushed out to all the units?

Also, ideally content editors should check if they have links to the newcatalog in the content and update them. A quick search for "catalog" on the Mann site and I found a couple of pages such as:
https://mann.library.cornell.edu/print-collections
https://mann.library.cornell.edu/cornell-agritech

Would it be best to email stakeholders directly and ask them to change the links? Although we have redirects, we probably want to change the URLs if possible.

**Comment by sarah-cul** [comment]
@mhk33 You are correct, I just found a search.js inside the culu theme that is pointing to newcatalog.library.cornell.edu. Ill make that update for the theme and it can be included in the next upstream effort. thanks for finding that! 

As far as content, that would be good to let content owners know, but I'm wondering in the past when our group transitioned to use "newcatalog" was that effort made by us? If so, maybe I should be the one to clean it up?

**Comment by mhk33** [comment]
@sarah-cul I updated the links on the main site, but it was mostly because it was just one site and relatively easy for me to do. If you want to do this on the units, I can try to help if we divvy them up. I can understand how that might be easier, overall, than communicating with and waiting for stakeholders to do it themselves.

I think it was relayed to librarians to update their guide links, too, but I have doubts that people did that with older guides.

**Comment by sarah-cul** [comment]
@mhk33  This might take some time. there are also bit.ly links that refer to newcatalog: 
<img width="350" alt="image" src="https://github.com/cul-it/uls/assets/144364984/eac500f9-ffdb-4473-9513-6b5133fdc1bf">
Those will need to be replaced with new bit.ly links, of just replaced? Not sure why they are necessary. 

I can keep a checklist on this issue, and just try to tackle the sites when possible.

**Comment by sarah-cul** [comment]
Checklist for ULS:

- [x]  Africana
- [x]  Annex
- [x]  Asia
- [x]  Catherwood
- [x]  Engineering
- [x]  Finearts
- [x]  Hotel
- [x] Law
- [x] Management
- [x] Mann
- [x] Math
- [x] Music
- [x] OlinUris
- [x] PSL
- [x] Rare
- [x] Tech
- [x] Vet

**Comment by mhk33** [comment]
@sarah-cul No idea about the bit.ly links, I wonder who made them. Perhaps a previous developer? Good catch. I'm not sure why we need them either.

**Comment by sarah-cul** [comment]
while going through the sites, I'm checking code snippets and posts by running a terminus command
`terminus remote:wp uls--site.live -- db search 'newcatalog.library'`

`terminus remote:wp uls-site.live -- db query "SELECT ID, post_title FROM wp_posts WHERE post_content LIKE '%newcatalog.library.cornell.edu%'"`

**Comment by sarah-cul** [comment]
@mhk33 made some progress this past sprint on these, more than halfway through now!

**Comment by sarah-cul** [comment]
UPDATE -  the db: all the custom post loops, and the RSS feeds. (Asia had many)

`terminus wp <site.live> -- db query "UPDATE wp_postmeta SET meta_value = REPLACE(meta_value, 'https://newcatalog.library.cornell.edu/', 'https://catalog.library.cornell.edu/') WHERE meta_key IN ('online_copy', 'url', 'wprss_url', 'wprss_item_source_url', 'wprss_item_permalink') AND meta_value LIKE '%https://newcatalog.library.cornell.edu/%'"`
  
------------------
QUERY MENU:
`terminus wp <site>.live -- db query "SELECT p.ID, p.post_title FROM wp_posts p INNER JOIN wp_postmeta m ON p.ID = m.post_id WHERE m.meta_key = '_menu_item_url' AND m.meta_value LIKE '%newcatalog.library%' AND p.post_status = 'publish' AND p.post_type = 'nav_menu_item'"`

----------------------
QUERY LATEST REVISION ONLY:
`terminus wp <site>.live -- db query "SELECT p.ID, p.post_title FROM wp_posts p WHERE p.post_content LIKE '%newcatalog.library%' AND p.post_status = 'publish' GROUP BY p.post_title ORDER BY p.post_modified DESC"`

------------------
QUERY SHOWS SPECIFIC META FILED NAMES
`terminus wp <site>.live -- db query "SELECT p.ID, p.post_title, m.meta_key FROM wp_posts p INNER JOIN wp_postmeta m ON p.ID = m.post_id WHERE m.meta_value LIKE '%newcatalog.library%' AND p.post_status = 'publish' GROUP BY p.post_title, m.meta_key ORDER BY p.post_modified DESC"
`
 
------------------
QUERY CONTENT FOR SPECIFIC POST 
`terminus wp <site>.live -- db query "SELECT post_content FROM wp_posts WHERE ID =<post id>"`

**Comment by mhk33** [comment]
Nice job! That was a lot.
