### ISSUE TITLE
Olin-Uris staff profile change not propagated to central repo

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1194]
From Xan:

`Is there a way we can get rid of the Language of Expertise option on the Olin profiles? I can’t figure out how to remove it. Hannah Toombs was the only one with a language listed and it was decided to not have that option at all if she was going to be the only one. We tried to remove Spanish from Hannah’s profile but it still shows up and I deleted it from the list in WP.`

I checked the Olin-Uris profile from Hannah and see Spanish has been removed from the Language field. According to the [documentation](https://github.com/cul-it/uls/wiki/Add-edit-delete-staff-profiles), this should automatically update the central repo. However I still see Spanish listed in Hannah's central profile. Perhaps the Olin-Uris site is no longer talking to the central repo?

In the same request, Xan had asked that Kristen and Tony be removed. She had removed them from the Olin-Uris site. I removed them from the central repo and they're no longer on the O-U site. So that worked at least.

**Comment by mhk33** [comment]
@jgreidy edited Jenny's central repo profile by unlinking it and left it "unlinked." After clearing the cache her profile now has the correct title on the Mann site.

This doesn't fix the issue of Jenny's profile being missing from the Mann site, but at least the title is changed now.

**Comment by jgreidy** [comment]
The olinuris site has 2 copies of the Distributor plugin. Who knows what that does?

**Comment by jgreidy** [comment]
Management also has 2 Distributor plugins. For Management and olinuris, the older one is called distributor-stable, the newer one is called distributor. I'm going to try deleting the distributor-stable one for the management multidev 'getupstream' to see if that changes anything with the staff profiles.

**Comment by jgreidy** [comment]
Profile problems were taken care of by 'distributing' the profiles. Putting off plugin cleanup till later on.

**Comment by mhk33** [comment]
Did you see the first part of the description about the Language field displaying for Hannah Toombs?
https://olinuris.library.cornell.edu/staff-profiles

If you go into her profile Spanish on the O/U site, Spanish is not in the field (Xan removed it), but it still displays.

**Comment by mhk33** [comment]
See #1225 - @sarah-cul removed the older version of the two plugins.

**Comment by sarah-cul** [comment]
Spanish is gone now, was likely an issue with the older plugin being activated
