### ISSUE TITLE
Mann staff member not showing up in admin

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1195]
Jenny L. is listed on the [Mann staff page](https://johnson.library.cornell.edu/staff-profiles/), but she doesn't have a post in the [Mann staff admin](https://mann.library.cornell.edu/wp/wp-admin/edit.php?post_type=staff). She is in the [central staff repo](https://live-uls-library-cornell-edu.pantheonsite.io/wp/wp-admin/users.php).

From Alex at Mann:

Thanks for reaching out! The main reason that I ran into this bug is due to needing to update Jenny's listing as I noticed there's a typo and it's a bit outdated. For her listing, I'd just need to update her title to be " Exhibit Designer & Outreach Spaces Coordinator".

**Comment by mhk33** [comment]
@jgreidy edited Jenny's central repo profile by unlinking it and left it "unlinked." After clearing the cache her profile now has the correct title on the Mann site.

This doesn't fix the issue of Jenny's profile being missing from the Mann site, but at least the title is changed now.

**Comment by jgreidy** [comment]
Jenny Leijonhufvud is showing up on the Mann profiles page now. Her title is 'Exhibit Designer & Outreach Spaces Coordinator'.

**Comment by mhk33** [comment]
@jgreidy I checked and she doesn't show up in the admin side for staff profiles, like the way it works for everyone else:
https://mann.library.cornell.edu/wp/wp-admin/edit.php?post_type=staff

She does show up on the public Staff Profiles page.

**Comment by jgreidy** [comment]
@mhk33 That is strange. If you were making a new staff profile, would you do it on the central site (live-uls-library-cornell-edu), or on the site where it was supposed to show up?

**Comment by mhk33** [comment]
@jgreidy I wasn't involved when they created the profile app, but I believe you have to create the profile in the unit site and then "distribute" it to the central repo (see the [documentation](https://cornell.app.box.com/s/53nvqbrqlzuuxk30k7b2m7f5bqnt2z46) and also how to [add/edit/delete](https://github.com/cul-it/uls/wiki/Add-edit-delete-staff-profiles)). So all edits to a profile should happen on the unit site. Per the [comment](https://github.com/cul-it/uls/issues/1195#issuecomment-1594761473) above, you had unlinked the profile in the central repo from the unit profile, edited it the central repo, and the edits seemed to propogate to the unit.

Jenny's profile is the only one I've heard of where she's missing completely from the admin side of the unit.

**Comment by sarah-cul** [comment]
Note: Claire Deng staff profile had same issues as Jenny

**Comment by sarah-cul** [comment]
same issues for profiles: Emma Sosebee & Alex Palacios

**Comment by sarah-cul** [comment]
These distribution issues are fixed with the change to no longer use the central repository
