### ISSUE TITLE
Distributor plugin licence and user needs update

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#1197]
From checking olinuris uls site I see that Manolo used his user info on https://live-uls-library-cornell-edu.pantheonsite.io/wp/wp-admin/admin.php?page=distributor-settings to get a licence key, and is using his login info for live-uls-library-cornell-edu to connect olinuris to the central distributor hub.

I don't see any info about the distributor license in LastPass.

We should have a special user to use for the distributor link from ULS sites to live-uls-library-cornell-edu.

**Comment by sarah-cul** [comment]
Need to better understand how to set this permission to allow the unit sites to push a staff profile to the remote site (https://live-uls-library-cornell-edu.pantheonsite.io/wp/wp-admin/index.php) 
in the settings of the plugin on the unit sites, check to see what the staff post type is allowed to do
![image](https://github.com/cul-it/uls/assets/144364984/74244b21-bd56-43ac-a3f1-b081fcea0c3a)

Also, check all unit sites and see what user roles have the ability to do this: 
![image](https://github.com/cul-it/uls/assets/144364984/d55ced0d-4b65-4887-93d2-c7c7c60c11f6)

**Comment by sarah-cul** [comment]
no longer using distributor plugin
