### ISSUE TITLE
Unit Information Architecture

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#12]
**Home**
- Modules determined by templates and customized per unit

**About (info about unit site)**
- Staff profiles
- FAQs distinct to unit
- Hours

**Resources (resources for research, faculty, students, etc.)**
- Databases
- Guides
- Collections
- Catalog

**Services (main CUL services)**
- Borrowing & Delivery
- Links back to main CUL site for information

**Use the Library (unit-specific services)**
- Spaces
- Equipment
- Course Reserves

**News & Events (unit news, events, regularly updated content)**
- Blog(s)
- News
- Events

I have been going through all of the unit website information that I wrote down when doing the audit of the unit sites a while back and trying to come up with a universal architecture that we can use for the main links on each unit site. This is what I have come up with because most units actually have the same kind of content.

I think the best way to look at this is to come up with top-level definitions and then help each unit fit their content into these categories on a unit-by-unit basis. We can give them this information with the samples of what will go under each link, have the stakeholders take this back to their units and come up with their own structure of links under these that we could review and make sure fit our definition where they are put. 

I would like to keep all of the units with the same structure when it comes to these links so that this is the maximum of what they can have, but if they don't want to use a link, we could omit it from the lineup. 

Please let me know any thoughts here @manolobevia @mhk33

**Comment by mhk33** [comment]
@kevinkidwell This looks like a great structure to start with. I also wonder if we want to plan to go with something like this for the main site (www.library.cornell.edu), or maybe that is also what you were thinking? I don't know if there is someone from the leads or stakeholder group who will be spearheading info architecture on the main site.

**Comment by kevinkidwell** [comment]
@mhk33 I don't know if this would be what we want for the main site or not just because of the amount of information and everything that is currently displayed. The main site IA is probably something that will come out of the CUL Online project once more information on that and who is being charged with doing what there.
