### ISSUE TITLE
Add Instagram icon to Africana

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1203]
Email request today --

Hello, Jesi.

My instagram handle is cornellafricanalibrary.

Link below
https://www.instagram.com/cornellafricanalibrary/

**Comment by mhk33** [comment]
@JesiBuell79 This is all set. I never added a social media icon for a unit site before and it was pretty easy:

1. Appearance > Customize > Widgets > Social Media
2. Enter the URL for the social media account you want to add in the appropriate field (e.g. Instagram).
3. Publish

This is built into the theme, I guess, and the icon just appeared once I did this.

**Comment by JesiBuell79** [comment]
Ah beautiful - thank you!!

Jesi Buell (she/her)
Manager of Library Applications Development
p. (607) 255-1769
Cornell University Library<http://www.library.cornell.edu>
Need development help? Contact ***@***.******@***.***>

________________________________
