### ISSUE TITLE
Database button doesn't work on Engineering site

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1207]
From: Jill H. Powell <jhp1@cornell.edu>
Date: Wednesday, August 23, 2023 at 11:43 AM
To: Melissa Wallace <mhk33@cornell.edu>
Subject: FW: Access the Cornell IEEE library
We can respond to the patron with the correct address but can’t find this page to correct it. It’s correct in the Engineering Databases page we link from the main page.
 
problem page - [library webpage on IEEE Xplore](https://engineering.library.cornell.edu/database/ieee-xplore/)
IEEE address - http://resolver.library.cornell.edu/misc/3847710.
 
thanks,
Jill
 
Jill H. Powell, Engineering Librarian
Cornell University
Ithaca, NY 14853
[Jhp1@cornell.edu](mailto:Jhp1@cornell.edu) 
 
From: Hyunjung Lee <hl867@cornell.edu> 
Sent: Wednesday, August 23, 2023 11:31 AM
To: Jill H. Powell <jhp1@cornell.edu>
Subject: Fw: Access the Cornell IEEE library
 
Hi Jill,
 
A patron found a [library webpage on IEEE Xplore](https://engineering.library.cornell.edu/database/ieee-xplore/) with a broken button. I tried to find a way to edit this page but failed. Do you have any suggestions on how to edit this page?
 
Thanks so much!
Hyunjung
...

**Comment by mhk33** [comment]
It looks like the link to the button is on a `<button>` tag and not `<a>`. If you change it to `<a>` in the source it works.

I'm not sure if this is a ULS template thing that affects other sites or only on Engineering.

**Comment by jgreidy** [comment]
I'm looking into adding a snippet to handle that display. I can't figure out where Elementor gets the code that draws those pages.

**Comment by sarah-cul** [comment]
@jgreidy @mhk33 
I'm currently going through the backlog of issues and researching them a little. My attempt to reproduce this particular issue failed,. The broken link on this button seems to be working now. Is this issue resolved?

**Comment by mhk33** [comment]
Yes, I think this is done. Thanks for checking!
