### ISSUE TITLE
filter by topic on math doesn't go further than letter N

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1208]
Hi web developers,
 
The filter by topic feature for https://mathematics.library.cornell.edu/recommended-books/ only lists author names up to the letter N. I suspect that a limit was set to the number of results to be returned. Could this number be increased to include all authors ?
 
Henrik
 
Henrik Spoon

**Comment by mhk33** [comment]
I see 192 Recommend Books in WordPress: https://mathematics.library.cornell.edu/wp/wp-admin/edit.php?post_type=recommended_books

Seeing if I can export them or find an easy way to see all the data to confirm that we only have to author 'N'. Perhaps the initial import was not complete.

**Comment by mhk33** [comment]
Never mind - it looks like we do have author names after 'N' but the facet doesn't display them.

**Comment by sarah-cul** [comment]
This can be done in the WPAdmin -> Settings -> FacetWP
Look at the 3rd row Author Last Name...  notice it says 186 Rows. This is the total # of authors. To make sure all authors are seen in the facet, click on "Author Last Name" to drill into the settings. 
Change the Count field 100 to 200. 
Click Save Changes. 
![image](https://github.com/cul-it/uls/assets/144364984/65d3365c-1f05-45aa-b1d4-3b5416c021c3)
![image](https://github.com/cul-it/uls/assets/144364984/d378250c-4a6a-4159-b9a7-613dc2ad222e)
