### ISSUE TITLE
Content improvements for Management Library

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1218]
At the 10/4/23 stakeholder meeting, Susan Kendrick requested a meeting to discuss some improvements to the Management Library (need more details).

She mentioned that Physical Sciences looked nicer and she wasn't sure how to make those kinds of changes. She said their site is text heavy.

**Comment by mhk33** [comment]
From: Susan F. Kendrick <sfk23@cornell.edu>
Date: Monday, November 27, 2023 at 11:46 AM
To: Jesi Buell <jcb79@cornell.edu>, Cornell University Library IT Developer Team <cul-dev@cornell.edu>
Subject: Management Library website change requests
Hi Jesi and team,
 
I hope everyone had a great holiday break!  Here are a few ideas for snazzing up our website. Let me know if you have any questions. The  main thing is to put the most used resources on the home page so students can get right to it. Then the “more” link would be to a list of all the databases on one page. Or all the databases in that category on one page. 
 
•	Databases list all on one pages like Nestlé has [https://hotel.library.cornell.edu/research-databases/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhotel.library.cornell.edu%2Fresearch-databases%2F&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674649367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5xJocLrD0AKSqIQ9aK%2FwilN03p5f721td8XZ1jh1Nmo%3D&reserved=0)
•	If we could have all FAQs on one page that would be amazing too. 
•	Accordion – expand all and contract all for the databases. 
 
Icons that might come in handy. Doesn’t have to be these, but gives you an idea of what might work:
•	House (Folks might not realize that clicking Management Library in the banner takes them back to the Home page) [https://fontawesome.com/icons/house?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fhouse%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674649367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B1U9MQd9pRAMLdq96%2BYQ2Ao9MN7gl5BDwvSWF3oVYX0%3D&reserved=0)
•	Handshake for career resources [https://fontawesome.com/icons/handshake?f=classic&s=regular](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fhandshake%3Ff%3Dclassic%26s%3Dregular&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674649367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xhv2Z3EuBGOUqd8%2Fs7nnWhCVR4OBUPS%2Ba9DEoq6x050%3D&reserved=0) and newspapers [https://fontawesome.com/icons/newspaper?f=classic&s=regular](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fnewspaper%3Ff%3Dclassic%26s%3Dregular&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674649367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nV18vm5gy3C5%2BmdC9Hpb9dnqyphvw1%2ByhXmFoPdL7s0%3D&reserved=0)
•	Link for accessing databases [https://fontawesome.com/icons/link?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Flink%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7K3pT%2F4osno2bGhWWNAvvXjWAnUF2uKX4La5X7sA90s%3D&reserved=0)
•	Clock next to hours [https://fontawesome.com/icons/clock?f=classic&s=regular](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fclock%3Ff%3Dclassic%26s%3Dregular&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BzoZFAs8oboD5v38BJZhyD5Nz5738QN8Pqudta8E%2F2Y%3D&reserved=0)
•	Database [https://fontawesome.com/icons/database?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fdatabase%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YLjgUwBOYPP4elC4TZJAUMp%2Fp7mrG7LHtVEk%2F2xw0Jc%3D&reserved=0)
•	Info for FAQs [https://fontawesome.com/icons/circle-info?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fcircle-info%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2xa1pfq0EKM6dKuzhzhoMixX6eNVgUynhalta8FT6jk%3D&reserved=0)
•	Because every site needs an Easter egg [https://fontawesome.com/icons/spaghetti-monster-flying?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fspaghetti-monster-flying%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tubx6N9nJ1%2B18Zgc9mKEDBSquhumVSdrX0LS9mlyQ8I%3D&reserved=0)
•	Possibly for finance [https://fontawesome.com/icons/money-bill-trend-up?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fmoney-bill-trend-up%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q3HQ7iljxrusoFcAPLij9i7g3dwXlVV%2BT4WjCmZP%2BZI%3D&reserved=0)  or this one [https://fontawesome.com/icons/arrow-trend-up?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Farrow-trend-up%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ksy%2F%2FYBQPGB0HYSvaVcGZOtJtDDMdZgrw4C1wtZIgww%3D&reserved=0)
•	For reserves [https://fontawesome.com/icons/book-open-reader?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fbook-open-reader%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ssGG6bhFKjLV5VyzDc1u%2FsxRUK%2F4dWMjOgHiueRWLbg%3D&reserved=0)
•	Possibly for industry and market [https://fontawesome.com/icons/industry?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Findustry%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FpKl2sz7Io6%2BvxJKZL7GcuFI842HQ1lTqU2MMNLJbqo%3D&reserved=0) (or similar like [https://thenounproject.com/icon/industry-1241105/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fthenounproject.com%2Ficon%2Findustry-1241105%2F&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wtioKHMDOwG6FuHRELjneLDBxEqc1VizzD4wa9%2BTmxI%3D&reserved=0)) and [https://fontawesome.com/icons/magnifying-glass-chart?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fmagnifying-glass-chart%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003674805665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oCLVN2CfEb%2FVlSDRtCk00PJ45psxO4p90uXjYDaXDSc%3D&reserved=0)  or [https://fontawesome.com/icons/people-group?f=classic&s=solid](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fpeople-group%3Ff%3Dclassic%26s%3Dsolid&data=05%7C01%7Cmhk33%40cornell.edu%7Ca83e0283a09e4cfebef608dbef685840%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638367003675118147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Oj3Fr5284rDo2J%2BOWeGJEvOGdSoh3utI1daBdtLPEb0%3D&reserved=0)

**Comment by JesiBuell79** [comment]
Sarah finished this up!
