### ISSUE TITLE
Workshops/classes filter for Mann events

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1219]
At the 10/4/23 stakeholders meeting, Tobi asked if we can bring back the workshops/classes filter on the Mann site.

This is an old email thread from when we took down a link to it:

From: Tobi Hines <[eeh53@cornell.edu](mailto:eeh53@cornell.edu)>
Date: Tuesday, February 28, 2023 at 1:46 PM
To: Melissa Wallace <[mhk33@cornell.edu](mailto:mhk33@cornell.edu)>
Subject: RE: Workshops page

Thanks, Melissa! We did have an events feed from Localist that was filtered to workshops and classes, but the feed broke and Manolo was never able to fix it. It probably makes sense for me to just delete the page at this point. We have an Events calendar feed that brings in everything, so it’s just getting rid of one view, which isn’t that big a deal.
 
I appreciate the reminder to deal with this!
Tobi
 
From: Melissa Wallace <[mhk33@cornell.edu](mailto:mhk33@cornell.edu)> 
Sent: Thursday, February 16, 2023 4:34 PM
To: Tobi Hines <[eeh53@cornell.edu](mailto:eeh53@cornell.edu)>
Subject: Workshops page
 
Hi Tobi,
 
There is a link to “Workshops & Classes” here but it gets a 404: https://mann.library.cornell.edu/news-events
 
https://mann.library.cornell.edu/workshops-classes
 
Is there a new page for this?
 
Thanks!
Melissa

**Comment by mhk33** [comment]
@sarah-cul That sounds like a good fix to me! Thank you for looking into this.

**Comment by sarah-cul** [comment]
Asked Stakeholder to confirm, waiting for approval. This is the localist code that fetches the event that are class/workshop

`<div id="localist-widget-55313087" class="localist-widget"></div><script defer type="text/javascript"
src="https://events.cornell.edu/widget/view?schools=cornell&types=5915%2C4228&days=90&num=50&match=all&container=localist-widget-55313087&style=none"></script>`

**Comment by sarah-cul** [comment]
confirmed with stakeholder, and also added back the "See all workshops and classes >> " link on the front page
