### ISSUE TITLE
Security update for WP SAML Auth plugin

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#1224]
After a low-risk vulnerability was recently discovered in the WP SAML Auth plugin, Pantheon released version 2.1.4 with a patch. We recommend updating the plugin as soon as possible.

Vulnerability description:
When WordPress authentication is turned off, POST requests to the WP login URL still provide an authentication cookie. A valid WordPress username and password are required in order to receive the authentication cookie.

**Comment by jgreidy** [comment]
Building new upstream. Including other plugin updates compatible with current WordPress version.

**Comment by sarah-cul** [comment]
[v2.4.2 of the upstream](https://github.com/cul-it/ci-jenkins-pantheon-wordpress/blob/master/CHANGELOG.md), we updated this plugin "pantheon-systems/wp-saml-auth": "2.1.4"
