### ISSUE TITLE
Change Twitter to X

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1228]
Per Communications, change any occurrences of the Twitter logo with the new X logo.

https://about.twitter.com/en/who-we-are/brand-toolkit

Font Awesome also has a version, if we are using font icons: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

**Comment by mhk33** [comment]
@sarah-cul Did you make this change? I'm checking the units for who might use Twitter and see that the logo has already been updated on many sites. If so, thank you!

**Comment by mhk33** [comment]
Looking at the source it looks like they may be tied to a plugin, so perhaps the plugin got the update.

**Comment by sarah-cul** [comment]
I can't take credit for that, but I think you may be right it could be a plugin update. we updated the simple social icons plugin on 2024-02-08

**Comment by mhk33** [comment]
Excellent!
