### ISSUE TITLE
Update Borrow Direct to BorrowDirect

### ISSUE THREAD

**Issue by JesiBuell79** [cul-it/uls#1229]
check uls for this branding

- [x] Africana
- [x] Annex
- [x] Asia
- [x] Engineering
- [x] Fine Arts
- [x] Hotel
- [x] Catherwood
- [x] Law - left private posts and Keywords newsletters as is
- [x] Johnson
- [x] Mann - left news posts as is
- [x] Mathematics
- [x] Music
- [x] Olin-Uris
- [x] PSL
- [x] Rare
- [x] Vet

**Comment by mhk33** [comment]
I checked all the units listed above and changed "Borrow Direct" to "BorrowDirect" where applicable. I did not change temporal communications such as news posts and newsletters, nor did a change private (not published) posts.
