### ISSUE TITLE
Staff profiles: "Could not determine remote post ID" when distributing post

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1232]
From Xan: "I'm trying to add new ones and when i try to distribute them i get an "Could not determine remote post ID." error"

https://olinuris.library.cornell.edu/staff/alex-palacios

**Comment by sarah-cul** [comment]
I added Emma Sosebee & Alex Palacios manually. 

I will investigate this staff profile issue in the next unit site sprint. 
Closing this issue and documented it in https://github.com/cul-it/uls/issues/1195
