### ISSUE TITLE
Can't update Easy Notification Bar

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1235]
Chris Dunham requested that the Vet Library banner get updated, but when we went to Plugins > Easy Notification Bar > Settings, we were taken to an update page under Appearance > Customize with a mesage regarding widgets.
<img width="395" alt="Screenshot 2024-02-26 at 5 02 41 PM" src="https://github.com/cul-it/uls/assets/1869412/b6f9d444-2699-450d-8038-a50d4467655c">

The email from Chris:

From: Chris Dunham <[cd332@cornell.edu](mailto:cd332@cornell.edu)>
Date: Monday, February 26, 2024 at 2:36 PM
To: Cornell University Library IT Developer Team <[cul-dev@cornell.edu](mailto:cul-dev@cornell.edu)>
Cc: Tobi Hines <[eeh53@cornell.edu](mailto:eeh53@cornell.edu)>, Lauren Mabry <[lem259@cornell.edu](mailto:lem259@cornell.edu)>
Subject: Update to Vet Library web page

 
Good afternoon IT Developer Team, 
I'm writing to ask if you could make a small change to the banner on our website re: the card access status? You kindly created the banner below for us last fall; could you add a second line that states "Non-vet patrons who wish to use the library must email [vetcirc-mailbox@cornell.edu](mailto:vetcirc-mailbox@cornell.edu) at least 24 hours in advance to schedule an appointment"
 
 
Thank you so much,
Chris

**Comment by mhk33** [comment]
@sarah-cul and I found posts saying it could be a plugin conflict. I last added an Easy Notification Bar to the Law site on 2/1, so it was working then. Sarah say an ExactMetrics error and tried disabling that one on a Vet test site and then the Easy Notification Bar settings worked. I confirmed that worked on a Law multidev as well.

**Comment by sarah-cul** [comment]
Updating Easy Notification Bar & Google ExactMetrics plugins resolved the issue. We will update all the unit sites with the next plugin update, but for right now the Vet site is updated so we can make the requested message change.
