### ISSUE TITLE
Mann hours displaying as 'closed' when library is open

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1257]
### Description
Leah Dodd reported that the Mann header said the library was closed when it should have showed as open. More details and comments here: https://cornell.libanswers.com/admin/ticket?qid=14687009

### Expected behavior
Open/closed status should accurately reflect the current hours.

**Comment by mhk33** [comment]
Possible related issue: https://github.com/cul-it/uls/issues/1182

Tobi reports that it is working for her now; TBD if it works for Leah (see LibAnswers ticket for status).

**Comment by mhk33** [comment]
Another report from Tobi today:

> Good morning! Remember that weird thing last week with the Mann Library hours? Now I'm seeing it on the Catherwood site: https://catherwood.library.cornell.edu/
> 
> If you click to the full hours page, it's correct. And if I navigate to another webpage, the hours look correct. But on the homepage, the library is showing as "closed"
> 
> Same thing at Math! https://mathematics.library.cornell.edu/

I am seeing it Closed on the home pages of both, and also closed on many other sub pages for both. On my phone it was Open on the Full Hours page.

**Comment by mhk33** [comment]
A report today from Marc, too. Something seems to be worse lately, for sure.

> Good evening :)
The [Cornell Tech library services](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftech.library.cornell.edu%2F&data=05%7C02%7Cmhk33%40cornell.edu%7C73387ba91a4d4391edbb08dceef0c40d%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638647965063493404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=H0vuXZ1%2B7oz3BsB8aZxZ%2BhvKfinLiw%2FQOidQVk7rJOk%3D&reserved=0) website and [Nestlé library website](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhotel.library.cornell.edu%2F&data=05%7C02%7Cmhk33%40cornell.edu%7C73387ba91a4d4391edbb08dceef0c40d%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638647965063512956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=PouI4ByoA8us4m3LhvdK1gHFE8Vo%2BrDILUQvsQibue4%3D&reserved=0) seem to keep showing incorrect hours on the front page. It seemingly randomly show the correct hours (and always shows the correct hours when you click to show full hours), and then periodically show an older cached version. (Nestle’s is especially confusing, since don’t believe I’ve ever made the closing time for October 17th 3:45pm??) I don’t think that this has happened with the Management Library website (or at least not in recent memory).
I get emails from my supervisors and administration periodically when they notice, because it looks like I’ve entered the hours incorrectly.
Is there anything I can do on my end to keep this from happening? Or is there any permanent fix that’s available?
Thank you,
Marc

**Comment by sarah-cul** [comment]
since the pantheon advanced page cache plugin was adjusted, this seems to be resolved.
