### ISSUE TITLE
Math Library new books feed is not correct

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#1258]
### Description

From Henrik:

"The link to “new books” on the main math library website is not working. The new book feed should cover a specific call number range of QA that excludes the computer science ranges QA 75+76 and QA 155.7 and QA 267-268."
https://mathematics.library.cornell.edu/new-books/

### Expected behavior

Feed should exclude the range indicated above.

**Comment by sarah-cul** [comment]
After some back and forth with the Henrik, it was agreed to change the New Books link to be a direct link to the catalog with an advanced search query. This allowed me to un-publish the New Books page and deactivate 4 plugins for WP RSS Aggregator

**Comment by mhk33** [comment]
That turned out to be a great solution!
