### ISSUE TITLE
Add Custom Styles to the hours plugin

### ISSUE THREAD

**Issue by tap87** [cul-it/uls#141]
The plugin is working pretty well for all the hours and libraries. It will need some custom html and css to improve the UI.

**Comment by manolobevia** [comment]
Can you throw me some markup for [libcal_status_now] and [libcal_hours_today] so I can style? Like:
`<span class="libcal-status-now">[libcal_status_now]</span>`
`<span class="libcal-hours-today"> [libcal_hours_today] </span>`

The shortcode just render the value of [libcal_status_now] and [libcal_hours_today]

**Comment by tap87** [comment]
@manolobevia Yes, I can put the markup in the plugin. I wasn't sure if you would put it in the website templates or in the plugin. Also, the markup for the weekly and monthly widget comes from LibCal which can't be modified but we can add css to it. All of the front end code is here: https://github.com/cul-it/wp-libcal-hours/tree/dev/public

**Comment by manolobevia** [comment]
Sorry, you don't need to add the markup in the plugin. I am not thinking clearly today. I can add the markup on the template.

**Comment by tap87** [comment]
It can go in either the plugin or the template, which ever you think will be easier to maintain and more flexible.

**Comment by tap87** [comment]
Manolo can add styles to the template pages, closing this one
