### ISSUE TITLE
ULS UNITS - Redesign headers for home and interior pages.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#144]
- The user nav ( Cornell Library hours, make a gift, etc) and the main nav needs to be combined together as one menu, the way it is right now is not ideal. Base on the samples attached,  I would like to combine what is related to the main library and avoid the hacky merge of two menus for responsive devices.

- Search on homepage has been requested for stakeholders, and I have created a simple search functionality in comparison to the one we have right now. Also, the current search required a lot of efforts to make it accessible.

- We see these features: spaces, equipment, and course reserve useful tools for patrons. I would like to make it prominent on the header sections.

**Comment by manolobevia** [comment]
![home page - added hero image](https://user-images.githubusercontent.com/8395482/52659871-65584300-2ecc-11e9-8061-49e07ac9de89.png)
![home page - current homepage](https://user-images.githubusercontent.com/8395482/52659872-65584300-2ecc-11e9-9b30-79895ac531d2.png)
![home page - version 1](https://user-images.githubusercontent.com/8395482/52659873-65f0d980-2ecc-11e9-8cd5-039f86cc9376.png)
![home page - version 2](https://user-images.githubusercontent.com/8395482/52659875-65f0d980-2ecc-11e9-8bbd-69eebd45a1fa.png)
![interior page - added hero image](https://user-images.githubusercontent.com/8395482/52659877-65f0d980-2ecc-11e9-9210-bbe74bd08260.png)
![interior page - version 1](https://user-images.githubusercontent.com/8395482/52659878-65f0d980-2ecc-11e9-8f9c-a1f3be977178.png)

**Comment by manolobevia** [comment]
Current homepage: 
![home page - current homepage](https://user-images.githubusercontent.com/8395482/52659913-7f922100-2ecc-11e9-93a9-c176e3dfb5c1.png)

Proposed homepage: 2 versions
![home page - version 1](https://user-images.githubusercontent.com/8395482/52659967-9f294980-2ecc-11e9-8a9d-b2fdec4ce1e6.png)
![home page - version 2](https://user-images.githubusercontent.com/8395482/52659969-9f294980-2ecc-11e9-83ce-efd313161437.png)

Proposed interior page:
![interior page - version 1](https://user-images.githubusercontent.com/8395482/52659986-a7818480-2ecc-11e9-9466-65f470ddf1d0.png)

**Comment by manolobevia** [comment]
@mhk33 Let me know what you think when you can. Thanks.

**Comment by mhk33** [comment]
@manolobevia i like this one:
https://user-images.githubusercontent.com/8395482/52659969-9f294980-2ecc-11e9-83ce-efd313161437.png

What would happen when clicking the search icon on the home page?

I wonder if we can change "Cornell Library Hours" to just "Hours" in the top bar. So it would be:
ALL LIBRARIES | Hours | Ask a Librarian

**Comment by manolobevia** [comment]
Re: What would happen when clicking the search icon on the home page? Good question :)? 
I want to avoid overlays or an overlay including the search box sliding from the top to avoid accessibility issues. Maybe something like cornell.edu has.

About the hours, I was thinking the same thing. Let's try and then test.

Thanks.
