### ISSUE TITLE
Search button hiding main navigation menu

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#150]
Whenever you open the search box using the icon in the upper right, close it using the close link, and then try to open it again, it toggles the main navigation below the banner image instead of the search box. This only happens when the window is tablet-sized.

**Comment by manolobevia** [comment]
I have opened the search box.
<img width="336" alt="screen shot 2019-02-14 at 9 57 09 pm" src="https://user-images.githubusercontent.com/8395482/52831716-9fc80880-30a3-11e9-9bd7-855abc0b5355.png">
then I have closed ti using the `close`
<img width="324" alt="screen shot 2019-02-14 at 9 57 14 pm" src="https://user-images.githubusercontent.com/8395482/52831735-b5d5c900-30a3-11e9-8b43-ce35531228b5.png">
After than I don't see the main nav. I have used Chrome and Firefox. Can you povide info about the browser, its version, os? I can't replicate this issue.

**Comment by kevinkidwell** [comment]
I'm doing this with Chrome Version 71.0.3578.98. It happens when my browser window is between 798px and 1200px wide. Here are a couple of screenshots showing what I'm seeing:

This is with the Search box open for the first time:
![screen shot 2019-02-15 at 8 59 34 am](https://user-images.githubusercontent.com/29164102/52861314-18f54900-3100-11e9-9eac-ad0c2b32dc5a.png)

This is after I've closed the search box and then clicked the search icon again:
![screen shot 2019-02-15 at 8 59 47 am](https://user-images.githubusercontent.com/29164102/52861315-18f54900-3100-11e9-9db1-d38b9958593e.png)

**Comment by manolobevia** [comment]
The issue was, behind the search icon there was the menu icon too.

**Comment by ajs17** [comment]
Kevin will review and close.

**Comment by kevinkidwell** [comment]
Looks good!
