### ISSUE TITLE
ULS UNITS - Add consultation capabilities to units sites

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#153]
This a feature 2 libraries have already requested. They want to follow MANN model for having consultations.

**Comment by tap87** [comment]
Mann has a separate content type for staff profiles. Nick used the My Scheduler Widget from Libcal to embed the widget.
For this to work, we will need to have staff profile content type in wordpress with a custom field for LibCal UID field to render the widget.
Here is the PR for reference from Mann repo(https://github.com/cul-it/mann-wagon/pull/574)

**Comment by manolobevia** [comment]
I am planning to do the same thing. I would like to have a content type for staff profiles. Then put for each unit library a [display](https://vet.library.cornell.edu/staff-profile-2/) with all the staff. Also, have a staff page on the main site if useful for users. I would like if somebody tells me what other custom fields I will need for a staff profile, besides first name, last name, email, etc... Do we include a small bio, staff interest, etc?

**Comment by tap87** [comment]
@manolobevia Before I go too far down the road with the plugin, I spoke with Darcy and she mentioned that there has been talk of changing consultation with individual librarians. Instead, they are thinking of providing consultation services in areas of expertise and then any available librarian can accept.

**Comment by manolobevia** [comment]
This is a duplication of #164

**Comment by manolobevia** [comment]
Metadata:
