### ISSUE TITLE
PSL Minor Style Adjustments

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#16]
Looking at the PSL dev site on my local machine, there a few things that I would like to adjust so I'm going to make a list of them here.

**Nav menu (middle of page)**
- Styling with the right border
- All items with sub-menus should have arrow
- Sub-sub-menus are being outlined and should not be/should be indented

**Footer**
- Add a bit more space between nav menu and text below it

**Content Area**
- Define colors for buttons to match more with theme colors

**Comment by manolobevia** [comment]
@kevinkidwell PSL theme is not ready. I still need to do a lot of visual changes.
