### ISSUE TITLE
ULS UNITS - Space availability and reservation

### ISSUE THREAD

**Issue by tahirpoduska** [cul-it/uls#173]

**Comment by tap87** [comment]
Mary Beth's email regarding spaces:
From: Mary Beth Martini-Lyons
Sent: Friday, February 1, 2019 10:25 AM
To: Tahir Poduska; Manuel Bevia Perez
Cc: Adam J. Smith
Subject: RE: CUL Equipment and Spaces booking and display.
 
All,
 
In your research re: spaces could you also please take a look at the Spacefinder tool developed by Cambridge University?  Harvard’s Library has recently implemented this tool on their newly redesigned website.  This app has also caught the eye of AULS and members of the CLO Leadership team, so at the very least, a review of the product, and looking at it from a feasibility angle for our needs would be best.
 
Cambridge seems to have developed it as a very wide ranging tool that also identifies spaces in the community (bars, coffee shops, etc…) but Harvard seems to have it pretty narrowed down to just spaces in their libraries, which is how I would imagine we would like to use it.  It is not limited to reservable space, but gives info on all types of spaces that exist within the libraries. 
 
Harvard:  https://library.harvard.edu/services-tools/find-space
Cambridge: https://spacefinder.lib.cam.ac.uk/#/map
More info about the app at Cambridge:  http://www.lib.cam.ac.uk/research/futurelib-innovation-programme/spacefinder
https://futurelib.files.wordpress.com/2016/06/the-spacefinder-project-final.pdf
 
Thanks,
mb

**Comment by sew268** [comment]
I've als spoken with the folks from Harvard about this and they are willing to share their modified code with us if we are interested.

**Comment by ajs17** [comment]
Nick may be able to help with any potential pitfalls using the SpringShare API

**Comment by JesiBuell79** [comment]
Closing
