### ISSUE TITLE
Make all HTTP URLs get rewritten / redirected to HTTPS for custom upstream and child sites.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#18]
@gdelisle the site that needs immediate attention is Vet library `https://vet.library.cornell.edu/`.
We tried a few WP plugins but no luck redirecting HTTP to HTTPS URLS. I am sure we can do this via Pantheon.

**Comment by manolobevia** [comment]
I would prefer if you take care of it.

**Comment by jgreidy** [comment]
Hi. @gdelisle I can take care of this.

**Comment by jgreidy** [comment]
I added code into wp-config.php in the custom upstream https://github.com/cul-it/uls that will redirect http:// requests to https:// . I pulled this update into the pantheon uls-psl site and tested there.

There is a configuration file that has to be set up in the pantheon site repo for the official live domain name. It is 'wp-config-cul-uls.php', and here is an example:

<?php
define('ULS_SITE_DOMAIN_NAME', 'physicalsciences.library.cornell.edu');

**Comment by mhk33** [comment]
Jim put the force https on the Vet dev site. I pulled down these changes to my local and have trouble loading the site with the NGINX https URL (and http now forces to https). I can load it with the Edge URL:  https://vetlibrarycornelledu.lndo.site, though in Chrome I have to click the button to "proceed anyway" as site is unsafe.
