### ISSUE TITLE
Closed Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#181]
I'm getting this error in the GitHub version of wp-libcal-hours:

Closed Warning: count(): Parameter must be an array or an object that implements Countable in /srv/bindings/a867b45a405b47ceadf898e5747e2e95/code/web/wp-content/plugins/wp-libcal-hours/public/class-wp-libcal-hours-public.php on line 252 - Full Hours /

https://github.com/cul-it/wp-libcal-hours

**Comment by tap87** [comment]
@jgreidy Can you give some more details of how you setup the plugin and how you are using it? There might be a big here but I also want to check that you have configured the app in the wordpress admin settings and are using the shortcode properly.

**Comment by jgreidy** [comment]
Here is the url https://dev-wp-ci-library-cornell-edu.pantheonsite.io/
You should be able to create an account with the Sign In button under Use one-click authentication:
I will make you admin after that.
This site is a test site with the custom upstream. No files/data, just the code is there so far.

**Comment by tap87** [comment]
THanks @jgreidy Just created an account. Also, which repo is the code in for this site? I wanted to see how the hours code is implemented.

**Comment by tap87** [comment]
@jgreidy I was able to reproduce the error. I pushed a commit to dev branch, to throw a user friendly error if the library to display the hours for isn't selected in wp admin settings.
