### ISSUE TITLE
1 - Forms

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#182]
Priority: 1
Feature: Forms
Research: https://github.com/cul-it/clo-content-group/issues/13

This epic will contain all issues pertaining to forms for accessibility. See https://github.com/cul-it/clo-content-group/issues/12 for full feature list.

**Comment by kevinkidwell** [comment]
Question on forms to look into: can qualtrics send emails from multiple senders (for LibAnswers reasons) or how do LibAnswers forms hold up for accessibility compliance?

**Comment by kevinkidwell** [comment]
Here is the wiki page for the forms creation guidelines: https://github.com/cul-it/uls/wiki/Forms-Creation-Guide

It includes a number of screenshots with the various settings and styles that should be used, along with how to organize the content into blocks and where button text should be changed.

**Comment by manolobevia** [comment]
@kevinkidwell great guide.  I'll create a sample form and add it to CULU. I would like to see how responsive it is. I think the forms are. Correct?

**Comment by kevinkidwell** [comment]
@manolobevia They should be but we don't have to display any of them of on our webpages. For these forms, we will just be linking out to Qualtrics on all unit sites. This keeps all of the accessibility requirements on their end instead of ours.

**Comment by kevinkidwell** [comment]
@MeredithLevy It looks like the list of forms is missing one from Fine Arts, because it is just a Word doc instead of being an online form. We need to create the Employment Application from https://finearts.library.cornell.edu/aboutus/jobs as a Qualtrics form because they want to move it digital.
