### ISSUE TITLE
VET - add form for after-hours access for Cornell students, faculty and staff

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#19]
This page links to a form on the old Vet library website: 
https://vet.library.cornell.edu/after-hours-access/ 

Here's the form: 
https://www2.vet.cornell.edu/about-us/flower-sprecher-veterinary-library/about-us-and-hours/veterinary-library-access-authorization-form-cornell-students-faculty-and-staff 

From Erin: 

For the Vet Library Authorization form page, we will need a new one with a form that sends a message. All of the fields except for Title and Class of should be required. Can you help us create that? These requests go to Chris Dunham, who manages access.

**Comment by manolobevia** [comment]
I might be using https://wordpress.org/plugins/contact-form-7/ (free version) for creating the forms. It has a lot of documentation, and I am not familiar rith now. I recommend in the interim to email to Chris Dunham. After launch, we should talk about what is the best solution for adding forms to ULS site.

Another great plugin (paid) is https://wpforms.com/. I would prefer not to break the user experience by taking them to google forms, qualtrics, or another external site.

**Comment by manolobevia** [comment]
@sew268 Vet didn't follow up about that particular form (gone from the old site). Could you contact  VET library and see if they still need it? If yes, it should be a Qualtrics form. Thanks.

**Comment by sew268** [comment]
@manolobevia sure thing!  I'll do that today.

**Comment by sew268** [comment]
@manolobevia any chance the form fields still exist somewhere?

**Comment by manolobevia** [comment]
Probably gone. I am going to close this issue since Vet is not requesting it. We can always reopen the issue in case they need a form.
