### ISSUE TITLE
Main CUL

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#193]
Main CUL Accessibility Remediation

Number of issues: 3
Current score: 98.2%
PDF errors: 1

**Comment by mhk33** [comment]
This is in good shape for now. I get email updates when SiteImprove re-crawls the site and then I clear any new open issues (there are usually just a couple of them).

I don't plan to do anything major with this until after we hear back from CIT with the report from their manual accessibility check.

**Comment by mhk33** [comment]
Main site accessibility is done except for video captions and a PDF. There are separate issues for those (#232 and #233).
