### ISSUE TITLE
Alumni

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#194]
Alumni Accessibility Remediation

Number of issues: 27
Current score: 64.1%
PDF errors: 0

**Comment by kevinkidwell** [comment]
Making a note here:

I had to edit the core node.module to get rid of role="article" to fix redundant labels. This will need to be an override but I don't know how to do them yet.

There is an issue with SiteImprove picking up a form field that isn't showing up for me on the site or in the edit screen. If we can get #182 figured out, I think it would be better to move this to Qualtrics and that would remove these errors.

**Comment by kevinkidwell** [comment]
@mhk33 Do we worry about the HTML/CSS validation portions with these sites? If not, and knowing about the two issues above that need done, I'd say Alumni is ready for the manual check.

**Comment by mhk33** [comment]
@kevinkidwell I wasn't worrying about validation before, but it came up on the manual check for the main site so I think it's something we need to pay attention to. That said, I think it would be okay to ask for the manual check before addressing validation, just to see what they report back.

**Comment by manolobevia** [comment]
@kevinkidwell we shouldn't change Drupal core files. Please ask @jgreidy if he can create a theme function instead.

**Comment by kevinkidwell** [comment]
CIT manual check results with a few things to fix: https://docs.google.com/spreadsheets/d/1hcWOTNzgP4QywQlBOcBiOmn1pKL9Bmogu5Vchui2MVg/edit#gid=776733708

**Comment by kevinkidwell** [comment]
I have updated Alumni based on the feedback from the CIT manual check. The only things that are left are some of the HTML validation things, which I've spoken with @mhk33 about and will see what the answers are with those regarding the main site and then figure out what to do with them here.

**Comment by manolobevia** [comment]
@mhk33 let me know what is the decision with HTML and CSS validation. Thanks.
