### ISSUE TITLE
ULS UNITS -Track search for Hotel in GA.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#206]

**Comment by mhk33** [comment]
@manolobevia I did a couple of test searches on Hotel and saw them show up for today's date in GA under Search Terms. So I think this should be all set.

**Comment by mhk33** [comment]
Note that it is tracking search terms for the website only, not the catalog. The catalog terms should be in GA and Matomo for the catalog.

**Comment by manolobevia** [comment]
It is tracking the terms sent to the catalog and internal search. There are 2 query parameters we are targeting 
![Screen Shot 2019-04-08 at 3 15 24 PM](https://user-images.githubusercontent.com/8395482/55750481-619af580-5a11-11e9-8b76-4946a1abd63a.png)

**Comment by mhk33** [comment]
I don't think the catalog search terms will show up in the Hotel or PSL GA project, though, since they are sent to the newcatalog domain. I did test catalog searches in Hotel and the terms don't show up. Neither do the url paths with q?= since those are newcatalog.

But we should be able to get those terms in the catalog GA project. We can also see if we can get the referrer path from hotel (or PSL).

**Comment by mhk33** [comment]
Yes, you can see the search term from Hotel in the catalog GA project, and you can add the full referrer as a second dimension to see where the search came from.
<img width="719" alt="Screen Shot 2019-04-08 at 3 27 37 PM" src="https://user-images.githubusercontent.com/1869412/55751142-fce09a80-5a12-11e9-8d25-5f12d4757ed8.png">

**Comment by manolobevia** [comment]
I don't know why I was thinking we can capture catalogue search on the unit site GA project. What I don't see is search terms. I did an internal unit search (sample /?s=web) but GA is not displaying the search terms.

**Comment by mhk33** [comment]
I'm not sure if this link will work, but I can see search terms for today, April 8, on Hotel:
https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a8097093w190758965p186843916/_u.date00=20190408&_u.date01=20190408/

**Comment by mhk33** [comment]
I had to do searches today, as there didn't seem to be searches prior to today and after you configured it. Anyway, it seems to be working for me on Hotel and PSL.
