### ISSUE TITLE
ULS UNITS - Unable to add plugins to FIne Arts instance.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#238]

**Comment by manolobevia** [comment]
Once you go to the admin panel and click on plugins. The display for the plugins doesn't show the button for adding new plugins.

Here is a sample of the plugin display for Fine Arts

![Screen Shot 2019-05-06 at 11 47 19 AM](https://user-images.githubusercontent.com/8395482/57237846-1404af00-6ff6-11e9-858f-96d900262232.png)

And this is a sample of culu

![Screen Shot 2019-05-06 at 11 48 47 AM](https://user-images.githubusercontent.com/8395482/57237850-15ce7280-6ff6-11e9-95fc-6de0f8be946b.png)

**Comment by manolobevia** [comment]
It is sound like a plugin is causing this `https://wordpress.org/support/topic/missing-my-add-new-plugin-button/`. I am deactivating all the plugins.

**Comment by manolobevia** [comment]
I did that and I get a page with the following message: 

`Fatal error: Uncaught Error: Class 'Kirki' not found in /app/web/wp-content/themes/culu/functions.php on line 182 Error: Class 'Kirki' not found in /app/web/wp-content/themes/culu/functions.php on line 182 Call Stack: 0.0005 434944 1. {main}() /app/web/wp/wp-admin/plugins.php:0 0.0005 435616 2. require_once('/app/web/wp/wp-admin/admin.php') /app/web/wp/wp-admin/plugins.php:10 0.0006 436096 3. require_once('/app/web/wp/wp-load.php') /app/web/wp/wp-admin/admin.php:34 0.0025 442688 4. require_once('/app/web/wp-config.php') /app/web/wp/wp-load.php:42 0.0032 518184 5. require_once('/app/web/wp/wp-settings.php') /app/web/wp-config.php:254 0.0315 2699648 6. include('/app/web/wp-content/themes/culu/functions.php') /app/web/wp/wp-settings.php:479`

**Comment by manolobevia** [comment]
Trying to see if with Lando WP CLI I am able to activate the plugins again. I can't `wp plugin activate --all'. I just `Lando pull` so now I have all the plugins back. After deactivating kirki, I get a white page. It must be this plugin causing not having the `'add new plugin` button.

**Comment by jgreidy** [comment]
kirki is one of the plugins required for the CULU theme. Somehow, the theme allows you to make it the default theme without checking that the plugins it requires are enabled.

**Comment by manolobevia** [comment]
I disabled all the plugins except Kirki, to see if one of them was causing not displaying the `add new plugin` button, but the button doesn't display. If I disable Kirki, I get the error page, so I won't able to check if kirki is the plugin causing not displaying `add new plugin` btn.

**Comment by jgreidy** [comment]
To test this out, I added a new multidev site 'addplug' here: 
https://dashboard.pantheon.io/sites/85c58cc2-e24d-4b1f-b6b6-c34ae886e068#addplug
I put the site in SFTP mode.
I logged in to the site as and admin.
I set the theme to the default: Twenty Nineteen
I deactivated all plugins.
Still no add plugin button.

**Comment by jgreidy** [comment]
Fixed with 8ea49655b5bd35d000e2cfd9e6397113fb7bcd08
See https://core.trac.wordpress.org/ticket/39802
removed define( 'DISALLOW_FILE_MODS', true ); from wp-config.php
