### ISSUE TITLE
ULS UNITS - Increase maximum upload file size or get unlimited

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#252]
After exporting current sites (ex: VET) and then importing to a CULU instance, "All-in-One WP migration" plugin generates a file in some cases bigger than 100 megabytes which I can't import into the CULU instance.
Message below:
"Your file exceeds the maximum upload size for this site: 100 MB
How-to: Increase maximum upload file size or Get unlimited?"

Please increase the size.

**Comment by jgreidy** [comment]
I added these limits to wp-config.php:

@ini_set( 'upload_max_size' , '100M');
@ini_set( 'post_max_size', '20M');
@ini_set( 'memory_limit', '256M');

**Comment by manolobevia** [comment]
Thanks.

**Comment by jgreidy** [comment]
Should have closed Jun 27. Fixed.
