### ISSUE TITLE
ULS UNITS - Update the custom stream of CULU to WP core 5.2.1

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#253]
Can you please update the custom stream to WP 5.2.1. (CULU is using 5.2.1) The new version of `elementor` plugin doesn’t work well with the WP 5.2 (I think). I have a local instance of the VET using the custom stream which I updated to 5.2.1, which the layout work well, but the layout breaks on DEV.   I can’t not update DEV to 5.2.1 since first the upstream needs to be changed. I tried everything to fix the layout on the DEV instance of VET using CULU but no luck. The only think I need to test is if the new core update fix the issue. Also there are a bunch of errors on dev `https://dashboard.pantheon.io/sites/7b992a7b-81a2-42b6-b4cf-8d915f927164#dev/status` that could be reason.

**Comment by manolobevia** [comment]
Sample of local instance layout:

![Screen Shot 2019-05-28 at 10 34 16 AM](https://user-images.githubusercontent.com/8395482/58487468-a00d8080-8135-11e9-8410-72f26a81527e.png)

Sample of dev instance

![Screen Shot 2019-05-28 at 10 41 32 AM](https://user-images.githubusercontent.com/8395482/58487489-a7348e80-8135-11e9-8abd-8cb3ffd19fcc.png)

**Comment by jgreidy** [comment]
I made a new upstream with WP 5.2.1 and some plugin updates. The update requires composer install.
