### ISSUE TITLE
Olin-Uris accessibility: add aria-labels to equipment matrix

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#266]
The "Pick up now" and "Reserve" buttons on this page use the same link text, but go to different destinations:
https://olinuris.library.cornell.edu/services/loans/equipment

They need to be differentiated either by having unique link text, or adding the aria-label attribute to each with a unique label. For example:

`<a href="/services/loans/equipment/597/pick-up" class="btn btn-primary equipment-pickup active" role="button" aria-label="Pick up Audio/Voice Recorder">Pick up now</a>`

`<a href="https://spaces.library.cornell.edu/equipment?lid=94&amp;gid=662" class="btn btn-primary equipment-pickup active" role="button" aria-label="Reserve Audio/Voice Recorder">Reserve</a>`

**Comment by jgreidy** [comment]
Added the aria-labels to equipment reserve and pick up now buttons
