### ISSUE TITLE
ULS UNITS - Refactor hours component to include virtual spaces.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#275]
~~Engineering~~ and PSL won't have library hours. Provide UI for including specific messages to be displayed like: 
- ~~`Study Space open 24 hours` ( Engineering )~~
- `24/7 study space and computing only` ( PSL )

**Comment by manolobevia** [comment]
Text to be displayed for PSL: `Study Space open 24 hours`

Engineering library hours need to be added to Libcal.

**Comment by mhk33** [comment]
May be worth confirming with Engineering, but they are also a virtual space and display this for their hours on the current main site: "24/7 study space and computing only."

**Comment by manolobevia** [comment]
#289 takes care of this issue.
