### ISSUE TITLE
CUL - Create theme

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#28]

**Comment by mhk33** [comment]
For accessibility, can the CUL logo be applied as a background image in CSS? It comes up in accessibility review as it is an image with text.

**Comment by manolobevia** [comment]
So the signage should be treated as an image and the logotype as text. Why is it wrong not to have an svg? We can make accessible.

**Comment by mhk33** [comment]
Yes that would be fine. I've also used an SVG as a background in CSS. Looks like cornell.edu uses the insignia as a background image.
