### ISSUE TITLE
ULS UNIT Management - Make sure WP search will look through ACF hidden field

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#280]
Based on our meeting with Rachel on 6/17/19 we need to have the option for them to add additional terms that can be searched on each database/topic/etc. This is for common misspellings, name changes, and the like.

**Comment by kevinkidwell** [comment]
@manolobevia I found a way to do this this morning. We can use this plugin https://wordpress.org/plugins/acf-better-search/ to select what ACF fields should be added into the default WP search without any additional coding on our part. I added it to the Management dev instance, created an example database, and searched for one of the hidden search terms. This plugin worked great and pulled up the database on the first try.

Is this a plugin that we should add to the CULU theme and then can be used across units?

**Comment by manolobevia** [comment]
@kevinkidwell So this plugin uses the internal search template to display content related keywords. GREAT!!!!!!!  I wonder if we can create our own search template and display 2 sections. One for databases and the other with FAQs related to the specific keyword.

I will add this plugin to CULU, custom-post-type-ui, and I need to add some changes to CULU too. I will push all this for our next deployment.
