### ISSUE TITLE
ULS UNITS HOTEL - Fix Hotel Horizons link

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#281]
From Melissa:

Hi Ken,
I understand there is an issue with access to the Hotel Horizons database. Manolo and I looked into it a little bit and it seems there is a redirect from the URL for Hotel Horizons back to the new Hotel website Databases page. From Manolo:

I was able to check the original link `https://web.archive.org/web/20180618133939/https://sha.cornell.edu/about/facilities/nestle-library/databases/list.html` which is `https://sha.cornell.edu/about/facilities/nestle-library/databases/hotel-horizons/` and redirects you to `https://hotel.library.cornell.edu/research-databases/` …

I don’t know what happened with the Hotel Horizons database after the Hotel Library redesign. Manolo and Kevin are cc’d, in case either of them recall. Is this one of the databases that was hosted by SHA? Assuming it is still available, can SHA IT remove the redirect that sends the user to the new Hotel Library databases page?

Best,

Melissa

From: <bounce-123676826-83995296@list.cornell.edu> on behalf of Ken Bolton <ktb4@cornell.edu>
Reply-To: Ken Bolton <ktb4@cornell.edu>
Date: Wednesday, June 12, 2019 at 9:14 AM
To: LIBIT-L <LIBIT-L@list.cornell.edu>
Subject: Hotel Horizons link not working

 

Hello libit,

 
The link to Hotel Horizons is not working. The resolver link seems to be redirecting back to the Research Databases page on the Nestle site.

https://newcatalog.library.cornell.edu/catalog/6348936

Thank you,
Ken

Ken Bolton
Librarian
Nestlé Library | School of Hotel Administration
Cornell SC Johnson College of Business
607 255-4103

**Comment by kevinkidwell** [comment]
I just received the code from SHA's web team. It was only one file, here's what it was:

`<?php
# Redirect to CBRE site with an HMAC token so they can verify the user has 
# logged in with us first. Task #17372.
$ENKI_TEMPLATE = false;
$shared_key = 'd9284539fa734be6a3a6035ce93ce8e7';
date_default_timezone_set('UTC');
$timestamp = date('YmdHis'); # YYYYMMDDHH24MMSS
$username = $_SERVER['CUWA_REMOTE_USER'];
$token =  hash_hmac("sha256", $username . $timestamp, $shared_key);
$url = "https://www.cbre-ea.com/outlook-dashboard/authenticate?userName=$username&timeStamp=$timestamp&token=$token";

SHA_HTTP::ExternalRedirect($url);
?>`

**Comment by manolobevia** [comment]
@kevinkidwell do you know what should we do with that code snippet?

**Comment by kevinkidwell** [comment]
I have absolutely no idea. Maybe @jgreidy or @mhk33 would know?

**Comment by manolobevia** [comment]
Hi @jgreidy , @mhk33 do you have any advice on this one? Thanks.

**Comment by mhk33** [comment]
I thought I had commented a while ago - I have no idea, sorry.

**Comment by mhk33** [comment]
From Adam:

So, this is just a very short PHP script that appears to read environment variables after successful CUWebAuth authentication and then redirects to a vendor URL (although I'm not familiar with the SHA_HTTP::ExternalRedirect() method) . So this could be done a few different ways, including making a very tiny WP plugin that uses existing Shibboleth authentication. The code is copied below.

Jim is on vacation for two weeks starting tomorrow, so can this wait until his return? I could start a plugin or some other approach, but I don't know how to tie into shib authentication in WP.

<?php
# Redirect to CBRE site with an HMAC token so they can verify the user has 
# logged in with us first. Task #17372.
$ENKI_TEMPLATE = false;
$shared_key = 'd9284539fa734be6a3a6035ce93ce8e7';
date_default_timezone_set('UTC');
$timestamp = date('YmdHis'); # YYYYMMDDHH24MMSS
$username = $_SERVER['CUWA_REMOTE_USER'];
$token =  hash_hmac("sha256", $username . $timestamp, $shared_key);
$url = "https://www.cbre-ea.com/outlook-dashboard/authenticate?userName=$username&timeStamp=$timestamp&token=$token";

SHA_HTTP::ExternalRedirect($url);
?>

**Comment by jgreidy** [comment]
Ken Bolton gave me his user and pw for https://pip.cbrehotels.com/. When I log in with that, I see a different page than when I log in with the code snippet.

**Comment by jgreidy** [comment]
From: James G. Reidy <jgr25@cornell.edu> 
Sent: Tuesday, August 20, 2019 4:06 PM
To: Ken Bolton <ktb4@cornell.edu>
Subject: Re: CBRE Hotel Horizons® September 2019 - November 2019 edition now available
 
Hi,
Strange – when I log in as you I go to a different place than where the snippet of login code takes me. (That code doesn’t care what user name you specify!)
 
https://www.cbre-ea.com/outlook-dashboard/authenticate?userName=cornell&timeStamp=20190820200258&token=05c5bf97287a3e56c1d3dd2261e41ce44d967dc0c8c21f46d347fc1e052b4743
 
See it this link works for you, and if the page you get to is useful.
 
-JGReidy

**Comment by jgreidy** [comment]
Yes, that link takes us to the landing page we were using previously, so that would work for us. I should also mention that the vendor wants access to be behind a firewall, even for on-campus usage.
 
Thanks,
Ken

**Comment by jgreidy** [comment]
Apparently 'behind a firewall' means user must log in to CUWebAuth before going to the link.

Kevin pointed out a way to do that with EZProxy:
Reference: https://www.library.cornell.edu/reserves/tools/linking
Prefix for url: https://login.proxy.library.cornell.edu/login?url=

Unfortunately, the url has to be registered with EZProxy beforehand.

There is a php code snippet to generate a URL, but that has a timestamp in it - not sure how long it would be valid.

So I'm still looking for a way to force a login before generating the URL for this Hotel Horizons database page.

**Comment by manolobevia** [comment]
@jgreidy is this issue fix. I don't remember if you fixed it on our last sprint.

**Comment by jgreidy** [comment]
@manolobevia Not quite yet. There are a lot of restrictions on the login - we've only applied some of them.

This is from Ken Bolton, talking about the restrictions on the login:

It should allow anyone with an active netID – students, staff, professors. One of the main purposes is to keep alumni from getting access. The vendor also insists that access is allowed from an on-campus computer only, even for anyone with an active netID. This prevents students from using it during the summer while they are serving an internship.

**Comment by jgreidy** [comment]
@manolobevia Where is the link to Hotel Horizons supposed to go on the Hotel web site?

**Comment by kevinkidwell** [comment]
@jgreidy it will go under the Hotel Horizons section on https://hotel.library.cornell.edu/research-databases/

**Comment by jgreidy** [comment]
I've added a link for Hotel Horizons to [https://web-services.library.cornell.edu/hotel-horizons-access](https://web-services.library.cornell.edu/hotel-horizons-access) .
