### ISSUE TITLE
ULS UNITS - Create site for Makerspace

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#287]
I found out this morning that we will need to move over http://makerspace.library.cornell.edu. It is currently a WP site but doesn't match our unit themes and we may as well be consistent with it. Can we go ahead and create the dev instance for this with the upstream?

**Comment by manolobevia** [comment]
@kevinkidwell do you have admin access on `http://makerspace.library.cornell.edu`? If you have, can you add `https://wordpress.org/plugins/all-in-one-wp-migration/`?

**Comment by kevinkidwell** [comment]
@manolobevia I just received admin access so I will add that to the site!
