### ISSUE TITLE
ULS UNITS - Library hours need be added to Libcal

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#289]
Hours need to be added to Libcal, so our WP plugin can get this data and display it on the library site.
Please, @sew268 @kevinkidwell contact Engineering library and let them know about this.
Thanks.

**Comment by mhk33** [comment]
I think that Engineering doesn't use Libcal because they are a 24/7 study space and do not have hours like the other units.

On the current Libraries page, the module that displays the hours outputs Libcal data for other units, but for Engineering the module is set to display this text: "24/7 study space and computing only."
https://www.library.cornell.edu/libraries

**Comment by manolobevia** [comment]
Annex doesn't have any hours on libcal, but it has hours on the site.

**Comment by manolobevia** [comment]
@mhk33 ok. That will need to be implemented on the plugin Tahir created.

**Comment by sew268** [comment]
@manolobevia I plan to add the Annex into LibCal and then I will show Cammie or perhaps Andy (once he arrives) how to maintain those hours

**Comment by manolobevia** [comment]
@sew268 do you know if we can have a custom text for today's library hour on Libcal ? ex: for `psl` we should have `Study Space open 24 hours`. Not a data type just text.

RE: `Management Library`. We are currently displaying the daily status of the library (open/close) and today's library hours. Ex:  `Open 24 hours`, and a link to `Full Hours` 

Management requested to include the department hours on the homepage header (not just a link), so I will have to display for all libraries. Have you seen how many departments have Mann :) ? I will continue having the library hour status and today's hour. Also, there is a link to `full hours`, which will link to a page with Dept. Hours.  
<img width="668" alt="Screen Shot 2019-06-19 at 1 05 25 PM" src="https://user-images.githubusercontent.com/8395482/59785933-15332800-9294-11e9-9830-a7bd1908d517.png">

The pattern I have seen on the 20 something libraries I have reviewed is just to have a link to hours or display the today's hours with a link to all hours.  I will continue having today's library status hours and a link on the header to Dept. hours. We have right now the label `full hours`, that could be changed to Dept. hours. Please see below.

<img width="777" alt="Screen Shot 2019-06-19 at 1 17 10 PM" src="https://user-images.githubusercontent.com/8395482/59786149-94c0f700-9294-11e9-9144-394abbe22e2e.png">

Is everybody Ok with this?

**Comment by manolobevia** [comment]
Also, we could link to https://www.library.cornell.edu/libraries/jgsm or embed (see below) the widget libcal generates. We have options.
<img width="1035" alt="Screen Shot 2019-06-19 at 1 41 27 PM" src="https://user-images.githubusercontent.com/8395482/59787741-1f572580-9298-11e9-90cf-f8b944470aab.png">

**Comment by manolobevia** [comment]
Here goes a sample of full hours or dept. hours page for mann.
http://dev-culu.pantheonsite.io/full-hours/

**Comment by kevinkidwell** [comment]
@manolobevia For Management, all we need to do is have the section where the hours are displayed be pulled from their Circulation Desk hours and then the Full Hours link could just go to their page on the main CUL site (https://library.cornell.edu/libraries/jgsm) to see all other hours.

We can see about going forward how we would want to do that and how the plugin may need to evolve for Mann just to have certain styling and be able to display all of those hours in a more user-friendly way on a page on their site, but that's down the road.

@sew268 Has added Engineering and PSL into libcal and there is a custom text field so we can display the text there. She is also adding the Annex in right now.

**Comment by manolobevia** [comment]
Ok, so instead of having today's library hours (what we have right now), they just want to use today's Circulation day hours. I will have to customize the header template for them, that's all.

<img width="314" alt="Screen Shot 2019-06-20 at 2 24 23 PM" src="https://user-images.githubusercontent.com/8395482/59872310-77a92880-9367-11e9-80ae-ab1aa67bcb96.png">

We don't need to take the user to CUL. If you check my last comment, I have created `http://dev-culu.pantheonsite.io/full-hours/`. We already have a link to https://library.cornell.edu/libraries/ on CULU header for ALL hours. Units will be able to display their weekly grid view (like CUL has). 

@sew268 thanks. That is great we can do that!!!!!

**Comment by manolobevia** [comment]
@sew268  here goes the text for:
PSL: `Study Space open 24 hours`
ENGINEERING: `24/7 study space and computing only`.
Let me know when is added to Libcal. Thanks.

**Comment by sew268** [comment]
@manolobevia thanks and all set in LibCal!

**Comment by manolobevia** [comment]
@sew268 Please add http://makerspace.library.cornell.edu/ hours to Libcal.

**Comment by sew268** [comment]
@manolobevia the Makerspace Hours are in LibCal - it's listed as a department under Mann and it's called the MannUfactory.  If that makes things complicate let me know.

**Comment by manolobevia** [comment]
@sew268 not et all. That's perfect. I will select the department.

**Comment by manolobevia** [comment]
https://github.com/cul-it/uls/issues/420 will take care of adding dept.  hours to headers.
