### ISSUE TITLE
ULS UNITS - Library names should be in uppercase.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#294]
Review all ULS dev sites and make sure the library name is in uppercase across all units.

**Comment by kevinkidwell** [comment]
@manolobevia Does this mean the full name of the units are uppercase such as "MANN LIBRARY" or that they will be with the first letter of each word capitalized like "Mann Library"?

**Comment by manolobevia** [comment]
@kevinkidwell A couple of years ago,  I created a new logo for CUL and their units that we are currently using. I started creating those logos to be added to a future brand identity book. The Unit library name uses uppercase to differentiate from Cornell University Library. We are using uppercase not capitalize. We don't have any logo for units libraries besides what I created. Right now we have just a logotype which uses Merriweather font. Since branding is on the air, I just want to be consistent having uppercase or capitalize. 
[cul-branding.pdf](https://github.com/cul-it/uls/files/3311556/cul-branding.pdf)

**Comment by mhk33** [comment]
FWIW, uppercase is supposed to be less easy to read for those with cognitive disabilities. I would say we don't capitalize in the new/future branding.

**Comment by kevinkidwell** [comment]
Yea, I find it harder to read when full words are fully uppercase. I like how we have it on units like Vet right now where just each word of the library name is capitalized. 

In that same vein, it came up in a couple of unit meetings about that headline font. Is that the font that is going to continue to be used or will there be options for stakeholders to select from maybe a list of a few for their unit name? Or is there a way, if we just want a single font, to pick one that feels like it would work with all unit names, maybe a slightly stylized sans-serif?

**Comment by manolobevia** [comment]
We are not talking about having whole pages on uppercase which I know is a disability issue. It will be acceptable to have the logo in uppercase if stakeholders or whoever is going to take care of the branding consider having the CUL unit name in uppercase. Think about CALS, CORNELL TECH, JHONSON School, and the million brands in uppercase. Sorry, I don't want to start a battle about this :)

**Comment by manolobevia** [comment]
re: select from maybe a list of a few for their unit name? Consistency in branding is key.

**Comment by mhk33** [comment]
I think it is a lot to process visually when the text is long, like CORNELL UNIVERSITY LIBRARY (e.g. why are you yelling??). It probably works better in some applications more than others.

**Comment by kevinkidwell** [comment]
I agree that we should keep a single font for that headline. Since a few stakeholders have expressed concern about that font, I think we should consider a few other options that we could then pick one as a group to apply across the board. Does that sound reasonable?

**Comment by manolobevia** [comment]
That is what I mentioned before :) Stakeholders should decide or branding group. I wish the branding group was working on this right now. Should we work on this and do a few explorations? Why not?

**Comment by mhk33** [comment]
I think we need it! The new branding.

**Comment by manolobevia** [comment]
@mhk33 I would be worried about having a logo for CUL, a logo for the College, and another logo for CUL UNIT, all yelling at the user at the same time and confusing them.

**Comment by kevinkidwell** [comment]
I don't think we need to have all the logos. I like how we have the main CUL logo in the top left, then the college logo off to the right (or just the name of the college in text if the unit prefers that), then just the name of the unit library as text in that main center box. We should just do some explorations of sizing and how those all fit together and what fonts for those various things would work together.

**Comment by manolobevia** [comment]
Remember IRL, LAW, and Management? They want the College logo. @kevinkidwell do you know if LAw and Rare want to have their own library logos?. The college logos will be big since the fonts need to be readable. I will go with just the text link for all colleges for now. We should have done exploration before we have done the implementation. Also, it could have been great if stakeholders provided some feedback about the visuals we showed them months ago. What I am trying to say is we should keep what we have and focus on this logo issue when there is an active branding team. I don't care if for now, we go with uppercase or lowercase for the library unit name. Sounds good?

**Comment by manolobevia** [comment]
If stakeholders want to start on CUL and CUL unit logos redesign, we could start working on a creative brief for the branding, before doing any exploration. But this is gathered with the clients' input. This is the first step on the branding process I have always followed when creating a visual identity for the brand, not creating the brand. I am not a brand strategist. We talk about the brand when we refer to the logo of an entity, but what we need is a logo/s that support the brand. The problem is we don't have a brand.

**Comment by manolobevia** [comment]
For now, I have added a function to convert the library name on home and interior headers to uppercase. When we reach a consensus with stakeholders, we can add a function to convert to italicized or keep it the way it is now.
