### ISSUE TITLE
ULS UNITS - Staff Profiles should have option for social accounts

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#295]
On Management, there are a few users who have their LinkedIn accounts as a link with their profile. I have a feeling some of the other units will want similar links either for their ORCid or LinkedIn.

@manolobevia I can edit the staff template and custom fields to do this if you want me to make that edit. If you do, what repo do you want me to make the edit in?

**Comment by kevinkidwell** [comment]
This has been done on the multi-dev instance "staffpro" and can be viewed here: http://staffprof-culu.pantheonsite.io/category/staff-profile/

All I did was add LinkedIn and ORCid for now, and we can have the option to add more in the future if necessary.

**Comment by manolobevia** [comment]
Great. Thanks. Can you add hover state colour to the ORCid icon?
