### ISSUE TITLE
ULS UNITS -  Provide in CULU functionality to add social media links for unit libraries.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#296]

**Comment by kevinkidwell** [comment]
This is a feature that units are requesting be available. We are going through the content editing documentation and noticed this wasn't built in yet so just wanted to bump up the priority because it keeps coming up more often from multiple units.

**Comment by manolobevia** [comment]
@kevinkidwell We are using simple social icons plugin, `https://wordpress.org/plugins/simple-social-icons/`

I registered a widget (Social Media) where users can add their social media links. I have removed the ui controls for adding styles so editors won't change styles.

Troubleshooting Tips
https://wordpress.org/plugins/simple-social-icons/
