### ISSUE TITLE
ULS UNITS - Enable multidev on CULU, so we can do branches.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#300]
![Screen Shot 2019-06-21 at 9.54.37 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/0dcaa528-d7ff-4b24-9a2d-c60c1111ac55)

**Comment by kevinkidwell** [comment]
In addition to this, I was doing some research on using github in addition to pantheon for a multi-dev environment. I think we'd be able to do it if we follow this guide: https://pantheon.io/docs/guides/collaborative-development/. It's relatively easy to set up in terminal, it's just a matter of having the multi-dev setup to be able to check on the feature branches, then whenever we merge it on github as a PR, we just have to push the master branch to pantheon. If we wanted to do this, it would then allow us to keep the code in a github repo.

**Comment by kevinkidwell** [comment]
@manolobevia I was able to create the multi-dev environment for CULU. I just followed the link above and was able to make it using `terminus` commands. I created one for the staff profiles for now so that I can work in there.

If you want to make any new multi-dev branches, you can use `terminus multidev:create culu.dev <branch name>`

**Comment by manolobevia** [comment]
I wonder why we can not do it from Pantheon's website. I am able to create branches from there normally. That's great with terminus we are able too it. 
re: https://pantheon.io/docs/guides/collaborative-development/, I would `love` if that happens for the custom stream. @jgreidy is that possible? To have the upstream and units on a github repo.

**Comment by manolobevia** [comment]
I have been requesting this since the beginning of the project :)

**Comment by jgreidy** [comment]
You can not make multi-devs for CULU because it is a 'Sandbox' site. It has to be a 'Personal' site to use that feature, automated backups, etc. I will try to upgrade CULU.

**Comment by jgreidy** [comment]
Can't make multi-devs in sandbox sites - must be 'Basic'
