### ISSUE TITLE
ULS UNITS - Create new upstream  (v1.2.4 )based on latest changes on CULU.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#310]

**Comment by jgreidy** [comment]
I will take the CULU theme from culu-library-cornell-edu.

**Comment by jgreidy** [comment]
plugin versions in culu-library-cornell-edu

+-----------------------------------+----------+--------+---------+
| name                              | status   | update | version |
+-----------------------------------+----------+--------+---------+
| acf-better-search                 | active   | none   | 3.3.1   |
| advanced-custom-fields-pro        | active   | none   | 5.8.1   |
| akismet                           | inactive | none   | 4.1.2   |
| all-in-one-wp-migration           | active   | none   | 6.97    |
| ares_wordpress-master             | active   | none   | 1.0     |
| better-font-awesome               | active   | none   | 1.7.1   |
| child-theme-configurator          | active   | none   | 2.5.0   |
| classic-editor                    | active   | none   | 1.5     |
| custom-post-type-ui               | active   | none   | 1.6.2   |
| elementor                         | active   | none   | 2.5.16  |
| elementor-pro                     | active   | none   | 2.5.9   |
| google-analytics-dashboard-for-wp | active   | none   | 5.3.8   |
| granular-controls-for-elementor   | active   | none   | 1.0.5   |
| intuitive-custom-post-order       | active   | none   | 3.1.2   |
| kirki                             | active   | none   | 3.0.44  |
| wp-libcal-hours-dev               | active   | none   | 1.0.0   |
| wordpress-importer                | active   | none   | 0.6.4   |
| wp-cfm                            | active   | none   | 1.5.1   |
| wp-saml-auth                      | inactive | none   | 0.6.0   |
| wp-ultimate-csv-importer-pro      | active   | none   | 5.5     |
| elementor-safe-mode               | must-use | none   | 1.0.0   |
| pantheon                          | must-use | none   | 0.1     |
+-----------------------------------+----------+--------+---------+

**Comment by jgreidy** [comment]
Created v1.2.4
