### ISSUE TITLE
ULS UNITS  - Wrong library and department hours status.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#313]
Circulation desk opens from 8:30am to 8:30pm. The hour's plugins display: `Opens tomorrow at 8:30am`. It should display: `Opens today at 8:30am` or `Opens at 8:30am`. The current time checking the hours was: 8:05 AM.

![Screen Shot 2019-06-27 at 7.59.47 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/2e0dd132-6275-4b52-b423-3d690fd998a1)

**Comment by manolobevia** [comment]
Not just for Management, also wrong display in all libraries status hours.

<img width="813" alt="Screen Shot 2019-06-27 at 8 07 09 AM" src="https://user-images.githubusercontent.com/8395482/60265109-d532fd00-98b2-11e9-9049-019931ca8191.png">

**Comment by jgreidy** [comment]
Is the issue here that the library hours display does not change when it should?

**Comment by manolobevia** [comment]
This is an unrelated issue. Not right logic in the code.

**Comment by jgreidy** [comment]
Is the problem that the message should change from "Opens tomorrow" to "Opens today" at just after midnight?

**Comment by manolobevia** [comment]
Correct.

**Comment by manolobevia** [comment]
Cache related issue fixed.
