### ISSUE TITLE
ULS Upstream - test update of finearts to v1.2.5

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#318]
In a multidev called upcheck run the upstream update to see what happens.

**Comment by jgreidy** [comment]
Before upstream update to v1.2.5

├── plugins
│   ├── acf-better-search
│   ├── advanced-custom-fields-pro
│   ├── akismet
│   ├── all-in-one-wp-migration
│   ├── ares_wordpress
│   ├── better-font-awesome
│   ├── classic-editor
│   ├── custom-post-type-ui
│   ├── elementor
│   ├── elementor-pro
│   ├── google-analytics-dashboard-for-wp
│   ├── granular-controls-for-elementor
│   ├── intuitive-custom-post-order
│   ├── json-content-importer
│   ├── kirki
│   ├── pantheon-advanced-page-cache
│   ├── wp-cfm
│   ├── wp-libcal-hours
│   ├── wp-mail-smtp
│   ├── wp-native-php-sessions
│   ├── wp-saml-auth
│   └── wp-ultimate-csv-importer-pro
└── themes
    ├── culu
    ├── culu-child
    └── twentynineteen

**Comment by jgreidy** [comment]
`terminus wp uls-finearts-library-cornell-edu.upcheck -- plugin list`

+-----------------------------------+----------+-----------+---------+
| name                              | status   | update    | version |
+-----------------------------------+----------+-----------+---------+
| acf-better-search                 | inactive | available | 3.3.0   |
| advanced-custom-fields-pro        | active   | available | 5.8.0   |
| akismet                           | inactive | none      | 4.1.2   |
| all-in-one-wp-migration           | active   | none      | 6.97    |
| ares_wordpress                    | inactive | none      | 1.0     |
| better-font-awesome               | active   | none      | 1.7.1   |
| classic-editor                    | active   | none      | 1.5     |
| custom-post-type-ui               | inactive | none      | 1.6.2   |
| elementor                         | active   | none      | 2.5.16  |
| elementor-pro                     | active   | none      | 2.5.9   |
| google-analytics-dashboard-for-wp | active   | none      | 5.3.8   |
| granular-controls-for-elementor   | inactive | none      | 1.0.5   |
| intuitive-custom-post-order       | inactive | none      | 3.1.2   |
| json-content-importer             | inactive | none      | 1.3.4   |
| kirki                             | active   | available | 3.0.43  |
| wp-libcal-hours                   | active   | none      | 1.0.0   |
| wp-native-php-sessions            | inactive | none      | 0.7.0   |
| pantheon-advanced-page-cache      | inactive | none      | 0.3.0   |
| wp-cfm                            | active   | none      | 1.5.1   |
| wp-mail-smtp                      | active   | none      | 1.4.2   |
| wp-saml-auth                      | active   | none      | 0.6.0   |
| wp-ultimate-csv-importer-pro      | active   | none      | 5.5     |
| pantheon                          | must-use | none      | 0.1     |
+-----------------------------------+----------+-----------+---------+

**Comment by jgreidy** [comment]
I found two extra .git repos in finearts before the upstream update:

lib-jgr25-maclap:upcheck-uls-finearts-library-cornell-edu jgr25$ pwd
/Users/jgr25/Documents/active/wordpress/sites-pantheon/upcheck-uls-finearts-library-cornell-edu
lib-jgr25-maclap:upcheck-uls-finearts-library-cornell-edu jgr25$ find ./ -name .git
.//web/wp-content/plugins/advanced-custom-fields-pro/.git
.//web/wp-content/themes/culu/.git
.//.git

**Comment by jgreidy** [comment]
This causes problems during composer install:

<img width="1215" alt="Screen Shot 2019-06-28 at 3 22 37 PM" src="https://user-images.githubusercontent.com/5996967/60366568-e74b9300-99b9-11e9-838b-e2f9cd72104d.png">

**Comment by jgreidy** [comment]
To get rid of these extra .git repos, you have to remove the contents of the /vendor folder. Something in there causes them to come back into /web/wp-content/* whenever composer install runs. 
composer install will then rebuild a clean /vendor folder.

**Comment by jgreidy** [comment]
After composer update:

+-----------------------------------+----------+--------+---------+
| name                              | status   | update | version |
+-----------------------------------+----------+--------+---------+
| acf-better-search                 | inactive | none   | 3.3.1   |
| advanced-custom-fields-pro        | active   | none   | 5.8.1   |
| akismet                           | inactive | none   | 4.1.2   |
| all-in-one-wp-migration           | active   | none   | 6.97    |
| ares_wordpress                    | inactive | none   | 1.0     |
| better-font-awesome               | active   | none   | 1.7.1   |
| classic-editor                    | active   | none   | 1.5     |
| custom-post-type-ui               | inactive | none   | 1.6.2   |
| elementor                         | active   | none   | 2.5.16  |
| elementor-pro                     | active   | none   | 2.5.9   |
| google-analytics-dashboard-for-wp | active   | none   | 5.3.8   |
| granular-controls-for-elementor   | inactive | none   | 1.0.5   |
| intuitive-custom-post-order       | inactive | none   | 3.1.2   |
| json-content-importer             | inactive | none   | 1.3.4   |
| kirki                             | active   | none   | 3.0.44  |
| wp-libcal-hours                   | active   | none   | 1.0.0   |
| wp-native-php-sessions            | inactive | none   | 0.7.0   |
| pantheon-advanced-page-cache      | inactive | none   | 0.3.0   |
| wp-cfm                            | active   | none   | 1.5.1   |
| wp-mail-smtp                      | active   | none   | 1.4.2   |
| wp-saml-auth                      | active   | none   | 0.6.0   |
| wp-ultimate-csv-importer-pro      | active   | none   | 5.5     |
| pantheon                          | must-use | none   | 0.1     |
+-----------------------------------+----------+--------+---------+

├── plugins
│   ├── acf-better-search
│   ├── advanced-custom-fields-pro
│   ├── akismet
│   ├── all-in-one-wp-migration
│   ├── ares_wordpress
│   ├── better-font-awesome
│   ├── classic-editor
│   ├── custom-post-type-ui
│   ├── elementor
│   ├── elementor-pro
│   ├── google-analytics-dashboard-for-wp
│   ├── granular-controls-for-elementor
│   ├── intuitive-custom-post-order
│   ├── json-content-importer
│   ├── kirki
│   ├── pantheon-advanced-page-cache
│   ├── wp-cfm
│   ├── wp-libcal-hours
│   ├── wp-mail-smtp
│   ├── wp-native-php-sessions
│   ├── wp-saml-auth
│   └── wp-ultimate-csv-importer-pro
├── themes
│   ├── culu
│   ├── culu-child
│   └── twentynineteen

**Comment by jgreidy** [comment]
It looks like some content is gone from the site after update:
https://dev-uls-annex-library-cornell-edu.pantheonsite.io/
vs
https://upcheck-uls-finearts-library-cornell-edu.pantheonsite.io/home/

**Comment by manolobevia** [comment]
@jgreidy it is not gone, the problem is because of the second `culu-child` added after the downstream. WP is activating the new culu-child added by the downstream by default, which doesn't have any data added via customizer.
![Screen Shot 2019-07-09 at 1 32 16 PM](https://user-images.githubusercontent.com/8395482/60910323-7d02e000-a24e-11e9-8b22-6db7d37baa53.png)
