### ISSUE TITLE
ULS UNITS - Search on a page other than home doesn't work

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#322]
On Management, I attempted to search the entire site from the About page and it ends up only searching on the about page and not taking the user to an overall search page.

Here is the URL that ends up happening:
`https://dev-uls-management-library-cornell-edu.pantheonsite.io/about/?s=cap+iq&search-type=site`
When it should be this:
`https://dev-uls-management-library-cornell-edu.pantheonsite.io/?s=cap+iq&search-type=site`

**Comment by manolobevia** [comment]
Fix issue on CULU.

**Comment by manolobevia** [comment]
@kevinkidwell Fixed. Once @jgreidy push this fix to upstream and then downstream to units sites, you'll be able to see the fix.
