### ISSUE TITLE
ULS UNITS - Search - Add FacetWP and use to organize search results

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#323]
We should add FacetWP to our search results page so that we are able to filter the search results. This is especially relevant on Management with their subject tags.

In the same vein, we can create a search results page in Elementor that uses the FacetWP shortcodes to show all of the relevant facets/pagination/sorting and style it using Elementor and some custom CSS.

**Comment by kevinkidwell** [comment]
Example of this: http://dev-agcensus-test.pantheonsite.io/?s=alabama

This plugin will be used on all unit sites with searching/search results and faceting.

**Comment by manolobevia** [comment]
I think that makes sense for management ( I wonder if PSL would like this feature ), but we have a few units with a very low amount of content and having faceted search wouldn't be ideal. There is an issue for adding this plugin to CULU.

**Comment by manolobevia** [comment]
RE: There is an issue for adding this plugin to CULU. 
I don't understand why I wrote that.
