### ISSUE TITLE
ULS UNITS - Search - Add Relevanssi plugin

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#324]
This is a plugin that I found that we have been using on AgCensus. It allows to add specific weight to parts of posts and custom posts so that users will be able to receive more relevant search results instead of by most recently edited first.

https://wordpress.org/plugins/relevanssi/

**Comment by manolobevia** [comment]
@kevinkidwell are we using this plugin? Need to be added to CULU?
