### ISSUE TITLE
ULS UNITS - Style category and tag pages

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#329]
Looking at Tag and Category pages on Management, these will need to have some style adjustments.

Right now there is a lack of space and when hovering over any of the tags, it highlights all of them. I think the problem with the categories is that even the databases is pulling from the staff loop so any category page that isn't staff doesn't display.

**Comment by manolobevia** [comment]
Breaking this into 2 issues. Before I didn't have a loop.php, it is added on culu.
