### ISSUE TITLE
ULS UNITS - Add a few plugins to CULU

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#333]
- [x] Code Snippets
- [x] FacetWP
- [ ] FacetWP - Conditional logic
- [x] WP RSS Aggergator
- [x] Draw Attention
@jgreidy `Code Snippets` and `WP RSS Aggregator` will be part of the upstream.

**Comment by kevinkidwell** [comment]
We will also need [Draw Attention](https://wpdrawattention.com/), for the floor plans/stacks maps.

Facet WP, RSS Aggregator, and Draw Attention all need the paid versions. We emailed @mbmartini last week about purchasing them so we should make sure we have those versions before they get added everywhere.

**Comment by manolobevia** [comment]
@jgreidy make all the plugins part of the upstream.

**Comment by manolobevia** [comment]
@jgreidy Please add https://www.seedprod.com/. It is a maintenance mode plugin. It needs to be in the upstream.

Also, can you put back Elementor and Elementor pro on the upstream? It is a pain to update this every time there is an update at the unit level. Thanks.

**Comment by jgreidy** [comment]
When we talked today, @manolobevia , you had decided not to put Elementor Pro in the upstream.

**Comment by manolobevia** [comment]
Please add `FacetWP - Conditional logic` to our next upstream.

**Comment by jgreidy** [comment]
- [ ] FacetWP - Conditional Logic

**Comment by manolobevia** [comment]
Creating a new issue for FacetWP - Conditional Logic
