### ISSUE TITLE
ULS UNITS - Update library hours plugin for including all libraries and department hours.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#350]

**Comment by jgreidy** [comment]
What site is this for?

**Comment by manolobevia** [comment]
PSL
MakerSpace (not a priority)

On culu, I have added PSL to the plugin on the culu theme, and it works, but If I get the latest plugin from the master. It doesn't.

**Comment by manolobevia** [comment]
Include also MakerSpace.

**Comment by kevinkidwell** [comment]
@manolobevia I wanted to check on this because of launching Makerspace today, they noticed the hours were off and just wanted to see if there was a way to get them to show.

**Comment by manolobevia** [comment]
I am addressing this issue here at `https://github.com/cul-it/uls/issues/356`. Right now I have a snippet implemented for adding department hours as management does. Could you take a screenshot of the issue? We have so many problems with the plugin.


![Screen Shot 2019-08-21 at 9 14 48 PM](https://user-images.githubusercontent.com/8395482/63478725-e6365f80-c458-11e9-9db5-2f7559e8a4ab.png)

**Comment by manolobevia** [comment]
Based on the attachment the plugin works. If I am up after 12 am,  I will check the status hours on engineering, makerspace, psl, and fine arts. After 12am is when we see the problem, at least with finearts.

**Comment by kevinkidwell** [comment]
The hours only match because they're set to Mann in the plugin. Those hours match Wednesday/Thursday but not Friday. I can also dive into the plugin to see what's up and if I can fix this and the PSL issue, if you have other stuff on your plate.

**Comment by manolobevia** [comment]
I have logic for when we are dealing with departments hours. Makerspace is not set to Mann lid. I am using the makerspace lid. Like I mentioned in another issue, I have checked the plugin at 7:44am today and displays the wrong content. 

--------
<div class="available-time">

  <i class="fas fa-clock icon-time" aria-hidden="true"></i>
  <span class="libcal-status-now">`<?php echo do_shortcode('[libcal_status_now lid="8658"]') ?>`</span>
  <span class="libcal-hours-today"> `<?php echo do_shortcode('[libcal_hours_today lid="8658"]') ?>` </span>
  - <a class="full-hours" href="/full-hours">Full Hours</a> /

</div>

**Comment by manolobevia** [comment]
or we can add this Lid to the plugin like you said and I did for PSL.
