### ISSUE TITLE
ULS UNITS - On local instances of CULU, I am unable to update plugins.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#354]
I get the following message: `Update Failed: Download failed. Destination directory for file streaming does not exist or is not writable.` 
These folders have this file permission `drwxr-xr-x`. Could you help me with this @jgreidy ?

**Comment by jgreidy** [comment]
Here is another way to fix this: https://www.dessol.com/blog/fix-wordpress-destination-directory-for-file-streaming-does-not-exist-or-is-not-writable/

**Comment by manolobevia** [comment]
THANKS, @jgreidy it works great.
