### ISSUE TITLE
ULS UNITS - Current libcal plugin hours breaks the theme

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#355]
![Screen Shot 2019-07-22 at 10.10.54 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/b3449799-f849-44ad-969a-fbc51eab7e7c)

**Comment by jgreidy** [comment]
Catherwood site is not up to date with the current upstream version.

**Comment by manolobevia** [comment]
It's ok. I will update with r 1.2.7. The rest are updates, and they have the same issue. I have to disable the hour's plugin to work.

**Comment by manolobevia** [comment]
I just updated to 1.2.6. Same issue. I have disabled the plugin.

**Comment by jgreidy** [comment]
Fixed in wp-libcal-hours v1.0.4

**Comment by jgreidy** [comment]
Fixed July 22
