### ISSUE TITLE
ULS UNITS - Adding social media links to footer

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#364]
Units should have the option to add links for their social media accounts in the same way that they do footer contact information

This should all be editable by library staff

**Comment by manolobevia** [comment]
@sew268 I am closing this issue because it is duplicated: `https://github.com/cul-it/uls/issues/296`

**Comment by sew268** [comment]
@manolobevia my bad. :)

**Comment by manolobevia** [comment]
@sew268 no worries. I duplicate my own issues so often.
