### ISSUE TITLE
ULS UNITS - Add plugin to restrict admin menu items by role

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#365]
There are a number of users who will be using the unit sites to edit content and they should end up having the role of Editor. Some of the options in the sidebar menu do not need to be shown for editors and others should be shown that aren't.

We're using a free plugin called Advanced Access Manager with AgCensus that I think would do great for this but I wanted to get your opinion on it first @manolobevia. Here is a link to it: https://wordpress.org/plugins/advanced-access-manager/

This plugin would also allow us to create new roles and give very specific access to what they can do on the site. For instance, this would be good for ILR with their students who create Workplace Issues Today posts.

**Comment by manolobevia** [comment]
@kevinkidwell If you think is good, let's add it to CULU. Can we use this with Elementor so editors don't change the layout? I know we can do some restriction with it but not sure how much?

**Comment by kevinkidwell** [comment]
Do we need to do this as an upstream plugin? We should get this into the sites that are going live before the semester, at least.

We can lock down Elementor so that they are only able to edit content and not touch layout. I’m going to do that along with this plugin.
