### ISSUE TITLE
ULS UNITS - Staff Profile fields

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#378]
@manolobevia I had a chat with Sara about what fields should be used for Staff Profiles so that we can get them all in now and then we shouldn't need to go back and adjust in the near future. Below is the list that she gave me, with * next to what should be required.

First Name*
Last Name*
Title*
Email*
Phone
Office Location
Book a Consultation
Areas of Expertise
ORCID ID
Linkedin Profile
Liaison Areas

This is just an over-arching list that includes #373, #374, and #375 with the addition of Liaison Areas and what should be required/optional.

**Comment by manolobevia** [comment]
Also **degree**. 
Ex: Peter Johnson, **MS, DVM, MLIS**

**Comment by manolobevia** [comment]
Reopening issue, I forgot to add a field for displaying type of staff: `staff`, `administration`, etc.
