### ISSUE TITLE
ULS UNITS FINEARTS - Add redirects to wp-config

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#380]
Following up with the email from Greg on the FineArts redirects, these URLs should be added into the `wp-config.php` file.

@jgreidy @manolobevia I'm not sure on the process for this. Would editing each unit's individual wp-config interfere with the CULU theme one if we needed to make edits there? This is something that we'll need to do for all upcoming units. Would one of you be able to do this?

Here is the redirects file Greg sent, with a few updates to URLs from me:
[fineartsredirects-trailingslashes.txt](https://github.com/cul-it/uls/files/3446684/fineartsredirects-trailingslashes.txt)

**Comment by manolobevia** [comment]
@kevinkidwell good point. I have no clue. @jgreidy is it possible to have the redirect in a file at the theme level, then include that file in wp-config.php? That way, we don't override wp-config.php on the units when we update CULU.

**Comment by manolobevia** [comment]
@kevinkidwell if we don't figure out this while Jim is on vacations, we can just add the redirect content on FINEARTS's wp-config.php for now.
