### ISSUE TITLE
ULS UNITS - Adjust staff profile pages to include 5 profiles on desktop and large devices

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#386]

**Comment by kevinkidwell** [comment]
@manolobevia I think we should hold off on this and get some other stakeholder feedback or do some user testing. I'm worried if we make those cards any smaller, text is going to start wrapping oddly and make it actually less user-friendly. What they're worried about is only aesthetics when we need to also consider the users of this page.

**Comment by manolobevia** [comment]
@kevinkidwell I am with you. Right now the right margin for each car is 20 pixels, if I reduce to 15px, I can have 5 profiles in a row for Desktop and Large devices. My problem is I always try to avoid patches on units. I should do the change on CULU then update all units with this change. I can do the change on CULU or put a patch on `finearts`. You decide.

**Comment by manolobevia** [comment]
I meant: ... I can do the change on CULU and wait to downstream the change when Jim is here or put a patch on `finearts` right now. You decide.

**Comment by kevinkidwell** [comment]
@manolobevia I think right now, let's see how they respond to the email I just sent them before we make any changes.

I think we should only put whatever choice we end up going with as a temporary patch to the Fine Arts site and we don't worry about editing CULU until we've done some user testing.

**Comment by manolobevia** [comment]
Ok, 
![Screen Shot 2019-07-31 at 2 37 14 PM](https://user-images.githubusercontent.com/8395482/62238377-e2a34180-b3a0-11e9-904e-22716a6485b4.png)
It actually looks good.

**Comment by kevinkidwell** [comment]
@manolobevia Based on that last email from Carla, I think that we should go with that reduced spacing so that we can get all 5 on one line for them. Let's only do it on their instance and then we can plan some user testing and stakeholder feedback after they launch.

**Comment by manolobevia** [comment]
Made staff profile responsive on small and tablet devices.
