### ISSUE TITLE
ULS UNITS FINEARTS - Pages not loading due to redirect

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#387]
On the Live instance of Fine Arts, trying to go to Databases or Equipment under Resources gives an error page saying that there were too many redirects occurring.

**Comment by gdelisle** [comment]
This is probably because there are redirects for those items that point to themselves. Remove the following from the redirects in wp-config.php:
'/equipment' => '/equipment',
'/databases' => '/databases',
'/equipment/' => '/equipment',
'/databases/' => '/databases',

**Comment by manolobevia** [comment]
I'll remove those redirect.
