### ISSUE TITLE
ULS UNITS FINEARTS - One-click sign in not working on Live

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#388]
Trying to sign in with the One-click authentication on our Live instance throws a page saying:

An error occurred while processing your request.
Error Message: Unsupported Request 

The application you have accessed is not registered for use with this service.

**Comment by manolobevia** [comment]
This will be fixed when @jgreidy  is back from vacation.

**Comment by manolobevia** [comment]
I have disabled this feature, until it is set up properly.

**Comment by kevinkidwell** [comment]
I have the stakeholders asking about the progress of this, so I wanted to check to see about it.

**Comment by manolobevia** [comment]
@jgreidy thanks.
