### ISSUE TITLE
ULS UNITS PSL: Site launch.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#393]
Migration: Complete
Launch day:`August 26th`
Current site: https://dashboard.pantheon.io/sites/343a4de1-6b88-462a-bd06-56b78ded4cce#dev/code
New Site: https://dashboard.pantheon.io/sites/ba552c66-aa18-4202-b712-b8612d0d6d11#dev/code
Domain: https://physicalsciences.library.cornell.edu/

**Comment by manolobevia** [comment]
Redirects: No

**Comment by manolobevia** [comment]
Contacted PSL 2 months ago asking timeline to launch. I contacted again yesterday, if we don't get an answer, we should provide to the client a day to launch.

**Comment by kevinkidwell** [comment]
There isn't much of a change between the sites, so if we don't hear back, I think we should just launch them with others before the start of the semester. Then we can set up a meeting after launch to go over any questions.

**Comment by manolobevia** [comment]
I agree, but I think we should tell them ahead we are making the site live day X.

**Comment by manolobevia** [comment]
@gdelisle we will be launching PSL this coming Monday like Hotel.
