### ISSUE TITLE
ULS UNITS HOTEL - Site launch

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#394]
Migration: Complete
Launch day: **August 26th**
Current site: https://dashboard.pantheon.io/sites/378b1497-8299-42b1-94d3-bd67abdbae89
New Site: https://dashboard.pantheon.io/sites/88600999-91cb-4bfc-882a-e4a1a7d9e832#dev/code
Domain: https://hotel.library.cornell.edu/

**Comment by manolobevia** [comment]
Redirects: No

**Comment by manolobevia** [comment]
@gdelisle we have the ok for the client to launch this site August 26th. Thanks.

**Comment by gdelisle** [comment]
@manolobevia can this issue be closed?

**Comment by manolobevia** [comment]
@gdelisle closing it.
