### ISSUE TITLE
ULS UNIT MANAGEMENT - Site launch

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#399]
Migration: `Pending`
Launch day: 12/16/19
Current site: `https://dashboard.pantheon.io/sites/f51035b4-bfb8-4360-8ff7-8c80506015fc#dev/code`
New Site: `https://dashboard.pantheon.io/sites/b79409ad-3d8a-44e8-9585-dd430c6e3ab8
Domain: https://johnson.library.cornell.edu/`
Redirects: `Pending`
Initialize test and live environments: `Pending`
Enable search Engine Visibility

**Comment by manolobevia** [comment]
@sew268  @kevinkidwell let us know when you meet with Rachel tomorrow when we should launch the site. Since it is pretty much ready.

**Comment by kevinkidwell** [comment]
@manolobevia We still have quite a bit of content work to do with Management before it is ready to launch. We are going to keep them in the dev site until after the Fall semester and launch them with the others then.
