### ISSUE TITLE
ULS ANNEX - Site launch

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#400]
Migration: Done
Launch day: August 21st.
Current site: https://dashboard.pantheon.io/sites/f23e3c0a-aeb0-43c1-a6b8-e4a485248d78
New Site: https://dashboard.pantheon.io/sites/807c1d68-c79d-4836-b4f4-b68ee23cb48f#dev/code
Domain: https://annex.library.cornell.edu/
Redirects: ?
Initialize test and live environments: Pending

**Comment by manolobevia** [comment]
@sew268 @kevinkidwell Do we have a launch time for Annex? This site is pretty much done. Right?

**Comment by kevinkidwell** [comment]
@manolobevia We are setting up a meeting for Andy and Cammie to review the content and once that's done we'll be ready to launch. We would like to get this site live before the Fall semester.

**Comment by manolobevia** [comment]
Let's plan for August 19th (Monday). I think Hotel would like to launch before the Fall semester too.

**Comment by kevinkidwell** [comment]
After our meeting with Cammie and Andy last week, we are good to go on launching this site. They are going to provide a new banner image but we can go live as-is and change after.

**Comment by manolobevia** [comment]
Do we need redirects?

**Comment by kevinkidwell** [comment]
No, no redirects necessary!
