### ISSUE TITLE
ULS MAKERSPACE - Site Launch

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#402]
Migration: Complete
Launch day: August 21st
Current site: https://dashboard.pantheon.io/sites/ad432440-adf7-4624-b13d-15d0b233e398
New Site: https://dashboard.pantheon.io/sites/bafc7fb0-7a8f-4307-b341-52a6660249e3
Domain: https://makerspace.library.cornell.edu/
Redirects: No
Initialize test and live environments: Pending

**Comment by manolobevia** [comment]
Launch day might change. @jgreidy is back August 15th from vacation. There are a lot of culu updates and plugins that need to be updated before the launch. I will coordinate with him when he is able to create a new upstream, then I need to test these new updates on the unit libraries. Also, @gdelisle needs to do his part, so I will provide a feasible launch day after I talk to Jim and Greg.
