### ISSUE TITLE
Staff Profiles

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#405]
Is there an adjustment that can be made so that a comma doesn't appear after each person's name?
See: https://dev-uls-annex-library-cornell-edu.pantheonsite.io/staff-profiles/

The comma makes sense if they want to add a value in the degree field but I'm guessing many of the staff position will choose not to have a value there.

**Comment by manolobevia** [comment]
@sew268 It is already fixed on CULU (parent theme). We need to wait for @jgreidy to push this change (and other changes)  to the custom upstream. Once it is ready, I will downstream to all unit libraries. You can see the current development for staff profiles templates, `http://dev-culu-library-cornell-edu.pantheonsite.io/staff-profiles/`

**Comment by sew268** [comment]
@manolobevia well that was easy :)
