### ISSUE TITLE
ULS UNITS - Teach how to create an upstream from CULU instance.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#406]
@jgreidy when you have time next week, let's meet and show me the process. Just for code theme changes. Thanks

**Comment by jgreidy** [comment]
See README.md in https://github.com/cul-it/ci-jenkins-pantheon-wordpress/blob/master/README.md#build-a-new-upstream for background information.

**Comment by manolobevia** [comment]
Thanks. I will move this to the wiki.
