### ISSUE TITLE
Staff Profile Name Order

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#408]
@manolobevia can staff profiles be displayed in alphabetical order by last name?

**Comment by manolobevia** [comment]
I already have a plugin for organizing the staff profiles. It would be ideal to have alpha order all the time, but other libraries want the order by seniority or job level like Hotel or Vet, so far. We don't have hundreds of profiles for each library unit, so the plugin (`Intuitive Custom Post Order`) I am using is enough for ordering the way we want (manually).

**Comment by manolobevia** [comment]
@sew268 Do you want to order all by the last name for now on?

**Comment by sew268** [comment]
@manolobevia Hmm, I wasn't aware that some units wanted to order by seniority/job level which I guess also makes sense. 
I like alphabetical by last name but it sounds like what might be best is having an option to drag and drop profiles in the order that the unit would like them.   Is that possible?

**Comment by manolobevia** [comment]
@sew268 that's what we have :). We can drag and drop profiles order.

**Comment by sew268** [comment]
ah - maybe I just don't have the right permissions?  I could add profiles but couldn't reorder them.  I'll take another look once I'm out of a meeting and see if I just missed something

**Comment by manolobevia** [comment]
@sew268 Which site are you working on?
