### ISSUE TITLE
ULS UNITS - Branding - CUL Logo

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#410]
According to the Cornell logo guidelines (https://brand.cornell.edu/logos/), we should be using the Reduced Lockup and it must be no shorter than 45px tall. I recommend making it 50px for an even number and to give a good amount of weight to the Library logo in relation to other page elements.

In looking at the Library logo, we should be using Montserrat sans-serif font. This is the Library font for all of the logo iterations. A version of the Reduced Lockup with the Library text in Montserrat is here: https://cornell.box.com/s/3c0q1lronlm4nvukwok5zwvsa7cb964u

**Comment by manolobevia** [comment]
Actually, if we consider Cornell University library as non-academic we shouldn't be using the reduced lock-up. Below are samples for non-academic. 

![Screen Shot 2019-08-13 at 10 26 45 AM](https://user-images.githubusercontent.com/8395482/62950357-df9f4c80-bdb5-11e9-88d0-2c4391917040.png)
![Screen Shot 2019-08-13 at 10 26 51 AM](https://user-images.githubusercontent.com/8395482/62950358-df9f4c80-bdb5-11e9-9556-ca831961368b.png)
![Screen Shot 2019-08-13 at 10 26 56 AM](https://user-images.githubusercontent.com/8395482/62950359-df9f4c80-bdb5-11e9-9614-4aa21cc5ead3.png)

I just contacted Cornell brand and verify how we should treat CUL, academic or non-academc? 
If we consider CUL as academic. We don't need to use the lockup in all different devices, only if If the seal is less than 73px tall. To be honest with you we shouldn't even have this 
![Screen Shot 2019-08-13 at 10 37 14 AM](https://user-images.githubusercontent.com/8395482/62951097-54bf5180-bdb7-11e9-97f5-a4e2b821249c.png) on the new sites, if we go with the reduced version of the Cornell logo.
When we started doing mockups for the new ULS, we did explorations of the logo and presented this to LEG and the mock-ups presented were accepted, so we moved on. So if we follow the Cornell guidelines we should really follow and not round the lock-up to 50px.

**Comment by kevinkidwell** [comment]
Let's see what the Cornell brand says about being either academic or non-academic. I'd like to do it so we are meeting the proper Cornell guidelines since we're using their logo. 

If we're treated as academic, then I think any logo between 45px and 73px would be the reduced seal, since it says "at least 45px tall" with the guidelines, so we could determine our sizing in there. If we're non-academic then we should explore the simple seal and how we can do it in that fashion on the site.

I think tying this in with our print presence would help with a more unified library cohesive brand. That would mean using Cornell University Library in Montserrat, since that is what print branding uses. And then adding whichever seal is required based on our status with that in the appropriate layout.

**Comment by mhk33** [comment]
Manolo developed the current branding (with Montserrat) a few years ago. I don't know if there have been further discussions about updating the branding within Zsuzsa's group. I got the sense that a branding update was on the back-burner. This was my impression based on a few months ago, though. I wonder if Mary Beth knows what the status of branding is as far as Communications' involvement. Or does Sara know?

I always thought Carla was using Helvetica for print, or something like Helvetica. Seemed a bit different than Montserrat.

**Comment by manolobevia** [comment]
Zsuzsa's group believes we can have a print and a digital version of CUL logo, which it breaks the first rule in branding, consistency. This is the logo used for all print materials and some websites. 

![Screen Shot 2019-08-13 at 11 23 04 AM](https://user-images.githubusercontent.com/8395482/62957295-84c02200-bdc2-11e9-991b-160711de9253.png)

**Comment by manolobevia** [comment]
![Screen Shot 2019-08-13 at 11 20 11 AM](https://user-images.githubusercontent.com/8395482/62957319-9275a780-bdc2-11e9-9299-6f7a1f81b43b.png)

So we have CU branding and CUL current logo identity, which in the past years we have been following. I thought the same as Melissa's comment.

**Comment by JesiBuell79** [comment]
Closing
