### ISSUE TITLE
ULS UNITS - Branding - CUL Navigation

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#412]
We have had feedback from multiple stakeholders about the navigation consisting of All Libraries, Hours, and Ask a Librarian. All of the feedback said that they found this navigation confusing and did not understand why it takes precedence over the Unit site they are on. Some stakeholders also wondered why the first thing users are asked to do on a site is to leave the unit and go back to the main library page.

This will be a place for user testing to be done on Fine Arts, performed by the Usability Working Group, within the next month.

In the meantime, we should give less weight to “All Libraries” by making it the same font size as Hours and Ask a Librarian, removing the bold, and removing all caps.

**Comment by manolobevia** [comment]
We had usability testing for VET, I think you did for PSL and hotel too. We presented this navigation to stakeholders. I demo this internally. Vet, hotel, law, fine arts, psl didn't say anything about this. 

You said you had feedback from multiple stakeholders. Can you please tell me how many stakeholders?

**Comment by kevinkidwell** [comment]
Vet, PSL, and Hotel usability testing were the old theme where these were not as prominent. In our initial meetings when we showed the new theme, every unit mentioned it. As we've continued to have meetings while migrating content and getting sites more finalized, it's something that has come up with each one.

**Comment by manolobevia** [comment]
I have noticed that `All Libraries` takes you to cul homepage, and it should take you to `https://www.library.cornell.edu/libraries` as a shortcut to all the library listing. That was the original intention.

**Comment by manolobevia** [comment]
I disagree. The new theme is less prominent, you can see this below. 
Whoa! All the stakeholders. 

![Artboard](https://user-images.githubusercontent.com/8395482/62960423-9d333b00-bdc8-11e9-9d70-0b83c980b585.png)

**Comment by manolobevia** [comment]
Thanks for adding the meeting notes to the WIKI. I don't see this issue on Management or Law notes.
