### ISSUE TITLE
ULS UNITS MANAGEMENT - Add group display results funtionality

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#419]
From Rachel:

Can search results be separated out by type?  Databases listed first, FAQs second, Guides, then everything else. Also can there be some visual cue or separation of the results? (example from our current site) Along the same lines, is there a system for ranking results?  Our current system is set up to offer specific results before others (example from searching Mergent).

**Comment by manolobevia** [comment]
@kevinkidwell is this something management still wants? I have no clue how to do this.

**Comment by kevinkidwell** [comment]
@manolobevia I think we're going to end up doing some user testing to see if this is something actually useful for their users. I've also put in place to show the post type (database or faq) on each search result so they have something there for the moment.

We can put this on hold for now and see what the user testing shows.

**Comment by manolobevia** [comment]
@kevinkidwell sounds good.

**Comment by manolobevia** [comment]
will reopen it need it.
