### ISSUE TITLE
ULS UNIT ENGINEERING - Site Launch.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#421]
Migration: Completed
Launch day: November 11th
Current site: https://dashboard.pantheon.io/sites/502f4691-a840-4529-92d8-5bc7584de885#dev/code
New Site: https://dashboard.pantheon.io/sites/3c2da129-503e-43f4-af22-2a520a8607e2#dev/code
Domain: https://engineering.library.cornell.edu/
Redirects: No
Initialize test and live environments: Pending
Enable search Engine Visibility

**Comment by kevinkidwell** [comment]
@manolobevia @jgreidy @gdelisle Migration has been completed and this site is good to go. We just got confirmation that they are willing to go live on November 11.
