### ISSUE TITLE
ULS UNITS AFRICANA -Site launch.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#427]
Migration: Final items in progress
Launch day: Nov 4 or Nov 11
Current site: https://dashboard.pantheon.io/sites/8c0aa5c2-590f-4bbb-a11c-66665a4848c3
New Site: https://dashboard.pantheon.io/sites/c31b251f-f096-4f51-b1fe-e5dd1f7d888b
Domain: africana.library.cornell.edu
Redirects: No
Initialize test and live environments: 
Enable search Engine Visibility

**Comment by kevinkidwell** [comment]
@manolobevia @gdelisle Africana is ready to launch whenever you think is best. We have a few items left to migrate but they are for content that isn't going to be publicly accessible so it can go after launch.

**Comment by gdelisle** [comment]
Africana went live last week. Can this issue be closed, and/or do we need a new one for deleting the old site from Pantheon?
