### ISSUE TITLE
ULS UNITS MATH - Site launch.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#428]
Migration: Completed
Launch day: November 11
Current site: https://dashboard.pantheon.io/sites/f34ce3c3-f21e-48bc-b997-6e45dfe34ec1#dev/code
New Site: https://dashboard.pantheon.io/sites/430a238b-b9f9-4244-81f7-d47d8ef92a32#dev/code
Domain: mathematics.library.cornell.edu
Redirects: No
Initialize test and live environments:
Enable search Engine Visibility

**Comment by kevinkidwell** [comment]
@manolobevia @jgreidy @gdelisle Migration has been completed and this site is good to go. We just got confirmation that they are willing to go live on November 11.
