### ISSUE TITLE
ULS UNITS theme accessibility review

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#43]

**Comment by manolobevia** [comment]
We will focus on Vet, Hotel, and PSL. Once the Units theme is created we will have to create an issue for accessibility review.

**Comment by manolobevia** [comment]
The units theme won't be part of this backlog. I will move it to `New issues` pipeline.

**Comment by manolobevia** [comment]
CIT is reviewing the theme. #154 will take care of accessibility changes provided by CIT report.

**Comment by manolobevia** [comment]
#152 not #154
