### ISSUE TITLE
ULS UNITS MANAGEMENT - Default site search to site content instead of catalog.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#468]

**Comment by manolobevia** [comment]
I finally finished this issue. The problem is that in a child theme, I need to use get_stylesheet_directory_uri() instead of get_template_directory_uri(), so I am able to set up the default search functionality (search.js)

**Comment by kevinkidwell** [comment]
@manolobevia We were just asked about this issue by Management because their search is still defaulting to Catalog instead of Site. Is there a setting somewhere to be able to adjust this?

**Comment by manolobevia** [comment]
@kevinkidwell I fixed this issue, but I see it went back to default the catalog. I need to see what happened.

**Comment by manolobevia** [comment]
@kevinkidwell now site search defaults. Ignore the lack of spacing on the radio buttons, next upstream will take care of this.
