### ISSUE TITLE
ULS UNITS PSL - One-Click Auth not working

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#473]
Whenever I try to do one-click login for PSL, it says "The application you have accessed is not registered for use with this service." Since we are going to require all content editors to login this way, can we get this fixed by Sep. 25th for the first content editor training?

**Comment by jgreidy** [comment]
I added the certs and
Requested Shibboleth integration here: https://shibrequest.cit.cornell.edu/shibrequest/cornell/main.html

**Comment by jgreidy** [comment]
Identity Management has finished integrating the site. Login works.
