### ISSUE TITLE
ULS Upstream - errors redeclare of json_encode

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#474]
When multiple copies of httpguzzle/guzzle are loaded, Pantheon sites complain of a redeclare of json_encode(). 
![Screen Shot 2019-09-11 at 11 59 18 AM](https://user-images.githubusercontent.com/5996967/64713889-af69cd00-d48b-11e9-838c-8ec0b3a3cde3.png)

**Comment by jgreidy** [comment]
Issue for guzzle: https://github.com/guzzle/guzzle/issues/2135

**Comment by manolobevia** [comment]
PHP Error Log
No PHP errors to report.
