### ISSUE TITLE
ULS UNITS LAW - Add html markup and styles to the body content of the 2 timelines

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#477]
Review all the body content and add styles and links, since exporting from Drupal views into Json  the markup and style are lost. Just about 240 slides to review.

**Comment by manolobevia** [comment]
@kevinkidwell When I migrated the timeline to JSON using a drupal module, this didn't export HTML markup for the timeline slides.

Can one of your students add the missing markup to the slides?

Here go the links for the WP timelines: 
https://dev-uls-law-library-cornell-edu.pantheonsite.io/timeline/
https://dev-uls-law-library-cornell-edu.pantheonsite.io/clinical-trials/

Drupal Timeline

![Screen Shot 2019-10-02 at 4 41 22 PM](https://user-images.githubusercontent.com/8395482/66080311-d881f880-e533-11e9-9faf-1e6c1527bd9a.png)

WP timeline

![Screen Shot 2019-10-02 at 4 42 44 PM](https://user-images.githubusercontent.com/8395482/66080326-e0419d00-e533-11e9-94aa-c7e2f6f2d37b.png)

Can you see the missing link for the slide description?

Thanks.

**Comment by kevinkidwell** [comment]
We can have the students go back through and look at adding that in. After meeting with Law, this is something that can be held off until after launch, they're not worried about having it to go live with everything else that still needs done.

**Comment by manolobevia** [comment]
Closing this one, since we will be using a plugin for timelines.
