### ISSUE TITLE
Old Pantheon instances to remove

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#478]
- Fine Arts (https://dashboard.pantheon.io/sites/c0ff3a54-2615-4a78-86f6-0b9c04b3bf22#dev/code)
- PSL (https://dashboard.pantheon.io/sites/343a4de1-6b88-462a-bd06-56b78ded4cce#dev/code)
- Hotel (https://dashboard.pantheon.io/sites/378b1497-8299-42b1-94d3-bd67abdbae89#dev/code)
- Vet (https://dashboard.pantheon.io/sites/26f1d206-7b0c-469e-b9fb-a5565ae6dda8#dev/code)
- Annex (https://dashboard.pantheon.io/sites/f23e3c0a-aeb0-43c1-a6b8-e4a485248d78#dev/code)

**Comment by jgreidy** [comment]
Vet is Greg, the rest are mine.

**Comment by gdelisle** [comment]
I just deleted Vet and it appears that Jim has already deleted his, so this is done.
