### ISSUE TITLE
ULS UNITS LAW - /admin redirect to /staff_web/administration/

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#482]
Let's keep `/admin` for accessing the dashboard, so we are consistent with all the uls sites.

**Comment by kevinkidwell** [comment]
This has been fixed. It did the same thing as the ILR Workplace Issues Today article where it found the word admin in the slug and automatically did a redirect. Is there some kind of setting we can do to keep that from happening?

**Comment by manolobevia** [comment]
@kevinkidwell so any slug with the word `admin` will redirect to `/admin`? Thanks
