### ISSUE TITLE
Main CUL accessibility: fix "#class" in ares module

### ISSUE THREAD

**Issue by mhk33** [cul-it/uls#492]
The course reserves search block has "#class" instead of "class". This appear to be in the drupal7search branch:
https://github.com/cul-it/ares-module/blob/drupal7search/ares.module#L433

**Comment by mhk33** [comment]
Assigned to @jgreidy to fix "#class", and look at how the Ares git and site modules have diverged.

**Comment by jgreidy** [comment]
Happy to say that the ares module on www matches the ares-module github repo I will put the fix in ares-module in github, then update www.

**Comment by jgreidy** [comment]
-    ‘#attributes’ => array(‘#class’ => ‘go’)
+    ‘#attributes’ => array(‘class’ => array(‘go’)),
Made this change to the ares module repo in github and also to www.library.cornell.edu
