### ISSUE TITLE
ULS UNITS - Make library hours plugin accessible.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#499]
Mostly contrast issues and html/css validation.
Also, the plugin uses bootstrap so any reference to this has to be removed.

**Comment by kevinkidwell** [comment]
I noticed this with the contrast issue a little while back and played with some CSS to fix those. If you wanted to use this styling, I'm including the code below:

`.s-lc-whw-head-date {
	color: #000 !important;
}
.s-lc-whw-today, .s-lc-whw-today-h, .s-lc-whw-today-h .s-lc-whw-head-date {
	background-color: #5b5b5b !important;
	color: #fff !important;
}
.hours-weekly__all-cul {
	text-align: right;
	float: right;
	margin-bottom: 10px;
}
.hours-weekly__nav {
	float: left;
	margin-bottom: 10px;
}
.hours-weekly__nav button {
	background-color: #fff;
	padding-bottom: 7px;
}
.hours-weekly__nav button:hover {
	background-color: #017db2;
	color: #fff;
	cursor: pointer;
}`

**Comment by manolobevia** [comment]
Thanks. I will.

**Comment by manolobevia** [comment]
@jgreidy Next upstream needs to get the latest from this plugin. Thanks.

**Comment by manolobevia** [comment]
For the library monthly hours, I need to add scope attributes to TH tags. The monthly hours are generated on the fly, and I am not sure if I can re-read the DOM for adding scope attributes.
