### ISSUE TITLE
Roadmap & Development Plan

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#5]
Roadmap of our plan for what we are doing to share with stakeholders. This would be a good place to create a timeline for when various sites will be worked on and the process that we will go through to keep it transparent.
- Requested at Stakeholders Discussion meeting 10/16/18

**Comment by ajs17** [comment]
Adam started a document in the wiki and handed off to Mary Beth to complete.

**Comment by kevinkidwell** [comment]
Updated document is on the Wiki and at https://cornell.box.com/s/pb4a8xaf8cy4i664au7x4lcccurar2be
