### ISSUE TITLE
ULS PLUGIN - Ares - Style table when course is selected

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#511]
We noticed that the styles for the Ares plugin, specifically the table that appears when a user selects a course from the dropdown, doesn't match the styling of the rest of the sites. It would probably be good to match this to the Full Hours table styling so that we are consistent on tables across the sites.

Here is a screenshot from https://dev-uls-law-library-cornell-edu.pantheonsite.io/current-course-reserves/
![Screen Shot 2019-10-04 at 8.08.42 AM.png](https://images.zenhubusercontent.com/597756e361b4ca3b0a759cb1/44647fe4-89c1-42ea-bec4-426464fc0299)

@manolobevia Let me know if you want me to get in and style this in the Ares plugin or if you'd like to do it.

**Comment by manolobevia** [comment]
@kevinkidwell I can do it. Unless you really want it to do it.

**Comment by manolobevia** [comment]
@kevinkidwell I am working on making the plugin accessible and styles.
