### ISSUE TITLE
ULS PLUGIN - Ares - Check table for accessibility

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#512]
I don't think SiteImprove catches the table since it's created after a selection from the dropdown. I'm not able to tab through this table so we probably need to manually check this accessibility and see what fixes we need to make.

**Comment by manolobevia** [comment]
I am not sure if you are able to tab on the tables. 
@kevinkidwell  @mhk33 
Check these samples:
`https://webaim.org/articles/jaws/tables.htm`
`https://accessibility.psu.edu/tableshtml/`
They supposed to be accessible, but as you can see you can't tab. I think each screen reader have their own key combinations for navigating through a table. I have also applied scope attributes. I am not sure what to do for tabbing, and I haven't found any samples. Any help?
