### ISSUE TITLE
ULS UNITS - Add Faculty Bio link to Staff Profiles

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#514]
Law needs to have a link to their Faculty Bios on their staff profiles. I talked to Dan about this. We should make it a `URL field` with a label of `Faculty Bio` which should be linked with that URL. This link should have the aria-label of `<Staff name> Faculty Bio` so that each link will be unique even with the same linked text. I think this could go right above the ORCID/LinkedIn in placement on the staff card, if that seems like a good place for you.

Let me know if this is possible and when this may get in so I can pass that on to Law.

**Comment by manolobevia** [comment]
@kevinkidwell sounds good. We are planning to do a push for CULU tomorrow. I will add this feature for tomorrow's push.
