### ISSUE TITLE
ULS UNITS - Create Elementor widget for custom post type loops

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#515]
This is needed because Custom Post Type loops break Elementor editor. This is something that happens when editing a page where there is a shortcode that was custom created as a loop for Custom Post Types. The reason this breaks is because shortcodes should only use `return` to get all of the content. Shortcodes are defined in the Snippets plugin based on each unit's particular custom post types and display needs.

The fix to this is to create an Elementor widget (https://developers.elementor.com/creating-a-new-widget/). I currently do not have time to do this but would like to do it myself when time frees up. Thought process for doing this:
- Create a widget that has all of the loops in a single widget
- Allow a textbox (or select menu) for custom post types on each unit, with that unit name attached somehow
- Name each section by unit so that we can differentiate between types such as databases that are the same name for multiple units but different displays

**Comment by manolobevia** [comment]
Moved to: https://github.com/cul-it/uls/issues/654
