### ISSUE TITLE
ULS UNITS - Math - Ultimate CSV Importer - Export Error

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#520]
@manolobevia I keep running into an issue when trying to exported the Collected Works of Mathematicians (collected_works) from the Math dev site. I need to be able to export these so that I can add in some tags and then re-import to update.

The error that keeps happening is that it will go through the export process but when I click on Download, it gives me an .html file and says Failed - No File. Any ideas of how to fix this or should we reach out to their support?

**Comment by jgreidy** [comment]
Note: the site can't make temp files when it's in Development Mode Git. (This is assuming you're doing the export from the development site.) Try switching the SFTP mode.

**Comment by kevinkidwell** [comment]
@jgreidy I tried switching it to SFTP and exporting but it is still giving the same error.

**Comment by manolobevia** [comment]
The only thing I could think is using an older version of the import/export plugin or contact support.

**Comment by kevinkidwell** [comment]
I don't know what's happening with it but I added WP All Export and was able to get it that way and then import using our plugin. Since this isn't something we should need to do often at all, I'm not that worried about it and we can see if a future update fixes anything.
