### ISSUE TITLE
Add SiteImprove Wordpress Plugin to Upstream

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#527]
We found that SiteImprove has a WP plugin that works well for making the content editors/creators/etc. to be able to check this themselves within their site. Can we get this added to the upstream so it's available on all the sites?

Here is the URL to be able to download the plugin: https://siteimprove.com/en-us/core-platform/integrations/cms-plugin/wordpress/

**Comment by manolobevia** [comment]
@kevinkidwell yeah!!! I was planning to add this plugin.

**Comment by jgreidy** [comment]
added to upstream v1.2.24
