### ISSUE TITLE
ULS Units - Manual Review Report Links

### ISSUE THREAD

**Issue by mbmartini** [cul-it/uls#534]
Main Site
https://docs.google.com/spreadsheets/d/1LHVahwNcawzTu9E7emf21h4hYs-IFyjaEuw_DMWIiiY/edit?usp=sharing

Mann
https://docs.google.com/spreadsheets/d/10v6id3J5eCmRdErFvI6I1gFrTx07opZpu60OaLEqI5Q/edit?usp=sharing

Fine Arts
https://docs.google.com/spreadsheets/d/1mBD8Lzusrbf-d0NulfM_pY8tnyD6suml9Nadtzob01g/edit#gid=776733708

Makerspace
https://docs.google.com/spreadsheets/d/11T2HjI1Zh97e2OnnfWI5a_II1wuvENiyu7sV9qGyU9g/edit?usp=sharing

Annex
https://docs.google.com/spreadsheets/d/1kziK9nEyibFL5L9-OH6v-NuXhZXgyZKSia8cuBjnurI/edit?usp=sharing

Asia
https://docs.google.com/spreadsheets/d/18vSvR7qiF5Iu5FwvwHYWgvNmpa69eiIeJXKm3wZy3b0/edit?usp=sharing

Management
https://docs.google.com/spreadsheets/d/1hrpTWCfLgl6hvvDwJltdhyMXbSLQoodZylKZChM1OGE/edit?usp=sharing

Alumni
https://docs.google.com/spreadsheets/d/1hcWOTNzgP4QywQlBOcBiOmn1pKL9Bmogu5Vchui2MVg/edit#gid=776733708

**Comment by mbmartini** [comment]
Hot off the press, these just in from CIT:

Africana checklist: https://docs.google.com/spreadsheets/d/1Lna_ggdPSmoHZEd9R6Mz1egqMju_U0sneUwqvigf9U8/edit?usp=sharing

Only a few issues left. "skip to main content" link doesn't work on some pages and a developer might be required to fix a few more issues like adding "aria-labelledby" to some links. On the content side, only a few images need their alt text corrected and a few links need some attention from a site manager.

Math checklist: https://docs.google.com/spreadsheets/d/1-jH1pBQLRqELJtYhsPytAln3fBnAUlyZnwIFmpp7glA/edit?usp=sharing

Site is pretty clean. a few issues left. On the developer side, there's a select box that needs a label and some page landmarks require additional labelling. On the content side, some pages still have repeated links. On the other hand, Siteimprove flagged a few false positive issues that maybe needs to be cleared.

Music checklist: https://docs.google.com/spreadsheets/d/1VPmztaeQ1JNFx6OCwVHvuTWCj1w68vaiIyK7C8-TG_8/edit?usp=sharing

Site has a few more issues than the other ones. Most of these issues are developer related and are related to incorrect use of Aria attributes. there is also one color contrast issue and an ID naming issue as well. On the content side, there's pretty much nothing to fix there.

**Comment by mbmartini** [comment]
These just in:

Olin & Uris checklist: https://docs.google.com/spreadsheets/d/1GstwRgme_k9PrOqjmXioAF8peIbaLtXm5U4nII7n7Eo/edit?usp=sharing

Engineering Library: https://docs.google.com/spreadsheets/d/1DM7pGKY2YcXEOQ4W1IdDOuDxcUBVL3BN9S0k-GVNB_U/edit?usp=sharing

Clark Physical Sciences: https://docs.google.com/spreadsheets/d/1lF8M3u57z6QyBb6hf0fLWBD0v5MnxuuRWv_2S-pxcZY/edit?usp=sharing

Overall the three sites seem very clean. there's still a few issues left. There are two dropbox elements that need labels and some buttons on the side menu of the homepage carousel that don't receive focus.

**Comment by mbmartini** [comment]
The last manual reviews are in:

Law: https://docs.google.com/spreadsheets/d/1ynMM22FIaaC27Il57IGhZOdRXXCuXeRMmggk6X800Yw/edit?usp=sharing
ILR: https://docs.google.com/spreadsheets/d/10FTiENgbLsRnokpvkQ5nmq_a0y8rsvvOPAr0N-Uy8SY/edit?usp=sharing
Management: https://docs.google.com/spreadsheets/d/1qPzPCbUiP8onk8ury7Rfi9M2bxMIJ75UQLU8H8LDdf0/edit?usp=sharing
Rare & Manuscript: https://docs.google.com/spreadsheets/d/1KKVfIptMhwiD67nhgYOpgzrFDqex5M-HMsJ5GGqr9sU/edit?usp=sharing

Overall all of these sites are pretty clean. They still have a few minor theme and content issues. like heading missing text, HTML used to format tables. Also, they're a few issues require a web developer to solve. like removing alt text from social media icons in the footer, removing duplicate ID names for some elements, Aria and other landmark issues.

**Comment by manolobevia** [comment]
@kevinkidwell Fixing the ones that involves the CULU theme.
