### ISSUE TITLE
ULS UNITS MATH - Collected works select box label

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#539]
- Select box element must have a label.
https://dev-uls-mathematics-library-cornell-edu.pantheonsite.io/collected-works/

**Comment by kevinkidwell** [comment]
@manolobevia I'm not sure of the best way to fix this one because it's an issue with FacetWP. These select boxes are being brought in by their shortcode. We could write some jQuery to add in the label but it might also be conducive to reach out to their support to see if they can add it in at the core plugin level.

**Comment by manolobevia** [comment]
Probably best way is to fix it with JS for now.

**Comment by kevinkidwell** [comment]
I was able to fix this using Filters for the HTML that FacetWP has in their hooks. We'll have to add those to any unit that uses them. I'll add this to the list to look over the end of this week.
