### ISSUE TITLE
ULS UNITS - Change Faculty Bio to Professional Biography

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#564]
@manolobevia We heard from Dan/Law about the faculty bio link and they were wondering if we could change the link wording from Faculty Bio to Professional Biography? This wording would probably work better if other units also wanted to use this.

**Comment by manolobevia** [comment]
If I change to `Professional Biography`, all units will have this new label.

**Comment by kevinkidwell** [comment]
I think that's fine. Law is the only one currently using this field but I think Professional Biography will work better as an overall label for all the units.

**Comment by manolobevia** [comment]
@kevinkidwell If I change the custom field from faculty_bio to professional_biography, the data will be lost, so I have just changed the link label to `Professional Biography`.
