### ISSUE TITLE
ULS UNITS - Add visual consistency to side bar navs.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#567]
![Screen Shot 2019-10-25 at 10.54.26 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/2318a4a3-3790-4442-8e17-0f830c2db5c3)![Screen Shot 2019-10-25 at 3.07.42 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/fd26b410-bed0-4563-8d36-29959ba9737b)

**Comment by kevinkidwell** [comment]
We should make sure that the fonts are the same but the background and background headline colors should be able to be chosen by the unit as part of their customizations of their page views.

**Comment by kevinkidwell** [comment]
I just went through and verified that these are matching across units that have this type of display block on their pages.
