### ISSUE TITLE
ULS UNITS CULU - Libcal plugin navigation

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#572]
![Screen Shot 2019-10-29 at 3.06.24 PM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/c148c861-74cc-4838-9a70-8500676e799b)

Finearts display the nav for going forward and backward days and the current day, but I don't see this in other sites. @kevinkidwell Do you know why this is happening? I have no clue.

**Comment by manolobevia** [comment]
I think I found out was going on. If I use the hour's template, the nav doesn't display.
If I use a default template, and I add the shortcode, we can see the nav displays.

**Comment by kevinkidwell** [comment]
I was going to say something similar! It looked like the Fine Arts is using the weekly shortcode which was why it was displaying.

**Comment by manolobevia** [comment]
But the hours template uses also the same shortcode. It is weird.

**Comment by manolobevia** [comment]
I am going to use an elementor default template and add the shortcode on the template for all sites.
