### ISSUE TITLE
ULS UNITS - Change Catalog to Library Resources

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#576]
We recently completed the polling of students for the language under the Search bar on the home page. The majority chose to replace Catalog with Library Resources. The link will stay the same as it currently is, just the label text should change. Below is an image for reference:

![ULS_Poll_LibraryResources](https://user-images.githubusercontent.com/29164102/68142860-3a040100-fefe-11e9-8003-7038a01742d2.jpg)

**Comment by manolobevia** [comment]
@manolobevia change management too, since it doesn't use CULU search markup.
