### ISSUE TITLE
ULD UNITS - Create new upstream 1.2.27. CULU updates and plugins (if we need updates).

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#588]

**Comment by jgreidy** [comment]
Built upstream v1.2.27

- CULU theme v1.0.25 updates - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
- custom-post-type-ui update - 1.7.1 - see [CHANGES](https://github.com/WebDevStudios/custom-post-type-ui/)
- wp-saml-auth - 0.7.3 - see [CHANGES](https://wordpress.org/plugins/wp-saml-auth/#developers)
