### ISSUE TITLE
ULS UNITS - Add a dash after "Closed" language in header hours when a unit is closed

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#589]
Right now the language in the header when a unit is closed reads like this screenshot:

![Screen Shot 2019-11-07 at 10 18 52 AM](https://user-images.githubusercontent.com/29164102/68401617-10d6b100-0148-11ea-95f5-c688cf6fb2ea.png)

It would be good to add a dash after "Closed" to have a little more space and so it's more legible for users, something like this:

![Screen Shot 2019-11-07 at 10 20 18 AM](https://user-images.githubusercontent.com/29164102/68401726-3bc10500-0148-11ea-9ea6-3ac523a4524a.png)

**Comment by manolobevia** [comment]
I had that in my mind for a long time.

**Comment by kevinkidwell** [comment]
This has been added to the plugin's Github repo on the dev branch and is ready to go/be included in the next upstream.

**Comment by manolobevia** [comment]
@kevinkidwell can you merge into master? Thanks.

**Comment by kevinkidwell** [comment]
@manolobevia Done!

**Comment by manolobevia** [comment]
@kevinkidwell THANKS!!!
