### ISSUE TITLE
ULS UNITS - Compiled list of launch dates

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#590]
This is a list of the proposed launch dates for unit sites that are currently in dev. Units with a * are dependent upon the New Books feed being fixed to launch. If the feed isn't fixed, the dates will be pushed back until it is.

November 11: Engineering and Math
November 18: Music*
December 2: Rare
December 9: Law*
December 16: ILR* and Management*

**Comment by gdelisle** [comment]
This is awesome. Thanks!
