### ISSUE TITLE
ULS UNITS - Course reserves plugin throwing error

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#602]
I wasn't sure who would be best for this. It looks like the course reserves WP plugin is throwing an error and generally not loading any of the items for us (at least on Music).

Here is the error:
<img width="413" alt="Screen Shot 2019-11-14 at 10 32 48 AM" src="https://user-images.githubusercontent.com/29164102/68871298-345ea600-06ca-11ea-9067-e4717f945b99.png">

**Comment by manolobevia** [comment]
This is working now, and faster that before. Probably the service was down. Closing since  I can't replicate.

**Comment by manolobevia** [comment]
Actually it is slow, like before.

**Comment by kevinkidwell** [comment]
I'm still getting the error. Steps to replicate:

1. Go to https://dev-uls-music-library-cornell-edu.pantheonsite.io/course-reserves/
2. Select Music 1341
3. Open console and see error

**Comment by manolobevia** [comment]
I see the issue. @ajs17 can you take a look?

**Comment by sew268** [comment]
@ajs17 any progress on the Course Reserves Plugin?  As we start to launch sites for units that have larger amounts of books on course reserves, the slowness/inability to load is going to be a real problem.  Thanks!
