### ISSUE TITLE
ULS UNITS RARE - Visual review and accessibility changes.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#604]
Manual review:
`https://docs.google.com/spreadsheets/d/1KKVfIptMhwiD67nhgYOpgzrFDqex5M-HMsJ5GGqr9sU/edit?usp=sharing`

- [x]  Disable elementor default colors and fonts

**Comment by kevinkidwell** [comment]
@manolobevia I wanted to get your opinion on this page: https://dev-uls-rare-library-cornell-edu.pantheonsite.io/digital-collections/

If you hover over the images in the "Featured Collections" section, it looks like an effect has been added. To you, does this break the general styling of the site? I have to send them an email about a few accessibility things that need fixed so want to include this in there if needed.

**Comment by manolobevia** [comment]
@kevinkidwell to be honest with you it doesn't add any value. I can go either way. I wonder if this bring some accessibility issues as you mentioned.
