### ISSUE TITLE
ULR UNITS LAW - ID and landmark issues on several pages

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#611]
FROM CIT

- Element ID is not unique. See SI for detials
https://dev-uls-law-library-cornell-edu.pantheonsite.io/law-library-maps/
- Landmarks with identical names. <section> element. See SI for details. 
for example: https://dev-uls-law-library-cornell-edu.pantheonsite.io/special-collections-2/
- Non-distinguishable landmarks. See SI

COntact CIT for clarification.

**Comment by kevinkidwell** [comment]
Element IDs have been fixed. Students are working on landmarks.
