### ISSUE TITLE
ULS UNITS -Explore libcal API for read/write data for Equipment.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#620]

**Comment by kevinkidwell** [comment]
I think it would be good to go ahead and explore these but I’d suggest we not get into implementing anything just yet. We just set up a meeting with Mann to figure out all of the requirements in December and see what might be the best way to go about starting to implement this. We’ll make sure you’re on that meeting invite!

**Comment by JesiBuell79** [comment]
Closing - we are handling differently
