### ISSUE TITLE
ULS UNITS ILR - Add email validation to WIT email form.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#629]
`https://dev-uls-ilr-library-cornell-edu.pantheonsite.io/workplace-issues-today/`
I think, we should add some anti spamming tool for this email subscription form.

**Comment by kevinkidwell** [comment]
This form utilizes Mailgun's plugin to be able to create that form. We'd have to find a way to edit the plugin code to add validation. At least on Mailgun's end, if it's not a valid email address it doesn't add it to the mailing list. If we can figure out a way to do that or can use another form plugin to create the form and get it to use the hooks into mailgun then we can look into that.

**Comment by JesiBuell79** [comment]
Closing
