### ISSUE TITLE
Upstream v1.2.33 requests

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#634]
Current changes:

- advanced-access-manager - update 6.0.5 - see [Release Notes](https://wordpress.org/plugins/advanced-access-manager/#developers)
- All-in-One WP Migration - Update to 7.11 - see [Release Changelog](https://wordpress.org/plugins/all-in-one-wp-migration/#developers)
- wp-saml-auth - update 0.8.1 - see [CHANGES](https://wordpress.org/plugins/wp-saml-auth/#developers)
- simplesamlphp - update 1.18.2 - see [Change Log](https://simplesamlphp.org/docs/1.18/simplesamlphp-changelog#section_1)

**Comment by jgreidy** [comment]
Manolo has CULU and ARES plugin changes to contribute before release.

**Comment by jgreidy** [comment]
Kevin has some updates for libcal-hours plugin.

**Comment by manolobevia** [comment]
I am done with my updates on culu.

**Comment by jgreidy** [comment]
Additional updates:

- CULU Theme updates - 1.0.28 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
- wp-libcal-hours - update - 1.0.9 - [Changelog](https://github.com/cul-it/wp-libcal-hours/blob/dev/CHANGELOG.md)
- json-content-importer - update 1.3.6 - see [changelog](https://wordpress.org/plugins/json-content-importer/#developers)
- ares_wordpress - update 1.0.5 - see [Changelog](https://github.com/cul-it/ares_wordpress/blob/master/CHANGELOG.md)

Note: some of our changelogs are one release behind the current release version.

**Comment by jgreidy** [comment]
This version is missing some CULU theme changes.
