### ISSUE TITLE
ULS UNITS MATH - Fix broken links 

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#647]
Here goes a list of broken links:

- The twitter icon on the footer.

- https://my2.siteimprove.com/QualityAssurance/Inspector/899880/29619583726/PageDetails/Report?impmd=5696CF9FFF459299E49DBBA948A717FE&Hash=%2FIssue%2FBrokenLinks

- https://my2.siteimprove.com/QualityAssurance/Inspector/899880/25724532967/PageDetails/Report?impmd=5696CF9FFF459299E49DBBA948A717FE&Hash=%2FIssue%2FBrokenLinks

- https://my2.siteimprove.com/QualityAssurance/Inspector/899880/29619580524/PageDetails/Report?impmd=5696CF9FFF459299E49DBBA948A717FE&Hash=%2FIssue%2FBrokenLinks

- https://my2.siteimprove.com/QualityAssurance/Inspector/899880/29619584024/PageDetails/Report?impmd=5696CF9FFF459299E49DBBA948A717FE&Hash=%2FIssue%2FBrokenLinks

- https://my2.siteimprove.com/QualityAssurance/Inspector/899880/29619587127/PageDetails/Report?impmd=5696CF9FFF459299E49DBBA948A717FE&Hash=%2FIssue%2FBrokenLinks

**Comment by kevinkidwell** [comment]
@manolobevia I have passed these on to the stakeholder to fix most of the links. I also just wanted to point out that you're looking at the Dev site in SiteImprove instead of the Live site, but all of the errors are still the same.

**Comment by manolobevia** [comment]
@kevinkidwell Thanks. I know. If I work on a specific site, I migrate files/db to test and dev all the time.  I need to ask CIT to give me access to all live sites.

**Comment by manolobevia** [comment]
Verified links.
