### ISSUE TITLE
ULS UNITS: Custom Loop Elementor Widget

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#654]
**Components**: 
UI design/thoughts, widget creation, GitHub Repo.  Potential hinderances: remove all custom loops and reimplement.  

**Units**:
Management, PSL, Africana, Law, ILR, Engineering, Math, Rare, Asia, Mann and Olin/Uris are unknown but likely need

**Effort**:
Medium-Large

**Comment by manolobevia** [comment]
From Nick:
Kevin – For the custom loop Elementor widget, I may be missing something, but with my limited experience with Elementor, as long as you ensure your shortcode returns a value (and does not simply echo), their included Shortcode Widget has served me well. Again, I realize I don't have the full context and details, so this may not apply at all =)

**Comment by manolobevia** [comment]
I think we have two completely different issues here:

1- If you go to the Africana site and edit the thesis page in admin, you get:

<img width="377" alt="thumbnail_1" src="https://user-images.githubusercontent.com/8395482/71108644-87c48800-2191-11ea-9a0b-7d3eafbf1400.png">

This is the solution I was mentioning during the meeting, just add to the template the_content() function. This is a regular page that should be using page.php.

2- if in your browser you open the thesis page, then at the bottom click on edit. After that, you should see a WP admin page for editing thesis, but you are not editing the thesis page. You'll see you are editing a thesis post( https://dev-uls-africana-library-cornell-edu.pantheonsite.io/wp/wp-admin/post.php?post=895&action=edit )

What happens here is that you are using wp_query and the edit button is editing the last post type thesis in Elementor, which makes sense. You go through all the posts and "edit" will edit the last post. That's a problem.

Then when you click on elementor, you will get:

<img width="403" alt="thumbnail_2" src="https://user-images.githubusercontent.com/8395482/71108669-96ab3a80-2191-11ea-934f-0372291a1a29.png">


(I am not sure about this part) So elementor is asked to edit a single post type thesis, which it hasn't been defined as elementor single post. https://docs.elementor.com/article/354-creating-a-single-post-template-with-elementor-pro

I think what you are trying to accomplish is to have an elementor page (ex: thesis), where you add all kind all content, but also a widget which contains a custom loop, and able to edit the page. Which for that, you can use a shortcode, like you are using.

Let me know if it make sense.

**Comment by manolobevia** [comment]
From Kevin:
This is needed because Custom Post Type loops break Elementor editor. This is something that happens when editing a page where there is a shortcode that was custom created as a loop for Custom Post Types. The reason this breaks is because shortcodes should only use return to get all of the content. Shortcodes are defined in the Snippets plugin based on each unit's particular custom post types and display needs.

The fix to this is to create an Elementor widget (https://developers.elementor.com/creating-a-new-widget/). I currently do not have time to do this but would like to do it myself when time frees up. Thought process for doing this:

Create a widget that has all of the loops in a single widget
Allow a textbox (or select menu) for custom post types on each unit, with that unit name attached somehow
Name each section by unit so that we can differentiate between types such as databases that are the same name for multiple units but different displays

**Comment by kevinkidwell** [comment]
I just got this added to the repo (https://github.com/cul-it/wp-custom-loop-widget) with the documentation of what all is included in the repo, how to use the plugin, and how to update it. I also added this to the Wiki under CULU Theme Plugins.

@manolobevia When you have a chance, would you be able to test this plugin to see if it's working as expected for you? I've tested it myself and it's doing what I expect but better to have someone else look as well.

**Comment by manolobevia** [comment]
@kevinkidwell Ok, I will.
