### ISSUE TITLE
UWS UNITS - Interactive Floor Maps

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#655]
Components:
Map design, Descriptive Elements (photos, details), explore options for searching, linking to map throughout site and highlighting locations, staff training. Potential hinderance: single software license, 14 sites would like to have; options for multiple editors

Units:
Law, Mann, Asia, Olin/Uris, ILR

Effort:
Medium

**Comment by cappadona** [comment]
@kevinkidwell Assigning this to you for obvious reasons 😄

I believe this may already be done, so please feel free to close if applicable.

**Comment by JesiBuell79** [comment]
Closing
