### ISSUE TITLE
UWS UNITS - Spaces

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#660]
Components:  
Landing pages that show type of space, availability, and option to reserve, filtering options, intergration of availability into a feature box - short code integrations, spaces feeds from LibCal, Outlook, R25 (25Live?) - API?, UI display, WP plugin development, Usability Testing, performance - test, maintain, improve. Hinderances: Nick's Time, WP API limitations, fitting the page design within the existing theme

Units:  
Mann but units like Law could utilize.  Main CUL site.
Olin/Uris

Effort:  
XL

**Comment by manolobevia** [comment]
List of reservable spaces: `https://spaces.library.cornell.edu/allspaces`

**Comment by JesiBuell79** [comment]
Closing
