### ISSUE TITLE
ULS UNITS - Events

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#661]
Components:  
Landing pages that show type of event, description and location, possible need short code integrations, events feeds from LibCal, localist, R25, Outlook - API?, UI display with filters for location, date, and type of event, WP plugin development, Usability Testing, performance - test, maintain, improve. Hinderances: Nick's Time, WP API limitations, fitting the page design within the existing theme

Units:  
Mann but units like Management and Olin/Uris may benefit.  Main CUL site.

Effort:  
XL

**Comment by cappadona** [comment]
Bumping to the Icebox where the rest of its open subtasks already reside.

**Comment by JesiBuell79** [comment]
Closing this epic - sub tickets still open
