### ISSUE TITLE
UWS UNITS - Newsletter

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#665]
Components:  
Archive old newsletters, move the mailing to Mailgun, commission the domain, create newsletter template, training, linking out to the newsletter

Units:  
Mann, ILR

Effort:  
Medium

**Comment by JesiBuell79** [comment]
@eeh53 @sew268 Do we still need this ticket?

**Comment by sew268** [comment]
@JesiBuell79 I don't think so?  But I'll let Tobi confirm :)

**Comment by eeh53** [comment]
Close 'er down!

**Comment by JesiBuell79** [comment]
@eeh53 - it's my favorite lol!
