### ISSUE TITLE
ULS UNITS - Research plugin to post to twitter when a new WP post added

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#676]
This is a request from Africana. They will be starting up a blog on the site at the beginning of February and are looking to cross post the blogs that are created to a Twitter account. 

Need to look into plugins that have this functionality and determine one that will work for this (which may end up being something other units would want to utilize). Should research and do some testing on this prior to a meeting in early February to go over the process with Africana staff.

**Comment by manolobevia** [comment]
@kevinkidwell I have found these ones:
- https://wordpress.org/plugins/wp-to-twitter/ (https://www.wpbeginner.com/plugins/how-to-automatically-send-tweet-when-you-publish-a-new-post-in-wordpress/)
- https://wordpress.org/plugins/twitter-auto-publish/ (better rating)

Good read: https://themeisle.com/blog/integrate-twitter-with-wordpress/

Also, we could use this for library events, in case some units want to post events to their twitter accounts.
