### ISSUE TITLE
Create github repo for Custom Loop Widget Plugin

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#696]
The way that Elementor requires us to add a widget is to actually create a plugin that incorporates the widget code. We should create a repo where we can keep this code and so that it can be bundled into the upstream, as it is its own plugin. I'm not sure who is able to create a repo for this, maybe @jgreidy?

**Comment by jgreidy** [comment]
I can't make github repos, but I ask Library Systems for them to be created.
The questions are:
What is the repo name? (cul-it/<<name>>)
Is the repo Public or Private?

**Comment by kevinkidwell** [comment]
The repo will probably be best as private in case we ever have to add loops that will be more sensitive info.

As for the name, I don't know what might be the best. Maybe uls-custom-loop-widget? Do we have a naming convention we were using for the Ares or Libcal Hours that we could keep consistent?

**Comment by jgreidy** [comment]
ares_wordpress vs. wp-libcal-hours

I think we should go with wp-custom-loop-widget @kevinkidwell

**Comment by jgreidy** [comment]
https://github.com/cul-it/wp-custom-loop-widget
