### ISSUE TITLE
ULS UNITS - Blog post template should show featured image if it exists

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#700]
We've added the first blog post for Africana and they are going to be using the Featured Image to show on their homepage. They would like this to be at the top of the post for each blog when you view the individual posts. Here is a link to their first blog: https://africana.library.cornell.edu/black-history-is-more-than-a-month/

**Comment by manolobevia** [comment]
But the post will be added manually to the homepage. Right?

**Comment by kevinkidwell** [comment]
The post is added automatically to the homepage using the Elementor Posts widget. This pulls the title, featured image, and content section. It displays the featured image and title, then uses the content section to create an excerpt of the post.
