### ISSUE TITLE
ULS UNITS - Implement announcement display on unit libraries

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#701]

**Comment by kevinkidwell** [comment]
@manolobevia this is something that we ended up adding to the draft roadmap after the voyager outage but hadn't created an issue yet. We hired a new student who is doing some more dev-type things and I have him working on this right now, using the Mann site for his test case of implementation.

**Comment by manolobevia** [comment]
@kevinkidwell I am getting very frustrated about your lack of communication. @ajs17 This situation needs to change.

**Comment by mbmartini** [comment]
Getting students to do dev work is very dicey and should be avoided. We have run into issues with this in the past. Reviewing content for accessibility compliance is one thing, but something as critical as this alert display needs to be done by staff.

**Comment by kevinkidwell** [comment]
@manolobevia @ajs17 There's been no communication from anyone on this project lately so this is something that we all need to work on going forward. We need to wait to hear about the roadmap decision that comes from Simeon and Danianne regarding timeline and then figure out sprints and who is working on what for the features.

**Comment by manolobevia** [comment]
I have tried to find this new feature on the wiki roadmap draft and the google doc for features, https://docs.google.com/spreadsheets/d/1ut4RXw0mpK6FOAqvkOMfgrVwU22shyeHvpml08-esa0/edit#gid=0,  but I don't see this new feature added. Can you point me to the draft road map you added this feature? @kevinkidwell we have had communications issues since the beginning, not just because of the current situation about Simeon and Danianne's decision on future roadmap. I am sure we can work to improve our communication.

**Comment by ajs17** [comment]
@manolobevia and @kevinkidwell thank you for bringing up these issues. I will do my best to get myself back up to speed and get us going again in the near future, and I think its a great time to talk about the structure of the project and how to work together and communicate more effectively. Manolo, I think you are out next week? Let me know when you are on-site again, and we can have a meeting with just you two, Melissa and Jim and talk about all this and come up with better ways to work together going forward. I also definitely understand the stress and frustration of not knowing where things stand, especially with a lot of personnel changes happening too. I'll do my best to get some clarity as soon as possible.

**Comment by manolobevia** [comment]
@ajs17 I will have my last two workshops this coming Tuesday and Wednesday. What about next Thursday? I'll be onsite. Thanks.

**Comment by ajs17** [comment]
Sounds good, I'll set it up. @kevinkidwell do you mind coming down to Olin for this? Since we'll be talking about communication, I'd rather have us all face-to-face, as I think Zoom can be pretty limiting sometimes.

**Comment by manolobevia** [comment]
@kevinkidwell no need to pass any dev work to students. We are taking care of that.

**Comment by manolobevia** [comment]
Also provide functionality for units to customize their own messages.
