### ISSUE TITLE
Create Pages with content templates for PSL

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#71]
We need to create the various pages within the PSL site architecture so that Leah and Henrik can get in and begin adding their content. This should be done by creating each page and adding in the blank sections in Elementor where they can edit content so that we are controlling layout.

**Comment by kevinkidwell** [comment]
I have created pages for pages within the PSL site. There are a number of pages where I had questions, which have been posed to the PSL Librarians and is waiting for a response.

Items that link out to main CUL or other pages have been added within the navigation.

I have also gone through with creating some basic templates in Elementor that allowed me to easily add the same layouts to multiple pages that needed the same layouts. I've exported all of those templates that are currently in the PSL site so that they can be used elsewhere, since we should having set templates for content across the units that stakeholders can select from.

[elementor-templates-2018-12-12.zip](https://github.com/cul-it/uls/files/2672086/elementor-templates-2018-12-12.zip)

**Comment by manolobevia** [comment]
![psl homepage desktop v1](https://user-images.githubusercontent.com/8395482/50014364-c4afda80-ff91-11e8-9757-eb3bb830dcd0.png)
![psl homepage desktop v2](https://user-images.githubusercontent.com/8395482/50014365-c5487100-ff91-11e8-8eaa-354d22a1ba34.png)
![psl homepage mobile](https://user-images.githubusercontent.com/8395482/50014366-c5487100-ff91-11e8-9e77-b37bd85d267a.png)
![psl sample interior](https://user-images.githubusercontent.com/8395482/50014367-c5487100-ff91-11e8-82ee-840cf0de38f9.png)
![psl visuals](https://user-images.githubusercontent.com/8395482/50014369-c5487100-ff91-11e8-8727-8082057ab770.png)

**Comment by manolobevia** [comment]
Adding mockups for reference. Ignore main navigation.
