### ISSUE TITLE
ULS UNITS - Create new upstream [v1.3.1]

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#713]

**Comment by jgreidy** [comment]
Please update the CULU changelog if it's not already updated. Thanks.

**Comment by jgreidy** [comment]
Remove all-in-one migration plugin from the upstream

**Comment by jgreidy** [comment]
For the changelog, you can just add the update comments to a section called 'Next Release' so you won't have to track the release numbers in the CULU Pantheon project. I'll change the 'Next Release' comment to whatever release I'm working on.

**Comment by jgreidy** [comment]
## [v1.3.1] -- 2020-02-20
### Changed
- CULU Theme updates - 1.0.32 -> v1.1.0 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
### Removed
- All-in One WP Migration

**Comment by jgreidy** [comment]
To build the artifacts, us this command

`composer update wpackagist-plugin/all-in-one-wp-migration`

This removes all-in-one-wp-migration from the /vendor directory and rebuilds the project, pulling in the CULU changes.

**Comment by jgreidy** [comment]
build v1.3.1
