### ISSUE TITLE
ULS UNITS - Resolve upstream issues for Music Library.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#714]
@kevinkidwell to update to the latest upstream MUSIC, you need to remove the last 2 commits you did on dev for Test new URL for course reserves Once I update dev with the new upstream, this commit and yours will be deployed to text, then to live.  Can please you revert to the original reserve ulr and then commit? Thanks.
-$reserves_url = 'http://api.library.cornell.edu/LibServices/showCourseReserveItemInfo.do?output=json&courseid=';
+$reserves_url = 'http://api.library.cornell.edu/CourseReserves/showCourseReserveItemInfo?courseid=';

**Comment by kevinkidwell** [comment]
This has been reverted to the pre-test version and the ares_wordpress plugin is back in line with the current version!
