### ISSUE TITLE
ULS UNITS - Libcal Hours - Next/Previous on Full Hours page not working

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#720]
@manolobevia I just received an email from Ken that clicking on the Next or Previous button from the [Full Hours page](https://rare.library.cornell.edu/full-hours/), it is just coming up blank instead of displaying the given week's hours. Is this something you want to look into to see what's up or would you like me to look into it?

**Comment by manolobevia** [comment]
@kevinkidwell I think you are more familiar with this plugin, I would prefer if you look into the issue.  I have checked other units and the pagination doesn't work. This was working before, I wonder if **libcal** has changed something on their end. Thanks.

**Comment by kevinkidwell** [comment]
I've been digging into this and I know what's happening finally. It seems like our custom navigation buttons for going to the next/previous weeks are the issue. I can think of two possible fixes, one is quite a bit easier than the other so I'd love opinions on which way might be better.

1. Re-enable the default LibCal widget Next/Previous buttons. This would mean needing to style the buttons and remove our custom navigation. We would lose the Today button ability in this case because we can't add that in to the widget.

2. Create a template to replace the widget where we loop through all of the data we are getting out of LibCal and create the table on our end. This would keep our custom navigation and would mean having to create a display that can loop through all of the information and parse it into various tables that we could display. This is how Mann is currently doing it and why ours is not. Our navigation is based off of the current Mann site but we aren't providing that loop/template to display and that's why it's breaking.

@manolobevia Do have a preference on which way you would prefer to have this? If we go with option 1 it will change the visuals of the widget where option 2 would keep them. Option 1 is also a much easier fix than option 2.

**Comment by manolobevia** [comment]
@kevinkidwell please go to **https://spaces.library.cornell.edu/admin/hours/widget**, select the daily hours or weekly grid view widgets. Choose a library and click on generate code/preview link for any library. As you can see, the pagination doesn't work on the site for the two widgets mentioned above. 

If you use the monthly calendar view widget and click on generate code/preview link the pagination works. I think there is a bug on libcal. This was working before on all unit sites.

Also I have noticed libcal has changed the jquery version. We have before <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>, but now they are using a new one, <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script> 

Does CUL have a contact person at libcal?

Let's say there is no bug.
Based on the options:

1- I have tried that using the code generated by the weekly grid view for Africana on a page template, and it doesn't display anything. Could you try?

2- That's pretty much what the widget does. Get the data, then the buttons hide/show the content weekly. 

I will go with #1  if the widget works. Eventually we will have to go with #2, so we have more control. 

Let me know what you think.

**Comment by kevinkidwell** [comment]
I don't know about a contact person at LibCal or not but that might be some good information to have.

Doing the preview on their site the buttons don't work, but I have a local instance of ULS Demo running and when I unhid the buttons and clicked on them, they worked to move between the weeks. I also just tried this on Africana's Full Hours page and it worked. I'm guessing their preview page doesn't have the JS file loaded that's needed to do that week switch, for some reason.

I'll work on getting Option 1 in place so that we can at least get a fix pushed out. After that we'll see how we can get Option 2 working more smoothly down the line and give us more control over everything.

**Comment by kevinkidwell** [comment]
@jgreidy I just merged this fix into the WP LibCal Hours master branch. Can this be included in the next upstream? https://github.com/cul-it/wp-libcal-hours
