### ISSUE TITLE
ULS UNITS - All-in-One WP Migration plugin wasn't removed for Upstream v1.3.2

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#723]
@jgreidy I can remove it manually if you want.

**Comment by jgreidy** [comment]
@manolobevia Which site(s) do you notice still have All-in-One WP Migration?

**Comment by jgreidy** [comment]
I see what's going on now - learned something here:

* uninstalling plugins with composer does not really get rid of them
    * remain in web/wp-content/plugins
    * need to run uninstall.php to clean up database entries
* suggested here: https://discourse.roots.io/t/preferred-way-to-install-and-uninstall-plugins/6914
```
ankurk91
Remove using Composer:
composer uninstall wpackagist-plugin/akismet
Above command will delete entry from composer.json and also delete the files related to this plugin.
But this will not trigger the uninstall.php file.
Plugin authors uses the uninstall.php 15 file to remove database entries created by plugin.

Uninstall using WP-CLI:
wp plugin uninstall akismet
Above command 5 has nothing to do with composer, it will delete the files related to this plugin. Plus this will trigger the uninstall.php which will delete database entries also. i.e. Complete uninstall can be done only via wp-cli.

paul_tibbetts
Jun '16
I personally use WP-CLI when I’m installing plugins on development to test them out and then use Composer to commit them to the project, which gets pushed to staging/production.

If you find yourself removing plugins once they’ve gone live you could SSH into the staging/production server(s) and use WP-CLI to uninstall them (cleanly), then on your development machine use the composer uninstall command to remove the plugin folder and entry in composer.json.
```

**Comment by jgreidy** [comment]
I'm working on a way to uninstall using terminus.

**Comment by jgreidy** [comment]
To remove a wordpress plugin from a Pantheon site:
`put the site in SFTP mode
terminus wp <sitename>.[dev,test,live] -- plugin deactivate all-in-one-wp-migration
terminus wp <sitename>.[dev,test,live] -- plugin uninstall all-in-one-wp-migration
commit the changes in SFTP mode
`
