### ISSUE TITLE
ULS UNITS - Remove staff profile custom loop from CULU and add it to the WP Custom Loop Elementor Widget.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#726]

**Comment by kevinkidwell** [comment]
@manolobevia I've moved the Staff Profiles loop into the WP Custom Loop Widget code. I made a few minor code adjustments and it's working as it was before. I was also able to move all of the CSS into the plugin as well and now we only load that when the staff profiles loop is called. If you want to keep the styles in the theme let me know and we can remove it from the loop widget plugin. This has also been pushed to the Master branch of the plugin repo so it's able/ready to be downloaded and tested!

**Comment by manolobevia** [comment]
@kevinkidwell that would be great. Thanks. Yes, let's keep the css on the theme. After your changes, I think we should do another upstream update and include this plugin.
