### ISSUE TITLE
CULU - Update header to allow for multiple hours display

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#737]
I've updated the [wp-libcal-hours plugin](https://github.com/cul-it/wp-libcal-hours) to be able to display multiple hours in the header. This was a large lift because it meant changing a number of other options throughout the structure of the plugin but it is now working as expected.

The way I've envisioned this working will mean a few changes on the theme file `header.php` and the removal of the `template-parts/library-hours.php` file.  This will allow the hours to work in the expected manner for the way that it's structured to display. 

A single function was created to now display the header hours and this now calls the other 2 functions that we had previously in place. Since we needed the ability to have two different IDs, it requires checking getting the option that stores the Library ID, seeing if an ID exists and then passing it to the function within the template file. Users are able to select in the same Settings area to be able to say which two libraries they wish to show hours from. This wording is what I could come up with for the settings area, totally open to recommendations for clearer language.

Because of the way the hours display if more than one ID is present, it was making the display of the contact/location block be way off to the site. This is why I pulled all of this into `header.php` instead of just updating `library-hours.php`. If we wanted to keep that separate file, we could bring the contact/location block into that instead.

### Proposed Changes

The change I'm proposing in `header.php` is replacing the first bit of code (lines 218 to 238) with the second:

```
<?php get_template_part( 'template-parts/library-hours' ); ?>

<ul class="header-contact">

    <li>
        <a href="<?php if (filter_var($email_label, FILTER_VALIDATE_EMAIL)) : ?>mailto:<?php echo $email_label ?><?php else : ?><?php echo $email_label ?><?php endif; ?>"
            title="Contact us"><i class="fas fa-envelope" aria-hidden="true"><span
                    class="sr-only">Contact us</span></i></a>
    </li>

    <!--<li><a href=""><i class="fas fa-phone-square" aria-hidden title=""></i></a></li>-->

    <?php if ( !empty( $google_map_label  ) ) { ?>

    <li><a href="<?php echo $google_map_label ?>" title="Library location"><i
                class="fas fa-map-marker-alt" aria-hidden="true"><span class="sr-only">Library
                    Location</span></i></a></li>

    <?php } ?>

</ul>
```

```
<div class="available-time">
  <?php $lid_1 = get_option('libcal_library_id_1');
  $lid_2 = get_option('libcal_library_id_2');
  if ($lid_1 != NULL) : 
    $shortcode = '[libcal_header_hours lid="' . $lid_1 . '"]'; ?>
    <i class="fas fa-clock icon-time" aria-hidden="true"><span class="sr-only">Library hours status</span></i> 
    <?php echo do_shortcode($shortcode); ?>
    <?php endif; if ($lid_2 != NULL) :
    $shortcode = '[libcal_header_hours lid="' . $lid_2 . '"]'; ?>
    <br />
    <i class="fas fa-clock icon-time" aria-hidden="true"><span class="sr-only">Library hours status</span></i> 
    <?php echo do_shortcode($shortcode); ?>
    <br />
  <?php endif; ?>
  <?php if ($lid_2 == NULL) : ?> - <?php endif; ?><a class="full-hours" href="/full-hours">Full Hours</a> /

  <ul class="header-contact">
    <li>
      <a href="<?php if (filter_var($email_label, FILTER_VALIDATE_EMAIL)) : ?>mailto:<?php echo $email_label ?><?php else : ?><?php echo $email_label ?><?php endif; ?>" title="Contact us">
        <i class="fas fa-envelope" aria-hidden="true"><span class="sr-only">Contact us</span></i>
      </a>
    </li>
    <?php if ( !empty( $google_map_label  ) ) { ?>
      <li>
        <a href="<?php echo $google_map_label ?>" title="Library location"><i class="fas fa-map-marker-alt" aria-hidden="true"><span class="sr-only">Library Location</span></i></a>
      </li>
    <?php } ?>
  </ul>
</div>
```

### Screenshots of the new single and multiple headers

Single Hours:
![Screen Shot 2020-03-18 at 3 20 12 PM](https://user-images.githubusercontent.com/29164102/76998928-3b255000-692c-11ea-975a-aafaea66d235.png)

Multiple Hours:
![Screen Shot 2020-03-18 at 3 21 50 PM](https://user-images.githubusercontent.com/29164102/76998942-3eb8d700-692c-11ea-856d-0d5fa0f24f28.png)

Settings in Admin:
![Screen Shot 2020-03-18 at 3 22 51 PM](https://user-images.githubusercontent.com/29164102/76998990-598b4b80-692c-11ea-8709-f8174f24b5fa.png)

**Comment by manolobevia** [comment]
Great.I can add the change to CULU. I'll use the latest libcal plugin on CULU for testing. Should I use the master or dev brunch? I'll check if this change need some responsive adjustment for mobile devices.
For Olin/Uris full hours page, I added the libcal shortcode for Olin and another for Uris, but it doesn't display for Uris. https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/full-hours/. Can you take a look when you can?

**Comment by kevinkidwell** [comment]
That double shortcode issue is also fixed in v2 of the plugin! It was a problem with both having the same ID so it was only showing one set of hours.

Just use the dev branch of the hours plugin for the moment. I won't push all these changes to the Master until right before we release.

**Comment by manolobevia** [comment]
Ok. Great. Thanks.
