### ISSUE TITLE
ULS UNITS - Remove double dashes on hours status.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#747]
![Screen Shot 2020-03-30 at 11.43.02 AM.png](https://images.zenhubusercontent.com/58ffa2ca51aa2c30577c6f84/50e8caac-0ad2-4c2b-a3ef-9332931376c1)

**Comment by kevinkidwell** [comment]
@manolobevia This has been fixed in v2 of the Libcal Hours plugin. Before this can be implemented, the theme will need to be adjusted with the code I put in #737. The changes in the latest version of the plugin are breaking without that adjustment.
