### ISSUE TITLE
ULS UNITS ILR - Php warning on WIT page

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#756]
While doing accessibility check, I have noticed this error:

Warning: Illegal string offset 'url' in /srv/bindings/f880a473a25e46c78513d827965ec9ec/code/web/wp-content/plugins/code-snippets/php/snippet-ops.php(446) : eval()'d code on line 6

https://dev-uls-ilr-library-cornell-edu.pantheonsite.io/wit/robots-increasing-safety/

**Comment by kevinkidwell** [comment]
I'll take a look at this. It seems that something is happening with the snippets plugin that's interacting with that. I may try to disable that snippet and then see what we have or what needs changed there.

**Comment by kevinkidwell** [comment]
@manolobevia Did you update ILR dev to the latest upstream? I was trying to replace that snippet with the loop from the Custom Loop plugin but the plugin is still the old version without all of the proper single templates.

**Comment by manolobevia** [comment]
@kevinkidwell No, I didn't.  Do you want me to update?

**Comment by kevinkidwell** [comment]
@manolobevia No need to update, the fix will be in the latest upstream.
