### ISSUE TITLE
ULS UNITS  - Missing status hours after adding the latest upstream update.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#758]
Ex: https://dev-uls-africana-library-cornell-edu.pantheonsite.io/
<img width="556" alt="Screen Shot 2020-04-07 at 3 40 52 PM" src="https://user-images.githubusercontent.com/8395482/78712372-8953c080-78e6-11ea-828c-a045f44e37d7.png">

**Comment by kevinkidwell** [comment]
That is extremely odd because it was working when I tested with uls-demo locally. I'll take a look at all of the units local to see what's happening there because it should be showing up.

**Comment by kevinkidwell** [comment]
@manolobevia After a little investigation, the issue here is that in Settings > LibCal Hours, this update removes the Library selection. Probably because that whole area was refactored with this update. If you go in there on the units and select them again, this will work as expect.
