### ISSUE TITLE
ULS UNITS - Create new upstream

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#761]
@jgreidy I have created a new release for the theme (release/1.1.6) to be added to the upstream
@kevinkidwell Please tell Jim what you need to add to this new upstream.

**Comment by kevinkidwell** [comment]
Custom Loop Widget v1.1.1 release is ready to be included in this upstream: https://github.com/cul-it/wp-custom-loop-widget/releases/tag/v1.1.1

**Comment by manolobevia** [comment]
@jgreidy please go ahead and create a new upstream. Thanks.

**Comment by jgreidy** [comment]
Ok - will start after lunch.

**Comment by kevinkidwell** [comment]
@jgreidy We also need to include a release from LibCal Hours - v2.0.1 - https://github.com/cul-it/wp-libcal-hours/releases/tag/v2.0.1

**Comment by jgreidy** [comment]
`
## [Unreleased]
- Draw Attention Pro - new version - Compatibility with WordPress 5.4: Unknown
- FacetWP - new version - Compatibility with WordPress 5.4: Unknown
- Kirki Customizer Framework - new version - Compatibility with WordPress 5.4: Unknown
- WP RSS Aggregator - Keyword Filtering - new version - Compatibility with WordPress 5.4: Unknown
- WP RSS Aggregator - Templates - new version - Compatibility with WordPress 5.4: Unknown

## [v1.3.9] - 2020-04-08
### Changed
- easy-notification-bar v1.1.2 - see [Changelog](https://wordpress.org/plugins/easy-notification-bar/#developers)
- capability-manager-enhanced aka PublishPress Capabilities - 1.9.5 - see [Changelog](https://wordpress.org/plugins/capability-manager-enhanced/#developers)
- Relevanssi - 4.7.2.1 - see [Changelog](https://wordpress.org/plugins/relevanssi/#developers)
- wp-custom-loop-widget v1.1.1 - see [Changelog](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
- wp-libcal-hours update - v2.0.1 - see [Changelog](https://github.com/cul-it/wp-libcal-hours/blob/dev/CHANGELOG.md)
- CULU Theme update v1.1.6 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
`
