### ISSUE TITLE
WUS - Full hours page doesn't display weekly libcal hours widget after updating to upstream v1.3.8

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#764]
Sites to check:
https://dev-uls-africana-library-cornell-edu.pantheonsite.io/full-hours/ 
https://dev-uls-finearts-library-cornell-edu.pantheonsite.io/full-hours/

**Comment by kevinkidwell** [comment]
This has been fixed in LibCal Hours release v2.0.1
