### ISSUE TITLE
WUS - Fix several formatting issues on staff profile on WP-custom-loop pluggin.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#765]
Please check: https://culu-library-cornell-edu.lndo.site/staff/alberto-contreras/
I have noticed a change in the original template. Before I had:
.......
```
$first_name = get_field('first_name');
$last_name = get_field('last_name'); ?>
<h3>
    <?php
    $degree = get_field('degree');
    echo $first_name . ' ' . $last_name, ($degree ? ', ' . $degree : '');
    ?>
  </h3>
```
.........
This is the new code.
```
<h3>
    <?php if (!empty(get_field('first_name')) && !empty(get_field('last_name'))) :
      the_field('first_name') . ' ' . the_field('last_name');
      if (!empty(get_field('degree'))) : ", " . the_field('degree');
      endif;
    endif; ?>
  </h3>
```

The reason I pre declared variables to hold some fields and use echo to concatenate fields and a space character was because, `the_field('first_name') . ' ' . the_field('last_name'); ` doesn't add a space. I know it should add a space, but it doesn't. It doesn't make any sense. We should see a space. I originally did the same: `the_field('first_name') . ' ' . the_field('last_name');

Do you want me to update the code @kevinkidwell ?

**Comment by kevinkidwell** [comment]
I did a little bit of testing and we can actually get it to work like this:
`the_field('first_name'); echo " "; the_field('last_name');`

I also noticed it's doing that issue with degree and staff type now, which can be fixed liked this:
`if (!empty(get_field('degree'))) : echo ", "; the_field('degree'); endif;`
`if (!empty(get_field('staff_type'))) : echo ", "; the_field('staff_type'); endif;`

Do you want to test those out on your local to see if they work and if they're good, I can update the plugin?
