### ISSUE TITLE
Build upstream 1.3.10

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#766]
Waiting for updates in custom loop and libcal plugins. Please let me know when they are ready, and anything else that should be added/changed.

**Comment by manolobevia** [comment]
@jgreidy I have a new CULU theme release (Release/v1.1.7). @kevinkidwell is updating the WP-Custom-loop plugin.

**Comment by kevinkidwell** [comment]
Custom Loop plugin has been updated to v1.1.2 - https://github.com/cul-it/wp-custom-loop-widget/releases/tag/v1.1.2

**Comment by jgreidy** [comment]
Upstream v1.3.10 is ready. Just a composer install.

## [v1.3.10] - 2020-04-09
### Changed
- twentynineteen v1.5 - see [Changelog](https://themes.trac.wordpress.org/log/twentynineteen)
- wp-custom-loop-widget v1.1.2 - see [Changelog](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
- CULU Theme update v1.1.7 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
