### ISSUE TITLE
Build upstream 1.3.11

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#779]
The new course reserves update is ready to be released. These changes have been made and are in v1.0.7 of the ares_wordpress plugin, available at https://github.com/cul-it/ares_wordpress/releases/tag/v1.0.7.

@manolobevia Are there any other things that need to go into this upstream?

**Comment by manolobevia** [comment]
@kevinkidwell that is the only thing. Let's wait first until we solve the full hours issue.

**Comment by jgreidy** [comment]
Can I start on this upstream now?

**Comment by manolobevia** [comment]
@jgreidy I need to do changes on CULU first. I'll let you know. For sure tomorrow or at the end of the day.

**Comment by jgreidy** [comment]
Sorry - I didn't get @manolobevia 's message in time. I have 1.3.11 ready. You can skip installing this one everywhere if you want. I'll be happy to make another one tomorrow.


## [v1.3.11] - 2020-05-15
### Changed
- json-content-importer - update 1.3.8 - see [changelog](https://wordpress.org/plugins/json-content-importer/#developers)
- simple-social-icons plugin - update 3.0.2 - see [Simple Social Icons](https://wordpress.org/plugins/simple-social-icons)
- ares_wordpress - update 1.0.7 - see [Changelog](https://github.com/cul-it/ares_wordpress/blob/master/CHANGELOG.md)

**Comment by manolobevia** [comment]
@jgreidy sorry. Thanks.

**Comment by manolobevia** [comment]
@jgreidy Actually, I will test this in a couple of sites for testing purposes.
