### ISSUE TITLE
WUS - Remove siteimprove plugin in all units.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#780]
The plugin is not letting libcal plugin display full hours.

From Jim:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://my2.siteimprove.com/overlay/cms/cmssite?url=https://…status=all&paged=1&s=&token=3cad427a42204e72b583f997b106f33f. (Reason: CORS request did not succeed).

**Comment by jgreidy** [comment]
You can just disable it on the live sites where it is a problem. SiteImprove will probably fix this for us soon.
