### ISSUE TITLE
WUS - Server error when creating a single template on elementor for Match Collective Work custom post using WP-custom-loop plugin.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#785]
<img width="627" alt="Screen Shot 2020-04-15 at 7 29 14 PM" src="https://user-images.githubusercontent.com/8395482/79400553-898e3480-7f54-11ea-9352-0aaffeec4d33.png">

**Comment by kevinkidwell** [comment]
I just pushed a fix for this to the Custom Loop plugin master branch. The while loop was still in here but that needed to be removed. This should be good to go.

**Comment by manolobevia** [comment]
Thanks
