### ISSUE TITLE
WUS - Research Enhanced Media Library plugins for organizing media files.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#787]

**Comment by kevinkidwell** [comment]
For AgCensus, I've been using [Media Library Assistant](https://wordpress.org/plugins/media-library-assistant/) and it's been working pretty well. Might be one to look into to see if it would work for this as well.

**Comment by manolobevia** [comment]
Checked Media Library Assistant (http://davidlingren.com/#two) and a few more from https://colorlib.com/wp/wordpress-media-library-management-plugins/. The lite/free version are very similar.  I like [FileBird.](https://wordpress.org/plugins/filebird/) because is compatible with elementor.
