### ISSUE TITLE
Build upstream 1.3.12

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#788]
Besides my CULU changes, @kevinkidwell is going to update the WP-custom-loop plugin. Do we need to add something else?

**Comment by jgreidy** [comment]
Just add in any other plugin updates.
@kevinkidwell Let me know when you're ready with the custom-loop.

**Comment by manolobevia** [comment]
@jgreidy CULU theme 1.1.8 git update is ready.

**Comment by manolobevia** [comment]
@jgreidy: @kevinkidwell updated libcal plugin too.
You probably have 3rd party plugin updates.

**Comment by manolobevia** [comment]
@jgreidy correction: @kevinkidwell updated **WP-custom-loop plugin** too, not the libcal one.

**Comment by jgreidy** [comment]
Upstream is ready to go. Just a composer install.


## [v1.3.12] - 2020-05-16
### Changed
- CULU Theme update v1.1.8 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
- wp-custom-loop-widget v1.1.3 - see [Changelog](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
