### ISSUE TITLE
UWS -  Staff Profiles: address additional filters

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#791]
@kevinkidwell are there any requirements for filtering staff profiles? For some units is not worthy to filter since don't have too many profiles. I think Mann and CUL will benefit of this feature.

**Comment by kevinkidwell** [comment]
Someone in the content group (I think Tobi) is working on the requirements list for this right now. Mann will definitely need something like it and Asia may actually benefit from it as well. I'll make sure we get the requirements list posted here when it's completed. We have our next meeting on Monday 4/27 so it may not be until then.

**Comment by manolobevia** [comment]
From Tobi:
I think we want to be able to sort by:

- First or last name
- Discipline support team
- Department
- Area(s) of expertise
Good sample for CUL staff. https://library.harvard.edu/staff

**Comment by eeh53** [comment]
The departments for Mann are:

- Administration 
- Instruction
- Research
- Collections
- Operations
- Outreach

**Comment by eeh53** [comment]
For Olin, we will want to be able to filter by:

- First or last name
- Department
- Liaison to (this will refer to academic departments within Arts & Sciences)

**Comment by manolobevia** [comment]
@eeh53 thank you.

**Comment by manolobevia** [comment]
Adding filters, sorting, and profile views (full/brief) for Olin/Uris, Mann, and CUL.

![DOC - Requirements](https://user-images.githubusercontent.com/8395482/83884666-35612e80-a713-11ea-8965-27933630a046.png)
