### ISSUE TITLE
Add logic to WP-custom-loop plugin for selecting loops for specific units in all pantheon environments.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#801]
This way, we are not restrictive to test on production env.

(need to test)

```php
$domain = $_SERVER['HTTP_HOST']);

if (strstr( $domain, 'africana' )) {
	$options = array_merge($options, $africana);
} 
.
.
.
```

**Comment by cappadona** [comment]
The [existing code](https://github.com/cul-it/wp-custom-loop-widget/blob/002189c31e9a6a823c0232d02cb1bc2e49ee3dad/widgets/custom-post-loops.php#L114-L196) could be further DRYed using [PHP's variable variables](https://www.php.net/manual/en/language.variables.variable.php) while looping through a list of the unit names.
