### ISSUE TITLE
UWS - build upstream v1.3.14

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#805]
Commercial Plugin and CULU updates. Anything else?

**Comment by jgreidy** [comment]
I don't see updates to library-cornell-edu-theme yet.

**Comment by manolobevia** [comment]
We have also changes for the WP-custom-loop plugin.

**Comment by manolobevia** [comment]
@jgreidy done with https://github.com/cul-it/uls/issues/807

**Comment by jgreidy** [comment]
## [v1.3.14] - 2020-05-11
### Changed
- Advanced Access Manager 6.5.1 - see [Release Notes](https://wordpress.org/plugins/advanced-access-manager/#developers)
- kirki customizer framework- 3.1.2 - see [Changelog](https://wordpress.org/plugins/kirki/#developers)
- WP Mail SMTP 2.0.1 - [Changelog](https://wordpress.org/plugins/wp-mail-smtp/#developers)
- CULU Theme update v1.2.0 - see [CULU CHANGELOG](https://github.com/cul-it/library-cornell-edu-theme/blob/master/CHANGELOG.md)
- wp-custom-loop-widget v1.1.4 - see [Changelog](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
