### ISSUE TITLE
Requirements for equipment

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#809]
- Need to differentiate between reservable and first-come, first-serve equipment
- Ability to sort equipment by type --> model --> location
- Initial view to be filtered to this individual location - potentially with the ability to switch to other unit sites to see all available equipment
- Policy information/instructions on reservation page/window
- Ability to reserve less than the maximum time allowed -- In LibCal
- Ability to add additional equipment types from reservation form -- In LibCal
- Shibboleth authentication connected to reservation form
- Connect equipment availability to library hours (unavailable 1 hour from closing)
- Unmediated reservations  -- In LibCal
- Automated confirmation email/due date reminder/overdue notification -- In LibCal
- Search function/feature checkbox/compare items
- Software list for long-term laptops - (can we pull from Sassafrass for each laptop?)
- Add equipment reservations to "My Account" to see what is upcoming/checked out/overdue
- Link to schedule an appointment with an expert for assistant

**Comment by cappadona** [comment]
## 2020-08-10 Update for Fall 2020

- avoid/eliminate short term loans
- focus on laptop and long term equipment loans (in a contactless fashion)
- Olin has lost equipment coordinator
- discussed splitting by location:
  - all laptops from Olin/Uris
  - all other equipment from Mann
- buffer period between reservations? (1wk to a month?)
  - option for renewal?
  - most of the procedures now for currently circulating material require a quarantine period of 3 days
  - so maybe a 4 day buffer in between for equipment
- most likely use LibCal
- many of our circulating laptops are currently in use by staff (won't be recalling them)
- our PCs are now 6 years old
  - little tanks but battery life is suffering
  - looking into funding/feasibility for replacing machines or batteries at the least
- confident that we'll be able to circulate at least the laptops in Sept
- draft of procedures by Monday 2020-08-17

**Comment by cappadona** [comment]
Olin/Uris would like a feature box on the homepage to show current availability of laptops and equipment

**Comment by cappadona** [comment]
@eeh53 Are we going to ignore all of the above for now and focus on maintaining existing functionality from the following sites?

* [Olin/Uris laptop reservation](https://olinuris.library.cornell.edu/services/laptops)
* [Mann equipment reservation](https://mannlib.cornell.edu/use/technology/equipment)

**Comment by eeh53** [comment]
@cappadona Thanks for checking! So all of the above is still true this semester - Mann is circulating specialized equipment and Olin is circulating laptops, with adjusted loan periods and contactless pickup/returns. However, the current webpages do reflect these changes, so I guess I would say that yes, we do want to replicate the existing functionality of those pages. Thanks!

**Comment by cappadona** [comment]
@eeh53 Thanks for clarifying.

@manolobevia Marking this as resolved so we can proceed with the rest of the integration work.
