### ISSUE TITLE
UWS - Spaces requirements

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#810]
**All Spaces display:**
(https://mannlib.cornell.edu/use/spaces )
- Feature box for each space type
- Ability to add a photo for each feature box
- Ability to add a label for that space type
- Feature box is clickable
- Space types for Mann  include: study spaces, conference and seminar rooms, classrooms, Lobby & cafe, gallery & exhibit spaces, Computing Facilities, Carrels & Lockers
- Space types for Olin: Carrels & Lockers, Faculty Research Spaces, Classrooms, Study Spaces, Cafe
- Ability to add a short description below the space type label

**Group Space display**
https://mannlib.cornell.edu/use/spaces/study 
- Feature box for each space/room
- Ability to add a photo for each feature box
- Ability to categorize rooms in Study Spaces: group study, individual study, quiet study, reservable, 
- Ability to show on each card: room availability, a reservation button, group/individual, quiet/noisy, location, loan period, occupancy 
- Ability to add a brief description or text on the feature box
- Option for text at top of landing page
- Reservation button opens in a modal window for libcal calendar if accessible and available; if not then we need the ability to link out to an outside system such as libcal reservation calendar or 25Live or another webpage with reservations information
- Location needs ability to add a url
- Ability to filter rooms in Study Spaces by category, availability, location, noise level 
- Icon options for the labels/categories - should be consistent with icons across all signage(currently using font awesome)

**Single Space display**
https://mannlib.cornell.edu/use/spaces/all/bissett-collaborative-center 
- Repeat info from the feature boxes regarding options and labels
- Space for descriptive text about the room
- Ability to add a bulleted list of features for the space
- Icon options for the labels/categories

Additional thoughts - should there be a way to label each space by unit library so that we can eventually show this on the main site?

**Comment by cappadona** [comment]
@cul-it/clo-content-group Confirming that these are the only reservation systems involved moving forward:
* [LibCal](https://spaces.library.cornell.edu)
* [25Live](https://corp.collegenet.com/products/scheduling/25live.html)

**Comment by sew268** [comment]
@cappadona yes!  Since it is still unclear to what extent we'll be using 25Live across campus, I think it is safe to treat 25Live as we have R25 for now.

**Comment by cappadona** [comment]
Thanks @sew268. Do you know of any other library spaces beyond Mann B30A/B that will be managed in 25Live?

**Comment by sew268** [comment]
@cappadona not to my knowledge but gonna tag @eeh53 as she was more involved in conversations with Jon Ladley this past February.  I **think** B30A & B were the only spaces being actively scheduled in 25Live that we would want to pull the reservation info from...

**Comment by eeh53** [comment]
@sew268 That's correct. There are other library spaces in 25Live as part of phase 1, but we are not actively managing reservations in that system since we're still using LibCal.

**Comment by cappadona** [comment]
Thanks @eeh53. When you get a chance (no rush), will you please provide a list of library spaces that will be in 25Live?

**Comment by cappadona** [comment]
@eeh53 & @sew268 I created #834 for you to inventory spaces across Olin, Uris and Mann.

**Comment by cappadona** [comment]
@sew268 @eeh53 Fair to say that none of this applies to the Spring launch of the Mann site and we'll be sticking with the link out to Chatter for the foreseeable future?

**Comment by eeh53** [comment]
@cappadona Correct!

**Comment by cappadona** [comment]
Thanks @eeh53 🙌🏼 

Removing from Mann Launch milestone.

**Comment by JesiBuell79** [comment]
Closing
