### ISSUE TITLE
FacetWP filtering not working

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#814]
Management just reached out that they aren't able to use the Filter by Topic on their Databases or FAQ pages. I checked other sites using FacetWP for filtering and they're all having this error.

Looking at the console, these are the two errors that I'm seeing on those pages:
![Screen Shot 2020-05-13 at 12 27 32 PM](https://user-images.githubusercontent.com/29164102/81839271-515b2100-9515-11ea-8672-79014a7a23c0.png)

It looks like this might be coming from Isotope that needs to be adjusted to work differently on these pages or something, I'm not exactly sure.

This is happening on most pages that use custom loops to render the pages because a lot of them use filters.

**Comment by manolobevia** [comment]
I just made secure the URL for the  image loader js library and everything is back to normal. I'll put a patch in all unite, instead of having another upstream.

**Comment by manolobevia** [comment]
@kevinkidwell management works now.

**Comment by kevinkidwell** [comment]
@manolobevia Looks great, thank you! I will reach out and let them know it's been fixed.
