### ISSUE TITLE
Consult with Olin/Uris stakeholders re: software availability

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#817]
Are they interested in the same presentation as Mann's current implementation?

If so, who will manually curate their software list via CSV?

More background in #753 and #816.

**Comment by kevinkidwell** [comment]
Notes from the meeting with Jessa:
The same view as Mann will work well and would be great to be able to switch locations to see where may have something that they don't (such as switching between Mann and Olin/Uris when on the unit site). The view that Mann has feels more useful than the map and would work well. Would prefer to use Sassafrass to bring this in and not have to work with a CSV.
