### ISSUE TITLE
Events requirements

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#819]
## Events Requirements
> extracted from [Box note](https://cornell.app.box.com/notes/662902398120) on 2020-10-19

### Landing page for news & events

- [x] Next _n_ events (#908)
   - default to `3` or `5` and make it configurable per instance
- [x] ~Feature box for both categories, as well as for additional customizable categories~
  - ~What will be included in the feature box for events?~
- [x] ~Ability to add a photo for each feature box~
- [x] ~Ability to add links below the feature box~

### Events calendar landing page (#909)

> What follows can essentially be summarized as: **Implement the current [Mann events calendar](https://mannlib.cornell.edu/news-events/events/calendar)**

#### February 2021 Update
We decided to keep it simple for now and compromised by [styling Localist widgets](https://github.com/cul-it/wp-cul-theme-culu/pull/90) so we could hit our Spring 2021 launch of the Olin/Uris and Mann sites. The compromises are indicated below via strikeouts and unchecked items.

- [x] Ability to display upcoming events sorted by day
- [x] Upcoming events include name, time, location 🤷🏼 , brief description, ~and tag~
- [ ] ~"Read more/read less" links for descriptions which display or less text in page when clicked~
- [x] Name is clickable link that opens up ~Libcal~ Localist event in the same window
- [ ] ~Location is clickable link that takes user to room page~
- [x] Ability to display a graphical calendar interface which defaults to the current month and allows users to navigate to previous or next month in the same window
- [x] Ability to filter by date, event type, and ~location~ in the same window
- [ ] ~"Include academic courses" toggle which pulls information from 25 Live~

### Events on homepage

- [x] Next _n_ events (#908)
     - default to `3` or `5` and make it configurable per instance
  - ~or featured/flagged events?~

**Comment by cappadona** [comment]
@arh269 Do you know if the [Events requirements](https://cornell.app.box.com/notes/662902398120) in Box are finalized?

**Comment by arh269** [comment]
Hi Nick,

I believe so, yes! @kevinkidwell, @sew268, and @eeh53: are any of you able to confirm? It has been awhile since we looked at this!

Andy

**Comment by sew268** [comment]
@cappadona @eeh53 - I do think this requirements list looks complete but I was drawn to the last box for the requirements of the Events landing page that says we need a toggle to add-in classes from 25Live.  Is that still necessary if we move forward with a url for staff that will show events in 100, 102, 160, Stone and the basement classrooms?  My hunch is that adding that info to the website was more for staff than for students but I could be wrong!

**Comment by cappadona** [comment]
Thanks for the feedback @sew268. My memory of our efforts for including academic courses on the Mann site was that _"Where's my class?"_ was a frequent question at our service desks. So yes, in a way it was for staff, but I think there was also the hope that our patrons would be able to answer this question on their own, even with an assist 😉.

All that being said, I'm okay with not including academic courses in what we officially consider and present as events moving forward.

I'm finding the Box note a bit cryptic at the moment since it includes news related requirements, which we have already previously decided is out of scope for events, correct? I'd like to either create a new page in the Box document that is Events only, or preferably, move the events requirements here at the top of this issue.

**Comment by sew268** [comment]
@cappadona thanks!  I'll defer to @eeh53 on this one.  Just out of curiousity, is it possible to know how many times that toggle was used??  We may want it regardless of stats so I truly am just curious but also realize that may be an impossible thing to get stats on. :)

**Comment by cappadona** [comment]
@sew268 Unfortunately we do not track that **Include academic courses** toggle on the events calendar.

**Comment by sew268** [comment]
@cappadona I figured as much!  But thanks for confirming

**Comment by cappadona** [comment]
@cul-it/clo-content-group I've attempted to extract the requirements pertaining to events from the Box note. [I've added some questions inline](https://github.com/cul-it/uls/issues/819#issue-621132909), primarily around:

* the feature box content for events on the News & Events landing page
* criteria for events on the homepage

Please review and let me know if I missed anything.

**Comment by kevinkidwell** [comment]
Asia events content they want to pull in:
[East Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=7624)
[Southeast Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=7625)
[South Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=42840)

**Comment by cappadona** [comment]
> Asia events content they want to pull in:
> [East Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=7624)
> [Southeast Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=7625)
> [South Asia Program](https://events.cornell.edu/calendar/week?event_types%5B%5D=42840)

Thanks @kevinkidwell. Some followup questions:

1. Do they want these events intermingled with Library events on the homepage and events calendar?
1. If not, how will they be used? On which pages do they need to appear and will they always be combined into a single listing or do they want a separate listing for each?

**Comment by kevinkidwell** [comment]
@cappadona We discussed this with the Asia stakeholders at our last meeting and got some answers for you.

1. Yes, they want to have them all appear in the same list on their site and aren't worried about having them display separately.
2. The pages that these events will need to display is the Homepage and an Events page. I told them that the homepage will need to be a shortened list (3 to 5 items, most likely) and then the Events page would have a list of all the events to display.

**Comment by cappadona** [comment]
Thanks @kevinkidwell. What do you think about using the [CU events widget builder](https://events.cornell.edu/help/widget) to meet Asia's needs at launch?

Here's [an example](https://events.cornell.edu/widget/view?schools=cornell&types=7624%2C42840%2C7625%2C4935%2C4205&days=365&num=5&format=html&template=custom-ktm) using the unstyled `Custom_ktm` template that includes the next 5 events over the upcoming 365 days for the following _depts_ in Localist:
* CUL
* Kroch Library
* East Asia Program
* South Asia Program
* Southeast Asia Program

**Comment by kevinkidwell** [comment]
@cappadona This looks really good and I think will do exactly what we're looking for on the Homepage. With doing this, would we just want to hide the Events page (that would list out more events) until we get that further along for Mann/Olin-Uris?

I'm also not sure exactly what to do with that list to be able to get it to display properly on the Asia homepage. Would that be something either you or Manolo would be able to do?

**Comment by cappadona** [comment]
Thanks @kevinkidwell. We could also use a widget for the Events page for now as well, increasing the number of events displayed, if interested.

I can work on integrating the widget on the Asia homepage unless this is something that @manolobevia wants to pick up.

**Comment by manolobevia** [comment]
@cappadona I can take care of it. Thanks.

**Comment by manolobevia** [comment]
@kevinkidwell I have added events to [homepage](https://dev-uls-asia-library-cornell-edu.pantheonsite.io) (3) and [Events page](https://dev-uls-asia-library-cornell-edu.pantheonsite.io/events/) (50 is the max). I will be working on styling the events.

**Comment by cappadona** [comment]
Styles for Localist widgets have been added to the them via cul-it/wp-cul-theme-culu#90.
