### ISSUE TITLE
Redesign staff profile pages to include filters, sorting, and profile views (full vs brief)

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#824]
Provide functionality to display staff profile by units and all staff from all units.

- [x] Create interactive wireframes
- [x] Test interactive wireframes
- [x] Create visuals

**Comment by manolobevia** [comment]
Attaching interactive hi fidelity wireframes for staff profiles and main and unit levels. I will show to group in our next meeting (Jun 8th)
- [Staff profile for main library](https://github.com/cul-it/uls/files/4736572/staff-cul.sketch.zip)
- [Staff profile for unit libraries](https://github.com/cul-it/uls/files/4736574/staff-unit.sketch.zip)

**Comment by manolobevia** [comment]
![1 STAFF CUL -  Home](https://user-images.githubusercontent.com/8395482/83886943-c2a58280-a715-11ea-9b98-10d014493a60.png)
![2 STAFF CUL --  Library list](https://user-images.githubusercontent.com/8395482/83886953-c6390980-a715-11ea-81b7-0e627bca9079.png)
![3 STAFF CUL --  Mann selected](https://user-images.githubusercontent.com/8395482/83886957-c76a3680-a715-11ea-9c3e-586d705b337b.png)
![4 STAFF CUL --  View display](https://user-images.githubusercontent.com/8395482/83886962-c89b6380-a715-11ea-80be-ef824e2b52d3.png)
![5 STAFF CUL --  View brief Display Option 1](https://user-images.githubusercontent.com/8395482/83886966-c933fa00-a715-11ea-998e-adba4849fc6d.png)
![6 STAFF CUL --  View brief Display Option 2](https://user-images.githubusercontent.com/8395482/83886969-c9cc9080-a715-11ea-87fd-abbde06fa565.png)

**Comment by manolobevia** [comment]
Staff profile visuals for main library:

![1 STAFF CUL -  Home](https://user-images.githubusercontent.com/8395482/83887153-0bf5d200-a716-11ea-8ffc-9dc8f3a986ed.png)

![2 STAFF CUL --  Library list](https://user-images.githubusercontent.com/8395482/83887161-0ef0c280-a716-11ea-82e6-26a69d6d34d1.png)

![3 STAFF CUL --  Mann selected](https://user-images.githubusercontent.com/8395482/83887167-10ba8600-a716-11ea-896e-7b1c44823567.png)

![4 STAFF CUL --  View display](https://user-images.githubusercontent.com/8395482/83887170-11531c80-a716-11ea-9a12-7d0691e4d216.png)

![5 STAFF CUL --  View brief Display Option 1](https://user-images.githubusercontent.com/8395482/83887172-11ebb300-a716-11ea-81e4-82ae0b5a5e3e.png)

![6 STAFF CUL --  View brief Display Option 2](https://user-images.githubusercontent.com/8395482/83887175-12844980-a716-11ea-9f84-9ba12f5f8bdf.png)

**Comment by manolobevia** [comment]
Staff profile visuals for unit libraries

![1 STAFF UNIT  Home](https://user-images.githubusercontent.com/8395482/83887418-6858f180-a716-11ea-8aae-7120bc90485d.png)

![2 STAFF UNIT  Filter by Department](https://user-images.githubusercontent.com/8395482/83887428-6b53e200-a716-11ea-9b88-9ce7ee9571e7.png)

![3 STAFF UNIT  Disable filter selection](https://user-images.githubusercontent.com/8395482/83887432-6c850f00-a716-11ea-9ada-16b87d7b4b58.png)

![4 STAFF UNIT - Select expertise](https://user-images.githubusercontent.com/8395482/83887439-6db63c00-a716-11ea-9270-837a8d704f1c.png)

**Comment by manolobevia** [comment]
Placed **Request a consultation** and **Request course instructions** outside the **Area of Expertise** filter.
![- 4 STAFF UNIT - Select expertise](https://user-images.githubusercontent.com/8395482/84683543-5bea4b00-af05-11ea-81f0-5f3dd4a2b776.png)

**Comment by arh269** [comment]
Hi Manolo! I missed the meeting where you demoed this--is there any particular type of feedback you're looking for?

**Comment by manolobevia** [comment]
Hi @arh269. I told the group I was going to put the mockups here in github. In case they want to take another look and see if I am missing something. I can demo this for you if you want. It will take 5 minutes.

**Comment by arh269** [comment]
That would be terrific! Maybe at our Monday meeting, since we're only talking about a few minutes? In the meantime, everything looks great to me!

**Comment by manolobevia** [comment]
Moving this to July milestone, in case of new changes.

**Comment by manolobevia** [comment]
Updated wireframes for filtering units. Primary changing filter selection to checkboxes and added staff profile card view.
![1 STAFF UNIT  Home](https://user-images.githubusercontent.com/8395482/90067865-bf061d00-dcbd-11ea-8a7a-7fd5aef0a187.png)
![2 STAFF UNIT  Filter by Department](https://user-images.githubusercontent.com/8395482/90067875-c3323a80-dcbd-11ea-84ab-8565f67a0e32.png)
![3 STAFF UNIT  Disable filter selection](https://user-images.githubusercontent.com/8395482/90067880-c4fbfe00-dcbd-11ea-9aef-e13a89fe807d.png)
![4 STAFF UNIT  collapse departments filter](https://user-images.githubusercontent.com/8395482/90067883-c6c5c180-dcbd-11ea-926c-74f8a4a7037b.png)
![5 STAFF UNIT - Expand areas of expertise](https://user-images.githubusercontent.com/8395482/90067889-c88f8500-dcbd-11ea-81ca-729819b8c7f5.png)
![6 STAFF UNIT - Card view](https://user-images.githubusercontent.com/8395482/90067893-ca594880-dcbd-11ea-959e-52eb94d25553.png)

**Comment by manolobevia** [comment]
**Detailed staff card vue**

![STAFF UNIT - detailed Card view](https://user-images.githubusercontent.com/8395482/98164472-57bdca80-1eb2-11eb-990b-245064818b88.png)

**Simplified staff card vue**

![STAFF UNIT - simplified (list) Card view](https://user-images.githubusercontent.com/8395482/98164509-65735000-1eb2-11eb-81da-4e46ea714c75.png)
card vue**
