### ISSUE TITLE
Fix unit logo placement in CULU footer for any page with software list shortcode

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#828]
This is due to a conflicting style from `vuetify` which overrides the `<footer>` to a block display instead of grid:

```
article,aside,details,figcaption,figure,footer,header,main,menu,nav,section,summary{display:block}
```

_from [`chunk-vendors.js`](https://github.com/cul-it/wp-cul-theme-culu/blob/c47371f2d93962df22165936f871894745bdf858/vue/dist/js/chunk-vendors.js)_

**Comment by cappadona** [comment]
@manolobevia Do you want me to address this now or hold off until we decide whether vuetify stays or goes?

**Comment by manolobevia** [comment]
@cappadona let's hold off for now.
