### ISSUE TITLE
Fix user tools on CULU header not displaying for any page with software list shortcode 

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#829]

**Comment by cappadona** [comment]
@manolobevia Thanks for catching and reporting. This is due to my [**single** style](https://github.com/cul-it/wp-cul-theme-culu/blob/c47371f2d93962df22165936f871894745bdf858/vue/src/components/SoftwareList.vue#L81-L83) in the SoftwareList component. So much for treading lightly...

On it.
