### ISSUE TITLE
Create visual for MANN homepage.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#835]

**Comment by manolobevia** [comment]
Incorporate MANN logo on homepage (https://mannlib.cornell.edu/sites/56e8640e3d262f7310000000/theme/images/cul-brand/mann-logo@2x.svg)

**Comment by manolobevia** [comment]
The content group has updated the dev site to reflect the new IA

**Comment by manolobevia** [comment]
Reopening issue. A visual will be still needed.

**Comment by manolobevia** [comment]
Homepage feature components. There are 2 versions for spaces and librarian

![HOMEPAGE FEATURE components](https://user-images.githubusercontent.com/8395482/87981898-f826e500-caa3-11ea-9970-296083873a32.png)
 components.

**Comment by manolobevia** [comment]
Samples of home page features in context with the highlight component.

![MANN HOME 1A](https://user-images.githubusercontent.com/8395482/87982029-29071a00-caa4-11ea-9267-31c3f53aa41f.png)

![MANN HOME 2](https://user-images.githubusercontent.com/8395482/87982045-2c9aa100-caa4-11ea-8dff-58f0d16773f6.png)

**Comment by manolobevia** [comment]
Sample of Mann logo added as a watermark in footer. 

![Mann logo](https://user-images.githubusercontent.com/8395482/87983366-3de4ad00-caa6-11ea-8e69-8c8bdb371282.png)

**Comment by manolobevia** [comment]
We will review these mockups on our next WUS website work meeting (Jul 27th).

**Comment by cappadona** [comment]
This is in place on dev with some remaining details (events, feature staff) in progress via separate issues.
