### ISSUE TITLE
Draw Attention and FacetWP Query Issue

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#840]
I mentioned this the past week or two in our meeting and was able to get an update on this. The problem is when FacetWP uses the incorrect post type in its query. There's a way that they've built in to be able to tell it to ignore a certain post type, we just need to use this:

`add_filter( 'facetwp_is_main_query', function( $is_main_query, $query ) {
    if ( 'da_image' == $query->get( 'post_type' ) ) {
        $is_main_query = false;
    }
    return $is_main_query;
}, 10, 2 );`

I've implemented this on the Asia dev site and on the Catherwood live site using the Snippets plugin. This would end up needing to go on Asia, Catherwood, Mann, Johnson, Math, Olin/Uris, Africana, Music, Engineering, Fine Arts, and Vet. Because of all of those that would need it, @manolobevia and @cappadona, do you think it would be worth putting this in the theme instead of one by one on each site?

FacetWP documentation for this issue: https://facetwp.com/documentation/troubleshooting/#wrongquery

**Comment by cappadona** [comment]
Thanks @kevinkidwell. As mentioned on this morning's call, my vote is to drop this from the snippets plugin and add it to the CULU theme.
