### ISSUE TITLE
Analyze overlap/duplication between Localist and LibCal events

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#841]
When developing the Mann site in 2016, we found a high rate of duplication between the CU events calendar (Localist) and the CUL Workshops calendar (LibCal events).

Will review a recent sampling of each to see if this still holds true.

> see cul-it/mann-wagon#834 and related issues for background from Mann website development

**Comment by cappadona** [comment]
@cul-it/clo-content-group I've added [two spreadsheets to Box](https://cornell.app.box.com/folder/112206373779) representative of Library events for the 2019 calendar year.

After reviewing the Localist and LibCal APIs I came up with a single request per system that should keep the duplication rate to a minimum. For the 2019 calendar year, this resulted in a single duplicate event, highlighted in red in each file.

## API Requests
> Each request was scoped for a date range of `2019-01-01` --> `2019-12-31`

### Localist

Requests all events via the `/events` endpoint in any of the library places defined in Localist (see **List A** below) that are not added/sponsored/entered by a user in any of the library related Localist department (see **List B** below).

#### List A – Library Places in Localist
- Annex
- Kroch
- Libe Cafe
- Mann
- Mann Addition
- MTJF Addition
- Olin
- Uris

#### List B – Library Departments in Localist

- Cornell University Library
- Mann Library
- Olin Library
- Africana Library
- Fine Arts Library
- Kroch Library
- Law Library
- Uris Library
- Engineering Library
- Hotel Library
- Adelson Library
- ILR Library
- Lee Library
- Management Library
- Veterinary Library
- Music Library
- Mathematics Library
- Library Annex

### LibCal

Requests the **CUL Workshops** calendar via the`/events` endpoint.

> This is the same calendar embedded on the [home page of our LibCal instance](https://spaces.library.cornell.edu/) although there it is labeled as **Workshops and Events @ CUL**


## Caveats/Questions

1. The Localist spreadsheet highlights two rows in yellow, which are events added by library staff where none of the Library departments within Localist (**List B** above) were identified. Unidentified sponsorship/ownership can lead to duplication, although for these two examples that was not the case.

1. One of the yellow highlighted rows in question is for a Library Exhibit. There are many more Library Exhibits in Localist but they are filtered out via the dept exclusion. If we proceed with this approach, and Localist continues to be the primary (only?) source for exhibit events, we'll need to explore our options to ensure exhibits are included.

   > One possible solution is to make a second request to the Localist API and filter by event_type = `Exhibit`

1. Does anyone know the current data sources for the 4 sub-pages of the [CUL Events page]( https://olinuris.library.cornell.edu/events)?

1. There are three other public calendars in LibCal, are any applicable here?
   - [mannUfactory makerspace](https://spaces.library.cornell.edu/calendar/makerspaces)
   - [NYSCILIB (TEST)](https://spaces.library.cornell.edu/calendar/NYSCILIB2019/)
   - [Systematic Reviews & Evidence Synthesis](https://spaces.library.cornell.edu/calendar?cid=12956)

**Comment by cappadona** [comment]
@cul-it/clo-content-group Thanks for everyone's feedback this morning.

I've [added a third spreadsheet](https://cornell.app.box.com/folder/112206373779) for the 216 events in Localist that were added/sponsored/entered by CUL staff for the 2019 calendar year as per @sew268 's request.

I also created and assigned #852 to @eeh53 since she so graciously _volunteered_ to help identify our data sources for exhibits 😄 

Thanks to @jgreidy & @mhk33 for confirming (and sharing the queries) that Localist is the only data source for events on the current Olin Uris site and CUL main site.

**Comment by jgreidy** [comment]
I can not view the the Box items from the 'two spreadsheets to Box' link above.

**Comment by jgreidy** [comment]
Here are the sources for CUL Events Page:

* library events page https://olinuris.library.cornell.edu/events
    * Book Talks
        * https://www.library.cornell.edu/about/events/booktalks
            * hand maintained mhk33
        * https://www.library.cornell.edu/about/events/booktalks/previous
            * hand maintained mhk33
    * Exhibitions
        * https://olinuris.library.cornell.edu/exhibitions
            * view with content type Exhibition
                * content manually entered by Craig Mains (csm4) or mhk33
    * Upcoming Events
        * https://olinuris.library.cornell.edu/events/upcoming
            * the last real content to this page (through 2016-05-13)
                * <p>Placeholder - The idea originally was for this page to point to the events list at https://olinuris7.dev.library.cornell.edu/events, but its parent "Library Events" points there. Maybe "Library Events" should point to a summary page with all of its submenu options (Exhibitions, Book Talks, etc) and this page should have a better title, like "Upcoming Events"?</p>
    * Workshops
        * https://olinuris.library.cornell.edu/events/workshops
            * view https://olinuris.library.cornell.edu/admin/structure/views/view/events/edit/block_4
            * content type Event - from feed Events
                * http://events.cornell.edu/api/school/10/events?api_key=KLhy2GtuSAGirYGY&pp=150&days=200&type[]=4925&type[]=4941&type[]=4250

**Comment by cappadona** [comment]
@jgreidy Thanks for the rundown...big help! Just added you to the Box folder.

**Comment by cappadona** [comment]
@cul-it/clo-content-group Thanks for everyone's feedback yesterday.

Three quick updates for your review:
1. I uploaded a new version of [localist_events-by-cul_2019_with-depts.xlsx
](https://cornell.app.box.com/file/696366056073) that includes the `room_number` field
1. I contacted the Cornell Events administrator who is following up with Localist to inquire about a controlled vocabulary for the `room_number` field, similar to the current behavior for `place` (location)
1. In speaking with the Cornell Events admin, I learned that we can [automate a nightly feed to Localist](https://support.localist.com/feeds/), meaning we can explore the option of entering **all of our events in LibCal only**

**Comment by cappadona** [comment]
> 2\. I contacted the Cornell Events administrator who is following up with Localist to inquire about a controlled vocabulary for the `room_number` field, similar to the current behavior for `place` (location)

Heard back from Cornell Events admin, who said this is not currently supported by Localist but a feature request has been submitted...

**Comment by mhk33** [comment]
Just a note, this page:
https://www.library.cornell.edu/about/events/booktalks

Uses a Localist widget to display the events. This is the feed URL:
//events.cornell.edu/widget/view?schools=cornell&amp;days=365&amp;num=50&amp;tags=book+talk

**Comment by cappadona** [comment]
Quick summary of what we decided via email. Thanks everyone!

1. Implement nightly feed from LibCal to Localist? This will eliminate the duplication of effort for our staff (we would enter our events in LibCal only) #886 
1. Use both LibCal and Localist as data sources #887 
   - we still need Localist for the events in the Library managed/sponsored by the rest of the Cornell community
   - the benefit of using LibCal for library events is that we have much finer control on the event metadata (i.e. Localist has limited location data for the Library and the Localist room number field does not leverage a controlled vocabulary)
1. Identify and engage stakeholders (staff who's responsibility it is to enter events in respective systems) to finalize a decision on the workflow process #852
