### ISSUE TITLE
Update CULU current staff custom field group

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#845]
Custom fields to be added:

- Unit Library (Ideally this field should be pre-populated)
- Department(s)
- Discipline support team

**Comment by cappadona** [comment]
@manolobevia, we could potentially use `constant('CUL_UNIT')` for pre-populating the unit library

https://github.com/cul-it/wp-cul-theme-culu/pull/12/commits/88e649c946a02a0ee590e2191d3925c874eed8bc

**Comment by manolobevia** [comment]
Table with all the staff profile fields:

| Field Label                  | Field Name                  | ACF Type       | Data Input    |
|:---------------------------- |:----------------------------|:---------------|:--------------|
| Unit Name                    | unit_name                   | Input Text     | config.yml    |
| Department                   | department                  | Select List    | config.yml    |
| Discipline Support Team      | discipline_support_teamat   | Text Area      | user          |
| Profile Photo                | profile_photo               | Image          | user          |
| First Name                   | first_name                  | Input Text     | user          |
| Last Name                    | last_name                   | Input Text     | user          |
| Degree                       | degree                      | Input Text     | user          |
| Staff Type                   | staff_type                  | Input Text     | user          |
| Title                        | title                       | Input Text     | user          |
| Email                        | email                       | Email          | user          |
| Phone                        | phone                       | Input Text     | libcal        |
| Consultation                 | consultation                | Select List    | user          |
| Office Location              | office_location             | Input Text     | user          |
| Areas of Expertise           | areas_of_expertise          | Text Area      | user          |
| Faculty Bio                  | faculty_bio                 | Url            | user          |
| ORCID ID                     | orcid_id                    | Url            | user          |
| Linkedin Profile             | linkedin_profile            | Url            | user          |
| Liaison Areas                | liaison_areas               | Text Area      | user          |

@cappadona should `Discipline Support Team` be added to `config.yml `?

**Comment by cappadona** [comment]
@manolobevia Are `discipline_support_team` values managed via a controlled vocabulary? I'm surprised about it being listed as a **text area** in the table. If that field type is not a mistake and values are open-ended, then I don't see what we would add to the config related to this field.

Apologies if I'm missing something obvious.

**Comment by manolobevia** [comment]
@cappadona I added as a text area, but at the end of the table I asked if it should be part of cul-config.yml. This should definitely be managed as controlled vocabulary. @eeh53 should areas of expertise be managed via a controlled vocabulary too?

**Comment by cappadona** [comment]
@manolobevia Got it...thanks for clarifying.

Along the same lines, what do you think about using a [select field](https://www.advancedcustomfields.com/resources/select/) for `unit_name`?

**Comment by manolobevia** [comment]
@cappadona `unit_name` is already pre-populated as a default input text value. If you are using MANN, the value will be Mann.

**Comment by cappadona** [comment]
Yes, it defaults to a value based on the YAML config, but since it's a text field a user can change the value to anything they want. If we use a `select` field, then the values are controlled by the YAML config and we can still set a default based on the active unit.

**Comment by manolobevia** [comment]
That was going to be my next thing. I want to see if I can restrict with ACF  the user to modify the value. If not, I will have a select list. Originally select list was the first option.

**Comment by cappadona** [comment]
If we're going to allow staff to be added from the CUL instance, I think we don't want to restrict editing the value.

**Comment by eeh53** [comment]
@manolobevia Re: controlled vocabulary for areas of expertise - yes, we did always intend to make this a controlled vocabulary. I believe someone in Erica Johns's department has been working on this, and they may even have a draft ready for Admin Council to review. I can bring this up at our next Admin Council meeting (Wed. 7/29).

**Comment by manolobevia** [comment]
> If we're going to allow staff to be added from the CUL instance, I think we don't want to restrict editing the value.

I thought staff were going to add/update profiles from their respective units without going to CUL. Then we use CUL distributor for getting all the staff units. We will use the (CUL) WP Rest API to get all the staff in CULU or get staff for any specific unit at the unit level. If it is the other way around, yes we will need a select list.

**Comment by manolobevia** [comment]
Thanks @eeh53

**Comment by cappadona** [comment]
> I thought staff were going to add/update profiles from their respective units without going to CUL.

Yes, this is the preferred/standard workflow but when we discussed this we weren't going to prevent users from creating staff in the CUL instance, especially since some staff (i.e. admin suite) do not fall under one of the unit libraries.
