### ISSUE TITLE
Restrict Elementor for staff profile post type on CULU and all units.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#846]
Should we do the restriction in the CULU theme?
Check: https://github.com/elementor/elementor/issues/9151#issuecomment-533867416

**Comment by kevinkidwell** [comment]
@manolobevia Do we want to restrict Elementor on that page for everyone or just non-administrators? Will we still need to implement the Custom Loop plugin with the staff profiles on unit sites? I guess I'm not sure what the workflow will be and where we would need to restrict things like this.

**Comment by manolobevia** [comment]
@kevinkidwell units admins can't really edit the content of a staff profile via [elementor](https://dev-uls-mann-library-cornell-edu.pantheonsite.io/wp/wp-admin/post.php?post=1371&action=elementor). They can change [single page template for staff](wp-admin/edit.php?post_type=elementor_library&tabs_group=theme), which it should be restricted too. 

I would like to restrict the use of elementor on staff post types via culu theme, so I don't have to manually to disable the staff post on the [elementor settings](https://africana.library.cornell.edu/wp/wp-admin/admin.php?page=elementor) for each unit . Sorry if I don't make anything.

**Comment by cappadona** [comment]
@manolobevia If staff profiles shouldn't be edited via elementor (it sounds like this is still up for debate), I think the preferred approach for handling this via CULU functions.php is to:

- ensure Elementor is disabled for staff CPT via WP's [`update_option()`](https://developer.wordpress.org/reference/functions/update_option/)
- remove staff CPT from Elementor's Post Types via a Elementor's supplied [`post_type_objects` filter](https://github.com/elementor/elementor/pull/9272)
