### ISSUE TITLE
Fix unit internal search styles in CULU for any page with software list shortcode.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#849]
<img width="1045" alt="Screen Shot 2020-07-22 at 2 10 01 PM" src="https://user-images.githubusercontent.com/8395482/88226160-aa43e580-cc39-11ea-9eb7-768c74847d33.png">

**Comment by cappadona** [comment]
Thanks @manolobevia. This is the same deal as #828 (conflicting style from `vuetify`), so sitting tight for now.

```
button,input,select,textarea{background-color:transparent;border-style:none;color:inherit}
```

_from [`chunk-vendors.js`](https://github.com/cul-it/wp-cul-theme-culu/blob/c47371f2d93962df22165936f871894745bdf858/vue/dist/js/chunk-vendors.js)_
