### ISSUE TITLE
Identify workflow for publicizing exhibits across CUL units

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#852]
Do all units publicize their exhibit schedule via Localist (CU events)?

@eeh53 – `2020-09-21` update: ~Do you want to include the stakeholders roundup here~ or should we create a separate issue – #888?

> See #841 for background.

**Comment by eeh53** [comment]
@cappadona Let's do a separate issue for the stakeholders roundup!

**Comment by cappadona** [comment]
Thanks @eeh53. Just created #888 for stakeholders review. Currently unassigned.

**Comment by JesiBuell79** [comment]
Close - addressed in separate ticket
