### ISSUE TITLE
Add restriction by role to Elementor Widget Manager

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#854]
Background information on Elementor Widget Manager can be found in #667.

After functionality has been extended in #853, the next step is work on allowing the deactivation of widgets based on the user roles. This will likely be the trickier part of this functionality extension, it will need to take into account:

1. Reading and displaying Advanced Access Manager roles that exist
2. Reading the role of the current user
3. Various checkboxes in the Widget Manager admin window for each role
4. Logic to only deactivate a widget if user role is not checked as activated

There may be more to this will need to be expanded upon once I dive into this phase of development.

**Comment by kevinkidwell** [comment]
I was able to do this in a slightly odd way that doesn't involve listing out all roles and then deactivating by role. Rather, using the Elementor Widget Manager plugin, I added a line to check if the current user can manage plugins or not within the widget deactivation call. This allows all Admin to see all Elementor options but anyone who is not an admin will only see those plugins not deactivated.

I never heard back from the owners of the AAM plugin that I wanted to use for this so I was looking for another, more simple way to achieve this.

I tested this on my local Law instance. Screenshots are below:
Admin:
![Screen Shot 2020-09-23 at 1 31 05 PM](https://user-images.githubusercontent.com/29164102/94048171-17423b80-fda1-11ea-9f03-8d9869b7d950.png)

Non-Admin:
![Screen Shot 2020-09-23 at 1 30 49 PM](https://user-images.githubusercontent.com/29164102/94048196-21fcd080-fda1-11ea-8278-ce22396676ea.png)

@manolobevia @cappadona I haven't added this code into a Repo yet or anything but it would be great if you could add the plugin and try it out as it is now. I would also like to figure out how we want to go about a plugin like this, since its base is a free plugin but it has a couple modifications to meet our needs. Should we make a repo and keep it in there, then update around our custom code if/when plugin updates come out?

[elementor-widget-manager.zip](https://github.com/cul-it/uls/files/5269919/elementor-widget-manager.zip)

**Comment by manolobevia** [comment]
@kevinkidwell I have tested the plugin on [Hotel DEV](https://dev-uls-hotel-library-cornell-edu.pantheonsite.io/). I have created a new  account and tested with the role of `content editor` and `content admin` (not sure if you are targeting this too). When I edit a page, I don't see any widget.

<img width="898" alt="Screen Shot 2020-09-23 at 5 09 26 PM" src="https://user-images.githubusercontent.com/8395482/94070451-3603fa80-fdc0-11ea-934f-3c72d26adf18.png">

But as soon as I click on the widget icon, I am able to see all the widgets.

<img width="895" alt="Screen Shot 2020-09-23 at 5 09 39 PM" src="https://user-images.githubusercontent.com/8395482/94070486-4c11bb00-fdc0-11ea-92ac-38636f95cdc0.png">

Should I test only on live sites or It doesn't matter? Let me know if I am doing something wrong for testing this new feature.

> I would also like to figure out how we want to go about a plugin like this, since its base is a free plugin but it has a couple modifications to meet our needs. Should we make a repo and keep it in there, then update around our custom code if/when plugin updates come out?

I am not sure what to do. Does this plugin have an API where you could create a hook?

**Comment by kevinkidwell** [comment]
@manolobevia Do you happen to have the Role Manager settings adjusted under the Elementor menu? Not seeing any widgets is what I had had when the checkbox for "Only allow to edit existing content" was checked. If you are using that, try unchecking that box and it should work. If you aren't using that, I'll have to dig in a little more to see why it might not be working.

This plugin is extremely minimal and doesn't seem to have any hooks or API. It seems like a one-off kind of thing that they developed and I'm not sure how often they'll actually be updating it, aside from keeping in line with Elementor version updates.

**Comment by manolobevia** [comment]
@kevinkidwell works.

**Comment by cappadona** [comment]
I haven't tested it personally but @kevinkidwell demoed it for me earlier today and functionality looked good and we [forked the repo](https://github.com/cul-it/elementor-widget-manager/) so we can manage our contributions.
