### ISSUE TITLE
Filter spaces wireframes for units and CUL.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#855]

**Comment by manolobevia** [comment]
Filter spaces for units.

![1 - SPACES - UNIT - BROWSE](https://user-images.githubusercontent.com/8395482/89182249-64edb500-d563-11ea-8ec4-6d4e796ad138.png)
![2 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182252-661ee200-d563-11ea-9303-ea7a1b8459bd.png)
![3 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182253-67500f00-d563-11ea-9dd5-c3b9d70493e8.png)
![4 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182427-b26a2200-d563-11ea-88a3-5e72b719f98c.png)
![5 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182254-67e8a580-d563-11ea-84e1-a7381d83c743.png)
![6 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182255-68813c00-d563-11ea-8707-866e6a3e8ea4.png)
![7 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182258-68813c00-d563-11ea-8440-49e714409b99.png)
![8 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182259-6919d280-d563-11ea-93e0-cbf6c13da72e.png)
![9 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182261-69b26900-d563-11ea-83e3-15541ff18137.png)
![10 - SPACES - UNIT -  FILTER](https://user-images.githubusercontent.com/8395482/89182262-69b26900-d563-11ea-801e-b01835c011fc.png)
![SPACES - UNIT -  Card](https://user-images.githubusercontent.com/8395482/89182264-6a4aff80-d563-11ea-95b0-2e1cf180d76d.png)

**Comment by manolobevia** [comment]
Spaces CUL homepage options
![SPACES - CUL - Home 1](https://user-images.githubusercontent.com/8395482/89182492-cf9ef080-d563-11ea-9f8e-5ae644e33249.png)
![SPACES - CUL - Home 2](https://user-images.githubusercontent.com/8395482/89182493-d0378700-d563-11ea-8128-3da00f30bd25.png)
![SPACES - CUL - Home 3](https://user-images.githubusercontent.com/8395482/89182494-d0378700-d563-11ea-9c9a-914d6b58ea92.png)

**Comment by manolobevia** [comment]
Spaces CUL filter page
![SPACES - CUL - Filters - Selected](https://user-images.githubusercontent.com/8395482/89182533-e1809380-d563-11ea-9f49-1ed22c6299a5.png)
![SPACES - CUL - Filters](https://user-images.githubusercontent.com/8395482/89182534-e1809380-d563-11ea-92b8-1dfb7fadcf0c.png)

**Comment by sew268** [comment]
@manolobevia There is a lot here to review!!  I'm going to try and detail our comments/feedback here in the issue but I'm sure we'll want to go over all this at one of our Monday meetings.

- the numbers by the space types is a little confusing and we aren't totally sure how they are being generated.  If they're coming from the # of spaces that are listed as being the type of space, it isn't a true reflection of what we have.  For example, the number 12 is by Study Space but we have more than 12 study spaces in the library.  We would vote for removing the # to avoid that confusion as well as people thinking that the space types were in some kind of numberical order.

- We think we'd like to stick with simple information on the initial space card as too much text makes the card look a bit cluttered, the Gallery Card is a good example.

- While we appreciate and were intrigued by the option to advertise in the lobby on the front of the lobby & cafe card, we aren't sure if looking for a space is how people would find this information.  Let's remove and keep as a distinct page as we do now on Mann's site

- For the left hand filter menu, we think that using check boxes to show the filters selected would be better than the boxes.  The boxes look a bit too much like the reserve button.

- Building on from that, we think that we should look at a new treatment for showing 'Closed' - the box, even though grayed out, looks a lot like a button to click.

- Group Study is listed as a 'feature' in the left hand menu, but it isn't listed as a 'feature' on the space card itself.

- We think we should replace the feature list with the icons that right now are over the image of the space and move the features to the detailed page view.

- We like the ability to rotate through multiple images but we won't need that ability for every space, just select ones like the Cocktail Lounge.

- For the mock-up for the main CUL site, there is a 'start over/clear filters' option at the top - can we put that on unit sites as well?

- We were all in agreement that we liked the mock-up for the main CUL space landing page that showed a unit library card for each library with the ability to click through.  Perhaps we could have some filter options on the left where you could click 'Individual Study' or 'Group Study' and it would refresh to show only those unit libraries that offered that type of space?

@kevinkidwell @eeh53 - my notes weren't as good as I thought they were so please add anything we discussed that I may have missed!  In fact, I know we had some thoughts on the pagination but I can't remember what we agreed on...sorry!

**Comment by JesiBuell79** [comment]
I believe this is closed
