### ISSUE TITLE
Olin/Uris content adjustments

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#857]
This issue is to document what needs done with content on the Olin/Uris dev site and provide a checklist we can mark off as we make these changes.

**Comment by kevinkidwell** [comment]
## Pages that need content:
- [ ]  [Databases in the Electronic Text Center page](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/databases-in-the-electronic-text-center/) - Linked from Collection Highlights, Electronic Text Center
- [ ]  [District of Columbia INDEX](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/sanborn-fire-ins%E2%80%A6rict-of-columbia/) - Linked from Collection Highlights, Map & Geospatial Information Collection, Map Collection, Sanborn Fire Insurance Maps - Do these indexes need to actually exist on this site or could we link out to something else?

## Page content questions:
- [ ] [Maps & Geospatial Location & Hours](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/maps-geospatial-location-hours/) - Does this need to exist?
- [ ] [Links to Selected Map & Geospatial Resources](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/links-to-selected-map-geospatial-resources/) - The links on this page go to more pages with links. Can these be combined or are all of these necessary in this format? Could they be created in some other way, such as a custom post type for resources? Many, if not all, of these child pages have notes that the page is dynamic so this could be done a better way. Child pages:
> [GIS Data & Maps](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/links-to-gis-data-maps/)
> - [Africa](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-africa/)
> - [Asia](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-asia/)
> - [Australia & New Zealand](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-australia-new-zealand/)
> - [Canada](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-canada/)
> - [Europe](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-europe/)
> - [Latin America](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-latin-america/)
> - [New York State / New York City / Tompkins County / Ithaca](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-local-new-york-city-new-york-state/)
> - [United States](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-united-states/)
> - [World](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/gis-data-maps-world/)
> [GIS Resources](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/links-to-gis-resources/)
> [Gazetteers](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/links-to-gazetteers/)
> [Reference Resources](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/links-to-cartographic-and-geographic-reference-resources/)
- [ ] [Micrographic Equipment](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/micrographic-collections-equipment/) - Does this need to be its own page? The same content is listed 2 down in the toggle.
- [ ] [Collection Highlights](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/collection-highlights/) US Government Documents has a link to a PDF.
- [ ] [Pay or Appeal a Fine](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/pay-or-appeal-a-fine/) has a link to a Word Doc at the bottom
- [ ] [Instruction & Outreach](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/instruction-outreach/) - Can these pages be cleaned up or consolidated? There are so many subpages with information that is buried and likely never actually seen by patrons - maybe could be made into a LibGuide if all this info is needed?
- [ ] [Research Guides Use Conditions](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/research-guides-use-conditions/) - Does this need to be on this site or should it be on these guides themselves?
- [ ] [Current & Past Exhibitions](https://dev-uls-olinuris-library-cornell-edu.pantheonsite.io/current-past-exhibitions/) - What was being done with Exhibitions?

## Forms to review (Jessa?):
- [ ] [Media Digitization Request](https://cornell.ca1.qualtrics.com/jfe/form/SV_aWxM9foIMWUUaJT)
- [ ] [Online Fine Appeal](https://cornell.ca1.qualtrics.com/jfe/form/SV_6sS553RrAXLreuh)

**Comment by kevinkidwell** [comment]
@eeh53 @sew268 I have updated the forms so they are ready to be reviewed and then shared with whomever it needs to be (I've already forgotten the name again).

**Comment by JesiBuell79** [comment]
@eeh53 @sew268 - do we need this list still?

**Comment by sew268** [comment]
@JesiBuell79 so I had to take a look at the Olin/Uris website, looks like:
1.  They renamed the electronic data center and resolved the maps content issues
2. There is still a like to a PDF but the link is broken so that will still need to be addressed https://olinuris.library.cornell.edu/files/Collection%20Development%20Policy_0.pdf 
3. The fine appeal form was transitioned to on online form

**Comment by JesiBuell79** [comment]
Removed PDF
