### ISSUE TITLE
Refactor WP custom loop plugin partials to avoid code duplication.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#861]
Sample: `https://github.com/cul-it/wp-custom-loop-widget/pull/13/commits/59db4e1c3f771d9ac3a4e28e27403503b1db83ed`

**Comment by kevinkidwell** [comment]
@manolobevia I just went through the loops and removed duplicate code where I could. I pushed it to the plugin if you want to take a look at see if there's anything that I missed in the partials!

**Comment by manolobevia** [comment]
@kevinkidwell Thank you. I will.

**Comment by manolobevia** [comment]
@kevinkidwell I reviewed the changes. All good. Thanks.
