### ISSUE TITLE
Clean up WP Libcal Hours plugin code

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#862]
Having to do the recent fix for #860, there was a lot in this part of the plugin that was confusing to get through and I was wondering why it was there.

I'd like to clean up the code and streamline it for better readability and debugging. A couple of questions to ask when cleaning up:
1. Do we need to specifically call out unit libraries by ID for specific text shown instead of hours or can we can do it by a variable coming with the location data?
2. Is any of the code within the various functions duplicated and can we reduce duplication?

**Comment by cappadona** [comment]
Morning @kevinkidwell.

I was reviewing the LibCal hours plugin earlier this week with @manolobevia after I noticed the Mann dev site was throwing an error in response to the overhaul of Mann's hours in Libcal (Tobi removed most of the _departments_ under Mann [in prep for the Fall semester](https://github.com/cul-it/mann-wagon/issues/1050)).

The one consequential deletion was the **Lobby**, and when I went to the Mann dev site admin to select another option for `libcal_library_id_2` I was surprised to find a [hardcoded list of options](https://github.com/cul-it/wp-libcal-hours/blob/b890472b10a0794a1131bacdcad690235d67593a/admin/class-wp-libcal-hours-admin.php#L110-L137) (not to mention the duplication 😉). I'm not sure whether this is aligned with one of your questions from above, but I think it would be worth our while to generate the options dynamically based on data from the LibCal API.

If you agree, are you open to us creating some issues in the plugin repo and perhaps using the upcoming mannUfactory hours change that you mentioned in Slack to implement some of this refactoring?

**Comment by kevinkidwell** [comment]
@cappadona It would be great to get rid of the hard coded list of options that are in there. When this plugin was developed, Tahir put together the initial list and then I've just been doing updates as we needed without changing much of the base code. I'm not familiar enough with the LibCal API yet to know how to go about doing that change but I agree it would be something we should look into doing.

I've started going through some of the duplication and cleanup, only on the files in the Public area of the plugin so far. I think if we want to start putting some issues in that repo and using it to track the edits there, we can. 

There was something special about that second LID with its display name. I had to put in some logic to have it adjust the display name to match more what's on the current sites for Mann and Olin/Uris, rather than the name LibCal was giving us. I don't remember all of the specifics with that but it's something to think about with the dynamically generated list if we aren't controlling the items in that list, does it still seem possible/worth it to adjust display names in specific cases?

**Comment by cappadona** [comment]
Thanks @kevinkidwell. I'll start adding an epic with some issues to the plugin repo and we can go from there.

Unfortunately (for me), I do have experience with the LibCal API and have some ideas for how we can help reduce the maintenance of this hours plugin.

And yes, I believe this is the [second LID magic](https://github.com/cul-it/wp-libcal-hours/blob/b890472b10a0794a1131bacdcad690235d67593a/public/class-wp-libcal-hours-public.php#L204-L216) you're referring to 😄

**Comment by cappadona** [comment]
@kevinkidwell I took a first pass at [an epic](https://github.com/cul-it/wp-libcal-hours/issues/35) and some initial sub-tasks. Please review and add/edit as needed.

My vote is to close this issue out and continue our work in the epic.

**Comment by manolobevia** [comment]
@cappadona +1

**Comment by kevinkidwell** [comment]
Sounds good to me!
