### ISSUE TITLE
Renew License for wp-rss-aggregator plugin

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#865]
The license for wp-rss-aggregator plugin expired August 1.

There is a new version of the plugin, 4.17.7. We are at 4.17.5.

**Comment by kevinkidwell** [comment]
@jgreidy Our plan was renewed and is good through August 1, 2021. The subscription is only for the add-ons, though. The core plugin is free. To update it, I found this in their documentation: https://kb.wprssaggregator.com/article/239-how-to-update-the-core-plugin
