### ISSUE TITLE
CULU Accessibility Review August 2020

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#867]
@kevinkidwell while you work on #866, if you see accessibility issues that could be applied to the CULU theme, please add them here.

**Comment by kevinkidwell** [comment]
- [ ] Clear Filters button on all units is too light of a red. The css class for this is `.elementor-element.elementor-button-danger .elementor-button`. If you have a specific darker red that's in use elsewhere I think we could go with that, otherwise maybe use Cornell red (#B31B1B).

**Comment by manolobevia** [comment]
CULU theme is in good shape
<img width="328" alt="Screen Shot 2020-08-31 at 2 20 22 PM" src="https://user-images.githubusercontent.com/8395482/91753000-329c9b00-eb95-11ea-85ba-89096a3d8bc5.png">
I will review again in September.
