### ISSUE TITLE
Upstream Release/v1.4.7

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#868]
Creating this issue for items that need to be included in next upstream.

1. LibCal Hours needed an update after seeing an issue with Vet's hours not updating. The problem is the transient created to hold hours data doesn't expire, when it should be expiring every 60 seconds. I haven't cut a new release for the hours plugin in case more needs done to it before a new upstream is put together.
2. WP Custom Loops plugin will need included for some language updates and for Math's new Recommended Books loop.

**Comment by manolobevia** [comment]
@kevinkidwell we could add manually the new libcal updated plugin for now to all units. This is not ideal, but faster than doing a new upstream and updating all units.

**Comment by kevinkidwell** [comment]
@manolobevia This code has been on the sites for a while and we hadn't seen any issues with it before. I can go in and clear the transients that are used as units re-open so it's not a big deal to hold off on this until we have a few more things to include in an upstream. I have Erin from Vet keeping an eye out for any issues she sees with the hours. If more issues crop up, then I think it we go through putting it up on all units if no upstream is ready to go.

**Comment by manolobevia** [comment]
@jgreidy please add the following plugins below to the upstream. We need these ones for refactoring staff. Thanks.
- [Distributor](https://distributorplugin.com/) 
- [ACF 2 Rest API](https://wordpress.org/plugins/acf-to-rest-api/)
- [Application password](https://wordpress.org/plugins/application-passwords/)

**Comment by manolobevia** [comment]
@jgreidy please update to WP core release 5.5.1

**Comment by jgreidy** [comment]
@kevinkidwell @manolobevia @cappadona I'm starting to work in a new upstream for ULS. Please update the issue if you'd like something else added/removed from v1.4.7

**Comment by cappadona** [comment]
Thanks @jgreidy.

@kevinkidwell & @manolobevia Do you want to include the [CULU theme](https://github.com/cul-it/wp-cul-theme-culu) or [LibCal hours plugin](https://github.com/cul-it/wp-libcal-hours) in this upstream release?

**Comment by jgreidy** [comment]
@manolobevia I can not log in to https://www.advancedcustomfields.com/my-account/ using the credentials from LastPass. Can you update the credentials for Advanced Custom Fields PRO?

**Comment by manolobevia** [comment]
@jgreidy sending via slack credentials. I can't access LastPass, I need to write CIT to reset my password.

**Comment by manolobevia** [comment]
@jgreidy Yes, we would like to include theme changes and LibCal Hours plugin, but the plugin still needs some work.

**Comment by jgreidy** [comment]
@kevinkidwell Could you tag the version of wp-libcal-hours you want me to use for this upstream? The last tag was v2.0.3.

**Comment by jgreidy** [comment]
@kevinkidwell Could you also tag the version of wp-custom-loop-widget you want me to use? The last tag was v1.2.1.

**Comment by jgreidy** [comment]
@manolobevia Could you tag the version of wp-cul-theme-culu you want me to use for the upstream? The last tag was v1.4.2.

**Comment by kevinkidwell** [comment]
The WP Custom Loop plugin is v1.2.2: https://github.com/cul-it/wp-custom-loop-widget/releases/tag/v1.2.2

**Comment by jgreidy** [comment]
## [v1.4.7] - 2020-10-26
### Changed
- wordpress-composer 5.5.1 update WordPress core - see [Field Guide](https://make.wordpress.org/core/)
- [Advanced Access Manager v6.7.0](https://wordpress.org/plugins/advanced-access-manager/#developers)
- [Advanced Custom Fields: Image Aspect Ratio Crop Field v4.1.2](https://wordpress.org/plugins/acf-image-aspect-ratio-crop/#developers)
- [Advanced Custom Fields Pro v5.9.1](https://github.com/cul-it/advanced-custom-fields-pro/blob/master/readme.txt)]
- [Akismet Anti-Spam v4.1.7](https://wordpress.org/plugins/akismet/#developers)
- [Better Font Awesome v1.7.4](https://wordpress.org/plugins/better-font-awesome/#developers)
- [Coming Soon Page & Maintenance Mode v6.0.8.3](https://wordpress.org/plugins/coming-soon/#developers)
- [Custom Post Type UI v1.8.1](https://github.com/WebDevStudios/custom-post-type-ui/)
- [Elementor v3.0.12](https://wordpress.org/plugins/elementor/#developers)
- [Elementor Pro v3.0.5](https://github.com/cul-it/elementor-pro/blob/master/changelog.txt)
- [FileBird Lite v4.0.7](https://wordpress.org/plugins/filebird/#developers)
- [JSON Content Importer v1.3.10](https://wordpress.org/plugins/json-content-importer/#developers)
- [Native PHP Sessions for WordPress v1.2.1](https://github.com/pantheon-systems/wp-native-php-sessions#changelog)
- [PublishPress Capabilities v1.10.1](https://wordpress.org/plugins/capability-manager-enhanced/#developers)
- [Redirection v4.9.1](https://wordpress.org/plugins/redirection/#developers)
- [Relevanssi v4.8.3](https://wordpress.org/plugins/relevanssi/#developers)
- [WP Mail SMTP v2.5.0](https://wordpress.org/plugins/wp-mail-smtp/#developers)
- [WP RSS Aggregator v4.17.8](https://wordpress.org/plugins/wp-rss-aggregator/#developers)
- [wp-custom-loop-widget v1.2.2](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)


### Added
- [Distributor v1.6.0](https://github.com/10up/distributor/blob/develop/CHANGELOG.md)
- [ACF to REST API v3.3.2](https://wordpress.org/plugins/acf-to-rest-api/#developers)
- [Application Passwords v0.1.2](https://github.com/WordPress/application-passwords/releases)
