### ISSUE TITLE
Design hours display in different scenarios.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#872]

**Comment by manolobevia** [comment]
Created different scenarios. Pending resolution of[ #38](https://github.com/cul-it/wp-libcal-hours/issues/38)

Scenario 1 - One single unit
![single unit](https://user-images.githubusercontent.com/8395482/109324852-3b5bea00-7823-11eb-9f51-3768f5f31b36.png)

Scenario 2 - Two units - v1
![two units - v1](https://user-images.githubusercontent.com/8395482/109324860-3dbe4400-7823-11eb-929c-0d8503768117.png)

Scenario 2 - Two units - v2
![two units - v2](https://user-images.githubusercontent.com/8395482/109324875-40b93480-7823-11eb-83cb-e5886a717109.png)

Scenario 3 -  One unit and one department
![single unit and department](https://user-images.githubusercontent.com/8395482/109324891-444cbb80-7823-11eb-9b30-e869caa8de1b.png)

**Comment by eeh53** [comment]
@manolobevia We showed this to Jessa yesterday for Olin & Uris and she strongly preferred scenario 2, v. 1

**Comment by manolobevia** [comment]
@eeh53 thanks. What about Scenario 3 for library + departments hours?

**Comment by eeh53** [comment]
@manolobevia As discussed in our meeting yesterday, I think scenario 3 is good to go!

**Comment by manolobevia** [comment]
@sew268 @eeh53 are we ok using **scenario 3** for Mann, or you want to use **Scenario 2 - Two units - v1** for Mann too?

**Comment by sew268** [comment]
@manolobevia scenario 3 for Mann is my preference...what do you think @eeh53?

**Comment by eeh53** [comment]
@manolobevia @sew268 Yes, that sounds good to me as well. We'll use scenario 3 for libraries that want both their library hours and an additional department's hours displayed.
