### ISSUE TITLE
Create custom Elementor widget for alerts in CULU.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#877]
Basic Requirements:
- User will be able to select type of alert (notification, alert, etc)
- User will be able to add copy to alert
- <del>Select location (all pages or just current page)</del>. Simple notification banner plugin takes care of adding a banner to all pages.

(Please add above)

**Comment by manolobevia** [comment]
@kevinkidwell If you want to check this new widget, please download this culu theme, 
[culu-dev-alertWidget.zip](https://github.com/cul-it/uls/files/5314462/culu-dev-alertWidget.zip), then upload it to https://dev-uls-mann-library-cornell-edu.pantheonsite.io/. After that, enable the new theme and edit a page in elementor adding  the 'Notification Alert Banner' widget located under `basic` category. Thanks.

**Comment by kevinkidwell** [comment]
@manolobevia I think that works well for being able to add the banners in and let them be edited by stakeholders! One thing, is it possible to create an option for them to select the icon at the front of the banner? I'm thinking of our COVID banners right now being an alert banner but having the exclamation icon so it would be useful for them to be able to select the icon.

I also noticed in the rich text editor area, there's no padding to keep the text off the side. Is that part of an elementor update or the admin theme or something else? The current editor on live unit sites has some padding there to keep text off the edges.

**Comment by manolobevia** [comment]
@kevinkidwell I can add the exclamation icon to the alert banner like here at https://www.library.cornell.edu/libraries/africana. If we give options, we are not going to see consistency. 

Yes, I switched back to the core admin theme and no padding issues. There is an update for the Slate Theme Admin plugin. Let me try to update and see if that fixes it.

**Comment by manolobevia** [comment]
@kevinkidwell it doesn't fix the padding issue. Also when I edit an elementor page, I get access denied when I use the text edit widget. I have disabled the Slate admin theme and back to normal. I'll check if there are another admin themes and add it to the upstream, but activating it on dev sites only, that way we don't change things for stakeholders. What do you think? Do you have any preference on admin themes? I have checked a lot and Slate was great, but introduce problems with Elementor.

**Comment by manolobevia** [comment]
@kevinkidwell changed alert icon.
[culu-dev-alertWidget.zip](https://github.com/cul-it/uls/files/5319248/culu-dev-alertWidget.zip)

**Comment by manolobevia** [comment]
@kevinkidwell if everything is ok, can you approve the PR?

**Comment by manolobevia** [comment]
@kevinkidwell adding culu-dev theme with the branch for the widget , so you don't need to do any local setup. Just add to dev this theme.
[culu-dev-widget-elementor-alert.zip](https://github.com/cul-it/uls/files/5329886/culu-dev-widget-elementor-alert.zip) Thanks

**Comment by manolobevia** [comment]
@kevinkidwell I have added a culu theme that includes the widget, and it is activated. Please go to https://dev-uls-mann-library-cornell-edu.pantheonsite.io/ and check the new widget. Let me know if you have any feedback.
