### ISSUE TITLE
Distributor doesn't pull images using ACF Image Aspect Ratio Crop.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#880]
In staff ACF group, we are using an ACF via ACF Image Aspect Ratio Crop plugin for cropping images. It looks like Distributor doesn't recognize this field. Images from staff are not pulled from MANN and OLINURIS to CULU.

**Comment by manolobevia** [comment]
From Distributor team: 

> @manolobevia Maybe this comment can give you some inspiration for handling custom fields distribution: [#609 ](https://github.com/10up/distributor/issues/609#issuecomment-656022292)(comment)

**Comment by cappadona** [comment]
Duplicate. Covered by cul-it/wp-cul-theme-culu#63.
