### ISSUE TITLE
Review proposed events management with stakeholders

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#888]
Identify and engage stakeholders (staff who's responsibility it is to enter events in respective systems) to finalize a decision on the workflow process

> See [#841](https://github.com/cul-it/uls/issues/841#issuecomment-696737413) for background.

**Comment by cappadona** [comment]
Advice from the CU Events administrator:

> It should be noted, though, that if an event is removed from your feed that it will not be removed from Localist, so it would have to be removed manually from there as well. We therefore advise that events are not removed from their source, but rather have their titles prepended or appended with words such as "cancelled" or the like, so that anyone who has Localist events feeding onto their personal calendars will see that update. Otherwise, the removal of the event, even in Localist, does not carry through to their calendars.

**Comment by cappadona** [comment]
@eeh53 Since we've decided to stick with our existing workflow and [use Localist widgets](https://github.com/cul-it/uls/issues/819) for the foreseeable future, do you prefer to close this or put it in the Icebox?

**Comment by eeh53** [comment]
@cappadona Let's icebox it for now, I think. And I can circle back to the folks we talked to about this (Rob & Xan, Michelle Eastman, Zsuzsa, Eveline & Jenny) and mention that we're putting this on hold for the moment.

**Comment by eeh53** [comment]
It can be closed. We decided not to go in this direction for event management. Thanks!

**Comment by JesiBuell79** [comment]
Thank you!
