### ISSUE TITLE
Create WP Pantheon instance for future development of www.library.cornell.edu

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#889]
- Instance name:  `uls-library-cornell-edu`
- Apply CULU upstream to this new instance
Thanks

**Comment by jgreidy** [comment]
I submitted the site to CIT for an upgrade to 'Basic'. This is the part that takes 7 days or so. I still need to set up email and shibboleth on the site.

**Comment by manolobevia** [comment]
@jgreidy Thank you.
