### ISSUE TITLE
Display tags as facets on category pages

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#89]
In knowing the functionality that PSL is looking for with being able to sort by the tags within a specific category, this is something that we should be thinking about.

https://facetwp.com/
I found this plugin which I downloaded on my personal test instance and was able to actually get facets displaying on category pages, and only the tags that belong within that category are displayed. We can add the demo version of this to the site for now but it will only show 2 facets until it is purchased. What we will need to do is add in a sidebar where we can add a shortcode (or create a template where we can add in the PHP for the display) to be able to get the facets to show up but I think this is going to be our best bet for creating these filterable pages without coding it all by hand.

Any thoughts on this? Do you think we should add in the demo before we launch PSL and work on adding it in to spruce up the category pages and make them more usable?

**Comment by manolobevia** [comment]
That plugin is the plugin we should use for facets. I checked this before too, and I was really surprised of what it does. It is great. It cost around $250 for 20 sites. To be honest with you, we shouldn't have a display with 400 items. As we talk, we should have a canned search on the catalogue.  USers are not going though a list of 400 items for core books. Users will use google, what his/her colleagues are reading, or what the professor recomen. Also, this site has a 20 visit avaerage per day. This is somethign that should CLO needs to review.
