### ISSUE TITLE
Wireframe upcoming events list

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#908]
List of upcoming events to be used on the homepage and news & events landing page as mentioned in #819.

- [ ] Default to the next `3` or `5`upcoming events
   - Allow this number to be overridden per instance
- [ ] Link to event (in LibCal or Localist?)

**Comment by cappadona** [comment]
@manolobevia In discussing this last week, we think what you did for Asia upcoming events (styling Localist widget) could work for Mann as well.

**Comment by manolobevia** [comment]
![screencapture-uls-mann-library-cornell-edu-lndo-site-news-2021-02-26-11_33_53](https://user-images.githubusercontent.com/8395482/109327794-b5da3900-7826-11eb-97d1-78e010609743.png)

**Comment by manolobevia** [comment]
Display event list on homepage.

<img width="1545" alt="Screen Shot 2021-03-03 at 11 48 54 PM" src="https://user-images.githubusercontent.com/8395482/109912992-2942d700-7c7b-11eb-8b4c-9e01b979d8df.png">
