### ISSUE TITLE
Wireframe events calendar

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#909]
~Use current [Mann events calendar](https://mannlib.cornell.edu/news-events/events/calendar) as inspiration, as described in #819.~

## 2021-02-01 Update

@manolobevia In discussing this last week with the Mann stakeholders, we're wondering whether we should shift gears and focus on using a [Localist widget](https://events.cornell.edu/help/widget) for this as well (type: `Mini Calendar + List` under **Display Options**).

Will you review when you get a chance and let us know if you think this is a viable option?

**Comment by manolobevia** [comment]
Yes. It is. I am currently working on it.

**Comment by manolobevia** [comment]
Attaching a visual for the events + calendar page:

![screencapture-uls-mann-library-cornell-edu-lndo-site-events-calendar-2021-02-25-10_42_52](https://user-images.githubusercontent.com/8395482/109178026-6b898700-7756-11eb-9d31-5d4e4b873285.png)
