### ISSUE TITLE
ULS UNITS PSL - Point physicalsciences.library.cornell.edu to pantheon's production repo.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#92]
@gdelisle **physicalsciences.library.cornell.edu** needs to point to the  Pantheon's project  (`physicalscienceslibrarycornelledu`). @kevinkidwell will let you know when PSL finish adding content.

Also, @jgreidy can you force all HTTP to HTTPS?

**Comment by gdelisle** [comment]
Domain has been moved, https is not yet forced.
