### ISSUE TITLE
Asia Site development epic

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#926]
Development Team To-do list:
- Add Tamar and Emily to the staff profiles
- Addition to the staff profiles, ability to add country and language expertise (included in next upstream)
- Need to redo feed of staff profiles onto the appropriate collections pages (will be done after updated staff profiles views implemented)
- Move all Subject Guides to Other Resources, remove Subject Guides post type from the backend, delete page, and remove from navigation
- Change text in navigation from Library Guides to Library/Subject Guides
- Change the Guides section on each country page to be a text box to add content instead of a list fed in from post type
- Look at feeding in department events and library hosted events from localist (potentially post launch pending developer progress) 
- Check that South Asia’s Research Tools have been brought over, as well as electronic resources.  
- Addition of option for a text box with customizable content at the top of each country page
- Add text box to the top of all Southeast Asia country pages
- Add the option to be able to select Featured resources for Databases, Books, Book Chapters, Other Resources, etc.
- Remove footer logo (theme edit will be needed)
- Add Subject to the Databases custom post type
- Change wording of Country filter to Region
- Under the newly named Region filter, add General Asia and rename Southeast Asia to General Southeast Asia
- Homepage:
- Add new books after receiving the list of URLs
- Add Collections like the current site
- Country pages:
- Research how to best add a list of other pages within each collection (similar to current site)
 
Developer questions for Asia Staff:
Events:
- Do they want these events intermingled with Library events on the homepage and events calendar? (see [original question in #819](https://github.com/cul-it/uls/issues/819#issuecomment-716607903))
- If not, how will they be used? On which pages do they need to appear and will they always be combined into a single listing or do they want a separate listing for each?

 
Asia Staff To-do list: 

- Send Kevin the order for Staff on the Staff Profiles page
- Create content for all the landing pages that correlate with the top level navigation: About Us, Collections, Use the Library, Services, News & Events
- Send content for the student employment page
- Review the broken links in the Box folder and update - these have been migrated and are showing as broken on the dev site.  Once in, we can update the site to either remove or edit links.  Please note in Box if something should just be deleted.
- -                  End of November deadline
- Answers to above developer questions about events
- Aparna: reach out and discuss questions for Floor Maps
- -                  Need to go through floor maps and let Kevin know the following: 1) information or text for those areas that are numbered 2) if any numbers exist that should not 3) if any areas are not numbered that should be.
- Bridging Worlds exhibit under South Asia Collection: https://asia.library.cornell.edu/collections/southasia/bridging-worlds.  Seems like it might be better if we treated it like this: https://exhibits.library.cornell.edu/films-mills-and-poets?q?
- -                  Speak with Bronwen about this content
- Send the list of URLs for each country/collections where the feed for New Books should come from in the catalog
- Need some text describing the Rawson Reading room - does it need reservation?  What type of study happens there?  How many people does it hold?
- Send the list of names of people who would be content editors on the site and then we can schedule training on how to use WordPress.
- Think about the text used for headings and categories and how to organize the content on Other Resources for filtering because it is currently confusing
- Determine if there is a need to add links to other programs on the Southeast Asia page

**Comment by cappadona** [comment]
@kevinkidwell @arh269 I added a reference to the original question in the description above about intermingling of department/program and library events for the Asia site.
