### ISSUE TITLE
ULS UNITS - Hotel: Setup site in pantheon.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#93]
The Hotel Library site needs to be ready Jan 23rd. Please setup this site in Pantheon as soon as you can. This is the domain, `http://hotel.library.cornell.edu` , we have to redirect to the live pantheon project.

Thanks

**Comment by kevinkidwell** [comment]
From slack: hotellibrarycornelledu has been provisioned. It should be ready for the domain transfer Jan 15.
