### ISSUE TITLE
Staff profile count inventory.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#930]

**Comment by manolobevia** [comment]
| Unit 	| Staff Count 	| 
|---	|---	|
| Annex         | 9| 
| Hotel         | 3| 
| Music         | 8| 
| Management    | 6| 
| Psl           | 2| 
| Africana      | 4| 
| Finearts      | 5| 
| Law          | 18| 
| Asia         | 24| 
| ILR          | 19| 
| Engineering   | 5| 
| Math          | 2| 
| Rare         | 33| 
| ann         | 23| 
| OLINURIS     | 43| 
| Vet         |   4| 
| **TOTAL**         |   **208**| 
| ......| |
| Makerspace   |  4|

**Comment by cappadona** [comment]
@manolobevia Where did you get these counts? For Mann, using the [current staff directory](https://mannlib.cornell.edu/about/staff), I have **37** after I subtract 7 CUL-IT staff and one retiree.

**Comment by manolobevia** [comment]
@cappadona From https://dev-uls-mann-library-cornell-edu.pantheonsite.io/
@kevinkidwell the current staff profiles on asia, olin-uris, and mann are final?

**Comment by kevinkidwell** [comment]
@manolobevia No, Mann and Olin/Uris will likely have to be updated again before the sites launch. Asia should have all staff added, though.
