### ISSUE TITLE
Update nightly LibCal -> Localist feed to include new calendar

### ISSUE THREAD

**Issue by cappadona** [cul-it/uls#939]
@eeh53 has created a new **CUL Events & Exhibits** calendar in LibCal that we want to include in the feed to Localist.

**Comment by cappadona** [comment]
@eeh53 I think this is ready to go but holding off on deploying it until we have some test data in each calendar.

**Comment by JesiBuell79** [comment]
@eeh53 is this resolved?

**Comment by eeh53** [comment]
I believe it is. This can be closed.

**Comment by JesiBuell79** [comment]
Thank you!
