### ISSUE TITLE
Build new Upstream - v1.4.13

### ISSUE THREAD

**Issue by jgreidy** [cul-it/uls#957]
- @cappadona via Slack
  > Quick heads up that I cleaned up the version discrepancy in wp-libcal-hours, so the release that will be included in this upstream is [v2.1.0](https://github.com/cul-it/wp-libcal-hours/releases/tag/v2.1.0)

- Remove Classic Editor

**Comment by manolobevia** [comment]
@jgreidy new [theme release](https://github.com/cul-it/wp-cul-theme-culu/releases/tag/v1.5.1) is ready.
Please update plugins too if you can. The hours and custom loops plugins need to be added too.
THANK YOU!

**Comment by jgreidy** [comment]
## [v1.4.13] - 2021-01-21
### Removed
- Classic Editor v1.6
### Changed
- [ACF Better Search v3.8.0](https://wordpress.org/plugins/acf-better-search/#developers)
- [Advanced Custom Fields Pro v5.9.4](https://github.com/cul-it/advanced-custom-fields-pro/blob/master/readme.txt)]
- [Coming Soon Page & Maintenance Mode v6.0.10.1](https://wordpress.org/plugins/coming-soon/#developers)
- [Google Analytics Dashboard v6.5.0](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/#developers)
- [Redirection v5.0](https://wordpress.org/plugins/redirection/#developers)
- [WP RSS Aggregator v4.17.10](https://wordpress.org/plugins/wp-rss-aggregator/#developers)
- [WP Custom Loop Widget v1.2.3](https://github.com/cul-it/wp-custom-loop-widget/blob/master/CHANGELOG.md)
- [WP Libcal Hours v2.1.0](https://github.com/cul-it/wp-libcal-hours/blob/dev/CHANGELOG.md)
- [CULU Theme v1.5.1](https://github.com/cul-it/wp-cul-theme-culu/releases/tag/v1.4.2)
