### ISSUE TITLE
Review latest update of Libcal hours  plugin

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#961]
@kevinkidwell Below are the hour statuses display using the latest version of the plugin.

- ILR: No hours display. Checked on Jan 24 at 4:14pm the status is closed.
- Management: Displays [libcal_status_now lid="3363"].
- Mathematics: No display. Checked on Jan 24 at 4:16pm, but the status is closed.
- Music: Checked on Jan 24 at 4:17pm the status is closed, but no display.
- OlinUris: Olin ok. Uris no hour status.
- Psl: Checked on Jan 24 at 4:19pm the status is closed, but no display.

**Comment by kevinkidwell** [comment]
I've updated the hours plugin to have the Closed status. This will fix the issues for ILR, Math, Music, Uris, and PSL.

New version release with fix: https://github.com/cul-it/wp-libcal-hours/releases/tag/2.1.1

**Comment by manolobevia** [comment]
@kevinkidwell thanks for fixing it.
