### ISSUE TITLE
Create new upstream (v1.4.17)

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#972]
@jgreidy @kevinkidwell this one will include latest plugin hours update. I will confirm when the release is ready.

**Comment by kevinkidwell** [comment]
Latest release for the Hours plugin has been cut and is available here: https://github.com/cul-it/wp-libcal-hours/releases/tag/v2.1.2

**Comment by jgreidy** [comment]
Problem 1
    - The requested package wpackagist-plugin/google-analytics-dashboard-for-wp (locked at 6.5.0, required as 6.5.1) is satisfiable by wpackagist-plugin/google-analytics-dashboard-for-wp[6.5.0] but these conflict with your requirements or minimum-stability.

As a result of this ^^^ we're sticking with 6.5.0 for now.

**Comment by jgreidy** [comment]
## [v1.5.0] - 2021-02-04
### Changed
- [WordPress v5.6.1](https://make.wordpress.org/core/)
- [Advanced Custom Fields: Image Aspect Ratio Crop Field v5.1.0](https://wordpress.org/plugins/acf-image-aspect-ratio-crop/#developers)
- [Anywhere Elementor - v1.2.3](https://wordpress.org/plugins/anywhere-elementor/#description)
- [Elementor v3.1.1](https://wordpress.org/plugins/elementor/#developers)
- [Google Analytics Dashboard v6.5.1](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/#developers)
- [Relevanssi v4.11.0](https://wordpress.org/plugins/relevanssi/#developers)
- [WP Mail SMTP v2.6.0](https://wordpress.org/plugins/wp-mail-smtp/#developers)
- [WP SAML Auth - 1.1.1](https://wordpress.org/plugins/wp-saml-auth/#developers)
- [WP Libcal Hours v2.1.2](https://github.com/cul-it/wp-libcal-hours/blob/dev/CHANGELOG.md)
