### ISSUE TITLE
Create template for Mannifest in Mailster

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#977]

**Comment by kevinkidwell** [comment]
Template for Mailster has been created. The way that I focused on this was to allow for drag-and-drop modules, the same that staff was used to in Mailchimp. 

An example Mannifest has been created for the Fall 2019 issue to show how it looks in Mailster: https://dev-uls-mann-library-cornell-edu.pantheonsite.io/newsletter/mannifest-fall-2019/

Modules that have been created for use:
- Full size image
- Heading
- Separator
- Text Block
- Event

@sew268 @eeh53, let me know if there are any adjustments that should be made to this!

**Comment by eeh53** [comment]
@kevinkidwell I think this looks great! Though I do think we'll need to play around with the header now that the new CUL branding has been released. I will talk to Eveline and Daisy about this.
