### ISSUE TITLE
Setup Mann equipment page.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#991]
@sew268 I have created a template here at https://dev-uls-mann-library-cornell-edu.pantheonsite.io/equipment/. Let me know if you want me to add real content.

**Comment by sew268** [comment]
adding @eeh53 to this so she can take a look as well; she knows the equipment lending better than I do at this point and can weigh in

**Comment by cappadona** [comment]
Pinging @eeh53

**Comment by manolobevia** [comment]
@sew268 @eeh53 Equipment will be dynamically render from libcal. Please ignore the template I have created.

**Comment by manolobevia** [comment]
@eeh53 thanks. It will look the same.
