### ISSUE TITLE
Mann URL for launch

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#992]
@sew268 @eeh53 I don't know if this was brought up before and was just something I thought of this morning. When we launch Mann, are we planning to bring the domain name (URL) into line with all the other unit library sites?

This would mean the site would be on mann.library.cornell.edu.
We would have to redirect mannlib.cornell.edu to the pages on that site.
If we do that, we'll want to set up redirects like we've done for a couple of other units.

My thoughts on this are that we should do that, for consistency. Where else would we need to update the link to the site (main site, catalog, etc.) if we do this?

Also tagging in @cappadona in case he has any thoughts on this.

**Comment by cappadona** [comment]
@kevinkidwell Thanks for creating this...it's been on my mind.

Currently we [redirect `mann.library.cornell.edu` --> `mannlib.cornell.edu`](https://github.com/cul-it/web-redirector/blob/master/mann.library.cornell.edu.conf).

Even though I'd prefer to keep our URL, I do agree that we should be consistent and fall in line.

**Comment by gdelisle** [comment]
I am just interested in this discussion, commenting so I get notified of replies.

**Comment by eeh53** [comment]
@kevinkidwell I agree with @cappadona - we should probably be consistent with the other library unit sites. I think as long as we change it on the main site and I make sure Eveline and her team know the new address for outreach materials, we should be good.

**Comment by cappadona** [comment]
Thanks @eeh53.

I'm not saying we shouldn't update the link from `library.cornell.edu`, but I just want to clarify that even if we don't, all references to the Mann homepage at `mannlib.cornell.edu` will continue to work due to the `mannlib.cornell.edu` to `mann.library.cornell.edu` redirect we put into place coordinated with the launch of the new site.

**Comment by eeh53** [comment]
@cappadona Thanks, understood!

**Comment by cappadona** [comment]
Not quite yet 😉
