### ISSUE TITLE
Mann hours in hero box

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#994]
Most unit sites just show "Open until 10pm".  Mann's says "Mann: Open until 10pm"
I checked in Libcal to see if this was a content or text entry issue and I don't think it is...

**Comment by cappadona** [comment]
I believe @manolobevia plans to take care of this as part of #872.

> Which is tied to the recent decision in cul-it/wp-libcal-hours/issues/38

**Comment by kevinkidwell** [comment]
This was fixed in [this PR](https://github.com/cul-it/wp-libcal-hours/pull/51) in the LibCal Hours plugin and will be pushed with the next upstream.

**Comment by cappadona** [comment]
Thanks @kevinkidwell I still think we need to resolve the [handling of locations that are open 24 hours](https://github.com/cul-it/wp-libcal-hours/issues/47) before we stick a fork in this.

@sew268 & @eeh53 I remember you mentioning you wanted to use the Lobby hours in the header and it looks like there was a recent name change to one of our departments: **Lobby/Contactless Pickup**. Is that the secondary header hours we'll use for the Mann site?

Here's how it currently renders:

![Screenshot_2021-03-18 Mann Library](https://user-images.githubusercontent.com/409842/111664102-d2471100-87e7-11eb-8961-a4b49c7051f4.png)

**Comment by kevinkidwell** [comment]
@cappadona I believe the [Add declaration for 24 Hours display](https://github.com/cul-it/wp-libcal-hours/pull/50) PR fixes that issue. I know you left a comment about breaking out some of the underlying functions. Do you have any specifics you'd want to see before that got pushed that I could work on so we can get it out before launch?

**Comment by cappadona** [comment]
@kevinkidwell Correct, I hadn't heard back from you on that one. It's been a while so let me take a look at it again (hopefully before the end of the day and we can pick up the thread in that PR...deal?

**Comment by sew268** [comment]
@cappadona I made that wording change this morning which I hope @eeh53 thinks is ok.  I thought it would be easier to do that then set up another department for the lobby.  Is there a way to remove 'closed-opens today' and the parantheses around 24 hours?  Maybe that's something that Tobi & I need to fix in LibCal??

**Comment by cappadona** [comment]
Thanks @sew268. That awkward handling of locations open 24hrs is exactly what the pull request (https://github.com/cul-it/wp-libcal-hours/pull/50) Kevin and I are discussing above will address. So nothing more you need to do in LibCal for now. We'll send you a heads up once we have the tweak in play so you can review.

**Comment by cappadona** [comment]
@kevinkidwell I just approved the PR as is, we can cleanup later.

@sew268 Here's how the Mann header hours render with Kevin's improvements.

![Screenshot_2021-03-18 Mann Library(1)](https://user-images.githubusercontent.com/409842/111684971-c23a2c00-87fd-11eb-80f2-876583e4de93.png)

**Comment by sew268** [comment]
@cappadona @kevinkidwell that looks beautiful! :)

**Comment by cappadona** [comment]
Thanks but all credit goes to @kevinkidwell & @manolobevia 👏🏼

**Comment by manolobevia** [comment]
I still need to do my part ;)
