### ISSUE TITLE
secondary department hours

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#995]
If we want to set this up to show that the lobby is 24/7 - how do we do this?  Put an entry in LibCal?

**Comment by cappadona** [comment]
@sew268 Correct, the hours are pulled dynamically from LibCal. Currently we don't have an entry for the Mann Lobby.

You can manage which hours are used in the header by going to **Settings** > **LibCal Hours** within the WP admin.

<img width="661" alt="Screen Shot 2021-03-11 at 3 04 39 PM" src="https://user-images.githubusercontent.com/409842/110847914-7c201e00-827b-11eb-87a8-71a1460d63f5.png">

**Comment by sew268** [comment]
@cappadona thanks, that's just what I needed! :)
