### ISSUE TITLE
Homepage feature box content issue

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#996]
Feature boxes are set and are pulling content from appropriate pages.  But we've run into an issue for those pages that have alert boxes, as that is the content this is being pulled in.  This wouldn't be too problematic except that instead of showing the alert icon, it reads "error alert".  The Services feature box when showing Disciplinary Research Support is a good example.  What might our solutions to this issue be?

**Comment by cappadona** [comment]
@sew268 Do you have a screenshot and/or URL? Also, which browser are you using? It sounds like you're seeing text meant only for a screen reader.

![Screenshot_2021-03-11 Disciplinary Research Support – Mann Library](https://user-images.githubusercontent.com/409842/110848590-4465a600-827c-11eb-80f6-f9c77850f6f2.png)

**Comment by sew268** [comment]
@cappadona using Chrome, didn't try other browsers.  Here's screenshot:

![Capture](https://user-images.githubusercontent.com/14821406/110848924-9eff0200-827c-11eb-9301-1e871d1394b8.PNG)

**Comment by sew268** [comment]
@cappadona I see the icon clearly on the discplinary research support page, but it's when the content is pulled into the feature box on the homepage that the icon gets lost

**Comment by cappadona** [comment]
@sew268 Thanks for clarifying. I will leave this in the capable hands of my colleagues 🎩

**Comment by manolobevia** [comment]
I am not sure if using the elementor post widget is the best option.

**Comment by manolobevia** [comment]
[#118](https://github.com/cul-it/wp-cul-theme-culu/issues/118) fixed the issue.
