### ISSUE TITLE
Hero Content Banner Image

### ISSUE THREAD

**Issue by sew268** [cul-it/uls#997]
I've tried multiple times now to switch the image and nothing seems to take - I'm following the training guidelines to the letter. ;)

**Comment by manolobevia** [comment]
<img width="338" alt="Screen Shot 2021-03-11 at 3 25 35 PM" src="https://user-images.githubusercontent.com/8395482/110850925-59433900-827e-11eb-8753-d17be40e15e0.png">

@sew268 You need to add the image to the tablet and mobile versions too. With Vet we provided the fubtionality to add different hero images depending on device type.

**Comment by sew268** [comment]
@manolobevia got it - thanks!

**Comment by manolobevia** [comment]
@sew268 or optimized graphic versions of the hero image for different devices. The current image is 3 megabytes for desktop, huge for small devices. I would provide a version for mobile and tablet. The hero image also looks compressed vertical. If you want, please send me the original image and I'll fix the issue.

**Comment by manolobevia** [comment]
We should provide guidelines for optional size for hero images.

**Comment by kevinkidwell** [comment]
I did have the dimensions listed in the training guide that has gone out to content editors. You can see it on [slide 45 of this presentation](https://docs.google.com/presentation/d/1gynviw3bpBGTXF0cIU0N0FnEmap0mtb0k_-DY4KQviA/edit#slide=id.g616335afcd_0_169).

**Comment by manolobevia** [comment]
@kevinkidwell Perfecto!!! Thanks.

**Comment by manolobevia** [comment]
Closing this issue since I see hero image in mobile, tablet, and desktop devices.
