### ISSUE TITLE
Change category term blog on dev Mann library to news.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#998]
@sew268 @kevinkidwell @eeh53 I will be changing all the post with category `blog` to `news` to be more consistent with the category `featured news`. @kevinkidwell will that cause and issue if you already has established the use of category blog in the content guidelines?

**Comment by kevinkidwell** [comment]
That shouldn't impact anything with the documentation or other functionality with content!

**Comment by eeh53** [comment]
@manolobevia So just to make sure I understand correctly (since I'm the one adding all these news items to the Mann dev site) - I don't need to add the blog category to these anymore? Just featured news?

**Comment by manolobevia** [comment]
@eeh53 Any news you add will have the category `news`. For those that will be featured news, you'll need to add the `featured news` category too.

**Comment by manolobevia** [comment]
@eeh53 here is a [screenshot](https://github.com/cul-it/wp-cul-theme-culu/pull/106#issuecomment-796897220) of the featured news slider/carousel, I have implemented. 

I have a requirement for all the `featured images`. The size needs to be 1529 (width) x 852 (height) pixels (jpeg). I want to clarify you can add any image size to the content of a news post.

**Comment by eeh53** [comment]
@manolobevia Thanks for sharing the screenshot, I think that looks great! Will this also solve the problem of not having the homepage reload every time a user tries to advance to the next news story?

Thanks for adding the requirement for the image size for the feature image. As you could probably see, I was struggling with that, haha. But good to know that other images can be added to the news post itself without the size restriction.

**Comment by manolobevia** [comment]
@eeh53 Yes. It will load dynamically within the homepage.

**Comment by kevinkidwell** [comment]
The blog category has been changed to news. Can this issue be closed now or are there things that still need done on it?

**Comment by manolobevia** [comment]
Yes. I can close it. Thanks.
